/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaSyncList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaSyncList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaSyncList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaSyncList obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaSyncList(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public static MegaSyncList createInstance() {
    long cPtr = megaJNI.MegaSyncList_createInstance();
    return (cPtr == 0) ? null : new MegaSyncList(cPtr, false);
  }

   MegaSyncList copy() {
    long cPtr = megaJNI.MegaSyncList_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaSyncList(cPtr, false);
  }

  public MegaSync get(int i) {
    long cPtr = megaJNI.MegaSyncList_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new MegaSync(cPtr, false);
  }

  public int size() {
    return megaJNI.MegaSyncList_size(swigCPtr, this);
  }

  public void addSync(MegaSync sync) {
    megaJNI.MegaSyncList_addSync(swigCPtr, this, MegaSync.getCPtr(sync), sync);
  }

}
