/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaAccountPlan {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaAccountPlan(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaAccountPlan obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaAccountPlan obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaAccountPlan(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public boolean isProPlan() {
    return megaJNI.MegaAccountPlan_isProPlan(swigCPtr, this);
  }

  public long getAccountLevel() {
    return megaJNI.MegaAccountPlan_getAccountLevel(swigCPtr, this);
  }

  public MegaStringList getFeatures() {
    long cPtr = megaJNI.MegaAccountPlan_getFeatures(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaStringList(cPtr, false);
  }

  public long getExpirationTime() {
    return megaJNI.MegaAccountPlan_getExpirationTime(swigCPtr, this);
  }

  public long getType() {
    return megaJNI.MegaAccountPlan_getType(swigCPtr, this);
  }

  public String getId() {
    return megaJNI.MegaAccountPlan_getId(swigCPtr, this);
  }

  public boolean isTrial() {
    return megaJNI.MegaAccountPlan_isTrial(swigCPtr, this);
  }

}
