/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaPricing {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaPricing(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaPricing obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaPricing obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaPricing(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public int getNumProducts() {
    return megaJNI.MegaPricing_getNumProducts(swigCPtr, this);
  }

  public long getHandle(int productIndex) {
    return megaJNI.MegaPricing_getHandle(swigCPtr, this, productIndex);
  }

  public int getProLevel(int productIndex) {
    return megaJNI.MegaPricing_getProLevel(swigCPtr, this, productIndex);
  }

  public int getGBStorage(int productIndex) {
    return megaJNI.MegaPricing_getGBStorage(swigCPtr, this, productIndex);
  }

  public int getGBTransfer(int productIndex) {
    return megaJNI.MegaPricing_getGBTransfer(swigCPtr, this, productIndex);
  }

  public int getMonths(int productIndex) {
    return megaJNI.MegaPricing_getMonths(swigCPtr, this, productIndex);
  }

  public int getAmount(int productIndex) {
    return megaJNI.MegaPricing_getAmount(swigCPtr, this, productIndex);
  }

  public int getLocalPrice(int productIndex) {
    return megaJNI.MegaPricing_getLocalPrice(swigCPtr, this, productIndex);
  }

  public double getPriceNetWithDecimals(int arg0) {
    return megaJNI.MegaPricing_getPriceNetWithDecimals(swigCPtr, this, arg0);
  }

  public double getLocalPriceNetWithDecimals(int arg0) {
    return megaJNI.MegaPricing_getLocalPriceNetWithDecimals(swigCPtr, this, arg0);
  }

  public double getAmountWithDecimals(int arg0) {
    return megaJNI.MegaPricing_getAmountWithDecimals(swigCPtr, this, arg0);
  }

  public double getLocalPriceWithDecimals(int arg0) {
    return megaJNI.MegaPricing_getLocalPriceWithDecimals(swigCPtr, this, arg0);
  }

  public double getAmountMonthWithDecimals(int arg0) {
    return megaJNI.MegaPricing_getAmountMonthWithDecimals(swigCPtr, this, arg0);
  }

  public double getMonthlyBasePriceNetWithDecimals(int arg0) {
    return megaJNI.MegaPricing_getMonthlyBasePriceNetWithDecimals(swigCPtr, this, arg0);
  }

  public String getDescription(int productIndex) {
    return megaJNI.MegaPricing_getDescription(swigCPtr, this, productIndex);
  }

  public String getIosID(int productIndex) {
    return megaJNI.MegaPricing_getIosID(swigCPtr, this, productIndex);
  }

  public String getAndroidID(int productIndex) {
    return megaJNI.MegaPricing_getAndroidID(swigCPtr, this, productIndex);
  }

  public boolean isBusinessType(int productIndex) {
    return megaJNI.MegaPricing_isBusinessType(swigCPtr, this, productIndex);
  }

  public boolean isFeaturePlan(int productIndex) {
    return megaJNI.MegaPricing_isFeaturePlan(swigCPtr, this, productIndex);
  }

  public int getAmountMonth(int productIndex) {
    return megaJNI.MegaPricing_getAmountMonth(swigCPtr, this, productIndex);
  }

   MegaPricing copy() {
    long cPtr = megaJNI.MegaPricing_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaPricing(cPtr, false);
  }

  public int getGBStoragePerUser(int productIndex) {
    return megaJNI.MegaPricing_getGBStoragePerUser(swigCPtr, this, productIndex);
  }

  public int getGBTransferPerUser(int productIndex) {
    return megaJNI.MegaPricing_getGBTransferPerUser(swigCPtr, this, productIndex);
  }

  public long getMinUsers(int productIndex) {
    return megaJNI.MegaPricing_getMinUsers(swigCPtr, this, productIndex);
  }

  public long getPricePerUser(int productIndex) {
    return megaJNI.MegaPricing_getPricePerUser(swigCPtr, this, productIndex);
  }

  public long getLocalPricePerUser(int productIndex) {
    return megaJNI.MegaPricing_getLocalPricePerUser(swigCPtr, this, productIndex);
  }

  public long getPricePerStorage(int productIndex) {
    return megaJNI.MegaPricing_getPricePerStorage(swigCPtr, this, productIndex);
  }

  public long getLocalPricePerStorage(int productIndex) {
    return megaJNI.MegaPricing_getLocalPricePerStorage(swigCPtr, this, productIndex);
  }

  public int getGBPerStorage(int productIndex) {
    return megaJNI.MegaPricing_getGBPerStorage(swigCPtr, this, productIndex);
  }

  public long getPricePerTransfer(int productIndex) {
    return megaJNI.MegaPricing_getPricePerTransfer(swigCPtr, this, productIndex);
  }

  public long getLocalPricePerTransfer(int productIndex) {
    return megaJNI.MegaPricing_getLocalPricePerTransfer(swigCPtr, this, productIndex);
  }

  public int getGBPerTransfer(int productIndex) {
    return megaJNI.MegaPricing_getGBPerTransfer(swigCPtr, this, productIndex);
  }

  public MegaStringIntegerMap getFeatures(int productIndex) {
    long cPtr = megaJNI.MegaPricing_getFeatures(swigCPtr, this, productIndex);
    return (cPtr == 0) ? null : new MegaStringIntegerMap(cPtr, false);
  }

  public long getTestCategory(int productIndex) {
    return megaJNI.MegaPricing_getTestCategory(swigCPtr, this, productIndex);
  }

  public boolean hasDiscount(int productIndex) {
    return megaJNI.MegaPricing_hasDiscount(swigCPtr, this, productIndex);
  }

  public String getDiscountCode(int productIndex) {
    return megaJNI.MegaPricing_getDiscountCode(swigCPtr, this, productIndex);
  }

  public String getDiscountName(int productIndex) {
    return megaJNI.MegaPricing_getDiscountName(swigCPtr, this, productIndex);
  }

  public int getDiscountGroup(int productIndex) {
    return megaJNI.MegaPricing_getDiscountGroup(swigCPtr, this, productIndex);
  }

  public int getDiscountMonths(int productIndex) {
    return megaJNI.MegaPricing_getDiscountMonths(swigCPtr, this, productIndex);
  }

  public int getDiscountPercentage(int productIndex) {
    return megaJNI.MegaPricing_getDiscountPercentage(swigCPtr, this, productIndex);
  }

  public long getTrialDurationInDays(int productIndex) {
    return megaJNI.MegaPricing_getTrialDurationInDays(swigCPtr, this, productIndex);
  }

  public boolean hasMobileOffers(int productIndex) {
    return megaJNI.MegaPricing_hasMobileOffers(swigCPtr, this, productIndex);
  }

  public String getMobileOfferId(int productIndex) {
    return megaJNI.MegaPricing_getMobileOfferId(swigCPtr, this, productIndex);
  }

  public boolean hasMobileOfferUat(int productIndex) {
    return megaJNI.MegaPricing_hasMobileOfferUat(swigCPtr, this, productIndex);
  }

}
