/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaSyncStall {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaSyncStall(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaSyncStall obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaSyncStall obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaSyncStall(swigCPtr);
      }
      swigCPtr = 0;
    }
}

   MegaSyncStall copy() {
    long cPtr = megaJNI.MegaSyncStall_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaSyncStall(cPtr, true);
  }

  public MegaSyncStall.SyncStallReason reason() {
    return MegaSyncStall.SyncStallReason.swigToEnum(megaJNI.MegaSyncStall_reason(swigCPtr, this));
  }

  public String reasonDebugString() {
    return megaJNI.MegaSyncStall_reasonDebugString(swigCPtr, this);
  }

  public String path(boolean cloudSide, int index) {
    return megaJNI.MegaSyncStall_path(swigCPtr, this, cloudSide, index);
  }

  public long cloudNodeHandle(int index) {
    return megaJNI.MegaSyncStall_cloudNodeHandle(swigCPtr, this, index);
  }

  public long pathCount(boolean cloudSide) {
    return megaJNI.MegaSyncStall_pathCount(swigCPtr, this, cloudSide);
  }

  public int pathProblem(boolean cloudSide, int index) {
    return megaJNI.MegaSyncStall_pathProblem(swigCPtr, this, cloudSide, index);
  }

  public boolean couldSuggestIgnoreThisPath(boolean cloudSide, int index) {
    return megaJNI.MegaSyncStall_couldSuggestIgnoreThisPath(swigCPtr, this, cloudSide, index);
  }

  public boolean detectedCloudSide() {
    return megaJNI.MegaSyncStall_detectedCloudSide(swigCPtr, this);
  }

  public long getHash() {
    return megaJNI.MegaSyncStall_getHash(swigCPtr, this);
  }

  public final static class SyncStallReason {
    public final static MegaSyncStall.SyncStallReason NoReason = new MegaSyncStall.SyncStallReason("NoReason", 0);
    public final static MegaSyncStall.SyncStallReason FileIssue = new MegaSyncStall.SyncStallReason("FileIssue");
    public final static MegaSyncStall.SyncStallReason MoveOrRenameCannotOccur = new MegaSyncStall.SyncStallReason("MoveOrRenameCannotOccur");
    public final static MegaSyncStall.SyncStallReason DeleteOrMoveWaitingOnScanning = new MegaSyncStall.SyncStallReason("DeleteOrMoveWaitingOnScanning");
    public final static MegaSyncStall.SyncStallReason DeleteWaitingOnMoves = new MegaSyncStall.SyncStallReason("DeleteWaitingOnMoves");
    public final static MegaSyncStall.SyncStallReason UploadIssue = new MegaSyncStall.SyncStallReason("UploadIssue");
    public final static MegaSyncStall.SyncStallReason DownloadIssue = new MegaSyncStall.SyncStallReason("DownloadIssue");
    public final static MegaSyncStall.SyncStallReason CannotCreateFolder = new MegaSyncStall.SyncStallReason("CannotCreateFolder");
    public final static MegaSyncStall.SyncStallReason CannotPerformDeletion = new MegaSyncStall.SyncStallReason("CannotPerformDeletion");
    public final static MegaSyncStall.SyncStallReason SyncItemExceedsSupportedTreeDepth = new MegaSyncStall.SyncStallReason("SyncItemExceedsSupportedTreeDepth");
    public final static MegaSyncStall.SyncStallReason FolderMatchedAgainstFile = new MegaSyncStall.SyncStallReason("FolderMatchedAgainstFile");
    public final static MegaSyncStall.SyncStallReason LocalAndRemoteChangedSinceLastSyncedState_userMustChoose = new MegaSyncStall.SyncStallReason("LocalAndRemoteChangedSinceLastSyncedState_userMustChoose");
    public final static MegaSyncStall.SyncStallReason LocalAndRemotePreviouslyUnsyncedDiffer_userMustChoose = new MegaSyncStall.SyncStallReason("LocalAndRemotePreviouslyUnsyncedDiffer_userMustChoose");
    public final static MegaSyncStall.SyncStallReason NamesWouldClashWhenSynced = new MegaSyncStall.SyncStallReason("NamesWouldClashWhenSynced");
    public final static MegaSyncStall.SyncStallReason SyncStallReason_LastPlusOne = new MegaSyncStall.SyncStallReason("SyncStallReason_LastPlusOne");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static SyncStallReason swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + SyncStallReason.class + " with value " + swigValue);
    }

    private SyncStallReason(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private SyncStallReason(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private SyncStallReason(String swigName, SyncStallReason swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static SyncStallReason[] swigValues = { NoReason, FileIssue, MoveOrRenameCannotOccur, DeleteOrMoveWaitingOnScanning, DeleteWaitingOnMoves, UploadIssue, DownloadIssue, CannotCreateFolder, CannotPerformDeletion, SyncItemExceedsSupportedTreeDepth, FolderMatchedAgainstFile, LocalAndRemoteChangedSinceLastSyncedState_userMustChoose, LocalAndRemotePreviouslyUnsyncedDiffer_userMustChoose, NamesWouldClashWhenSynced, SyncStallReason_LastPlusOne };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

  public final static class SyncPathProblem {
    public final static MegaSyncStall.SyncPathProblem NoProblem = new MegaSyncStall.SyncPathProblem("NoProblem", 0);
    public final static MegaSyncStall.SyncPathProblem FileChangingFrequently = new MegaSyncStall.SyncPathProblem("FileChangingFrequently", 1);
    public final static MegaSyncStall.SyncPathProblem IgnoreRulesUnknown = new MegaSyncStall.SyncPathProblem("IgnoreRulesUnknown", 2);
    public final static MegaSyncStall.SyncPathProblem DetectedHardLink = new MegaSyncStall.SyncPathProblem("DetectedHardLink", 3);
    public final static MegaSyncStall.SyncPathProblem DetectedSymlink = new MegaSyncStall.SyncPathProblem("DetectedSymlink", 4);
    public final static MegaSyncStall.SyncPathProblem DetectedSpecialFile = new MegaSyncStall.SyncPathProblem("DetectedSpecialFile", 5);
    public final static MegaSyncStall.SyncPathProblem DifferentFileOrFolderIsAlreadyPresent = new MegaSyncStall.SyncPathProblem("DifferentFileOrFolderIsAlreadyPresent", 6);
    public final static MegaSyncStall.SyncPathProblem ParentFolderDoesNotExist = new MegaSyncStall.SyncPathProblem("ParentFolderDoesNotExist", 7);
    public final static MegaSyncStall.SyncPathProblem FilesystemErrorDuringOperation = new MegaSyncStall.SyncPathProblem("FilesystemErrorDuringOperation", 8);
    public final static MegaSyncStall.SyncPathProblem NameTooLongForFilesystem = new MegaSyncStall.SyncPathProblem("NameTooLongForFilesystem", 9);
    public final static MegaSyncStall.SyncPathProblem CannotFingerprintFile = new MegaSyncStall.SyncPathProblem("CannotFingerprintFile", 10);
    public final static MegaSyncStall.SyncPathProblem DestinationPathInUnresolvedArea = new MegaSyncStall.SyncPathProblem("DestinationPathInUnresolvedArea", 11);
    public final static MegaSyncStall.SyncPathProblem MACVerificationFailure = new MegaSyncStall.SyncPathProblem("MACVerificationFailure", 12);
    public final static MegaSyncStall.SyncPathProblem UnknownDownloadIssue = new MegaSyncStall.SyncPathProblem("UnknownDownloadIssue", 13);
    public final static MegaSyncStall.SyncPathProblem DeletedOrMovedByUser = new MegaSyncStall.SyncPathProblem("DeletedOrMovedByUser", 14);
    public final static MegaSyncStall.SyncPathProblem FileFolderDeletedByUser = new MegaSyncStall.SyncPathProblem("FileFolderDeletedByUser", 15);
    public final static MegaSyncStall.SyncPathProblem MoveToDebrisFolderFailed = new MegaSyncStall.SyncPathProblem("MoveToDebrisFolderFailed", 16);
    public final static MegaSyncStall.SyncPathProblem IgnoreFileMalformed = new MegaSyncStall.SyncPathProblem("IgnoreFileMalformed", 17);
    public final static MegaSyncStall.SyncPathProblem FilesystemErrorListingFolder = new MegaSyncStall.SyncPathProblem("FilesystemErrorListingFolder", 18);
    public final static MegaSyncStall.SyncPathProblem WaitingForScanningToComplete = new MegaSyncStall.SyncPathProblem("WaitingForScanningToComplete", 20);
    public final static MegaSyncStall.SyncPathProblem WaitingForAnotherMoveToComplete = new MegaSyncStall.SyncPathProblem("WaitingForAnotherMoveToComplete", 21);
    public final static MegaSyncStall.SyncPathProblem SourceWasMovedElsewhere = new MegaSyncStall.SyncPathProblem("SourceWasMovedElsewhere", 22);
    public final static MegaSyncStall.SyncPathProblem FilesystemCannotStoreThisName = new MegaSyncStall.SyncPathProblem("FilesystemCannotStoreThisName", 23);
    public final static MegaSyncStall.SyncPathProblem CloudNodeInvalidFingerprint = new MegaSyncStall.SyncPathProblem("CloudNodeInvalidFingerprint", 24);
    public final static MegaSyncStall.SyncPathProblem CloudNodeIsBlocked = new MegaSyncStall.SyncPathProblem("CloudNodeIsBlocked", 25);
    public final static MegaSyncStall.SyncPathProblem PutnodeDeferredByController = new MegaSyncStall.SyncPathProblem("PutnodeDeferredByController", 26);
    public final static MegaSyncStall.SyncPathProblem PutnodeCompletionDeferredByController = new MegaSyncStall.SyncPathProblem("PutnodeCompletionDeferredByController", 27);
    public final static MegaSyncStall.SyncPathProblem PutnodeCompletionPending = new MegaSyncStall.SyncPathProblem("PutnodeCompletionPending", 28);
    public final static MegaSyncStall.SyncPathProblem UploadDeferredByController = new MegaSyncStall.SyncPathProblem("UploadDeferredByController", 29);
    public final static MegaSyncStall.SyncPathProblem DetectedNestedMount = new MegaSyncStall.SyncPathProblem("DetectedNestedMount", 30);
    public final static MegaSyncStall.SyncPathProblem SyncPathProblem_LastPlusOne = new MegaSyncStall.SyncPathProblem("SyncPathProblem_LastPlusOne");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static SyncPathProblem swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + SyncPathProblem.class + " with value " + swigValue);
    }

    private SyncPathProblem(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private SyncPathProblem(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private SyncPathProblem(String swigName, SyncPathProblem swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static SyncPathProblem[] swigValues = { NoProblem, FileChangingFrequently, IgnoreRulesUnknown, DetectedHardLink, DetectedSymlink, DetectedSpecialFile, DifferentFileOrFolderIsAlreadyPresent, ParentFolderDoesNotExist, FilesystemErrorDuringOperation, NameTooLongForFilesystem, CannotFingerprintFile, DestinationPathInUnresolvedArea, MACVerificationFailure, UnknownDownloadIssue, DeletedOrMovedByUser, FileFolderDeletedByUser, MoveToDebrisFolderFailed, IgnoreFileMalformed, FilesystemErrorListingFolder, WaitingForScanningToComplete, WaitingForAnotherMoveToComplete, SourceWasMovedElsewhere, FilesystemCannotStoreThisName, CloudNodeInvalidFingerprint, CloudNodeIsBlocked, PutnodeDeferredByController, PutnodeCompletionDeferredByController, PutnodeCompletionPending, UploadDeferredByController, DetectedNestedMount, SyncPathProblem_LastPlusOne };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
