/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaRequest {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaRequest(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaRequest obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaRequest obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaRequest(swigCPtr);
      }
      swigCPtr = 0;
    }
}

   MegaRequest copy() {
    long cPtr = megaJNI.MegaRequest_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaRequest(cPtr, true);
  }

  public int getType() {
    return megaJNI.MegaRequest_getType(swigCPtr, this);
  }

  public String getRequestString() {
    return megaJNI.MegaRequest_getRequestString(swigCPtr, this);
  }

  public String toString() {
    return megaJNI.MegaRequest_toString(swigCPtr, this);
  }

  public long getNodeHandle() {
    return megaJNI.MegaRequest_getNodeHandle(swigCPtr, this);
  }

  public String getLink() {
    return megaJNI.MegaRequest_getLink(swigCPtr, this);
  }

  public long getParentHandle() {
    return megaJNI.MegaRequest_getParentHandle(swigCPtr, this);
  }

  public String getSessionKey() {
    return megaJNI.MegaRequest_getSessionKey(swigCPtr, this);
  }

  public String getName() {
    return megaJNI.MegaRequest_getName(swigCPtr, this);
  }

  public String getEmail() {
    return megaJNI.MegaRequest_getEmail(swigCPtr, this);
  }

  public String getPassword() {
    return megaJNI.MegaRequest_getPassword(swigCPtr, this);
  }

  public String getNewPassword() {
    return megaJNI.MegaRequest_getNewPassword(swigCPtr, this);
  }

  public String getPrivateKey() {
    return megaJNI.MegaRequest_getPrivateKey(swigCPtr, this);
  }

  public int getAccess() {
    return megaJNI.MegaRequest_getAccess(swigCPtr, this);
  }

  public String getFile() {
    return megaJNI.MegaRequest_getFile(swigCPtr, this);
  }

  public int getNumRetry() {
    return megaJNI.MegaRequest_getNumRetry(swigCPtr, this);
  }

  public MegaNode getPublicMegaNode() {
    long cPtr = megaJNI.MegaRequest_getPublicMegaNode(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaNode(cPtr, true);
  }

  public int getParamType() {
    return megaJNI.MegaRequest_getParamType(swigCPtr, this);
  }

  public String getText() {
    return megaJNI.MegaRequest_getText(swigCPtr, this);
  }

  public long getNumber() {
    return megaJNI.MegaRequest_getNumber(swigCPtr, this);
  }

  public boolean getFlag() {
    return megaJNI.MegaRequest_getFlag(swigCPtr, this);
  }

  public long getTransferredBytes() {
    return megaJNI.MegaRequest_getTransferredBytes(swigCPtr, this);
  }

  public long getTotalBytes() {
    return megaJNI.MegaRequest_getTotalBytes(swigCPtr, this);
  }

  public MegaAccountDetails getMegaAccountDetails() {
    long cPtr = megaJNI.MegaRequest_getMegaAccountDetails(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaAccountDetails(cPtr, true);
  }

  public MegaPricing getPricing() {
    long cPtr = megaJNI.MegaRequest_getPricing(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaPricing(cPtr, true);
  }

  public MegaCurrency getCurrency() {
    long cPtr = megaJNI.MegaRequest_getCurrency(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaCurrency(cPtr, true);
  }

  public MegaAchievementsDetails getMegaAchievementsDetails() {
    long cPtr = megaJNI.MegaRequest_getMegaAchievementsDetails(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaAchievementsDetails(cPtr, true);
  }

  public MegaTimeZoneDetails getMegaTimeZoneDetails() {
    long cPtr = megaJNI.MegaRequest_getMegaTimeZoneDetails(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaTimeZoneDetails(cPtr, true);
  }

  public int getTransferTag() {
    return megaJNI.MegaRequest_getTransferTag(swigCPtr, this);
  }

  public int getNumDetails() {
    return megaJNI.MegaRequest_getNumDetails(swigCPtr, this);
  }

  public int getTag() {
    return megaJNI.MegaRequest_getTag(swigCPtr, this);
  }

  public MegaTextChatPeerList getMegaTextChatPeerList() {
    long cPtr = megaJNI.MegaRequest_getMegaTextChatPeerList(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaTextChatPeerList(cPtr, false);
  }

  public MegaTextChatList getMegaTextChatList() {
    long cPtr = megaJNI.MegaRequest_getMegaTextChatList(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaTextChatList(cPtr, false);
  }

  public MegaStringMap getMegaStringMap() {
    long cPtr = megaJNI.MegaRequest_getMegaStringMap(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaStringMap(cPtr, false);
  }

  public MegaStringListMap getMegaStringListMap() {
    long cPtr = megaJNI.MegaRequest_getMegaStringListMap(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaStringListMap(cPtr, false);
  }

  public MegaStringTable getMegaStringTable() {
    long cPtr = megaJNI.MegaRequest_getMegaStringTable(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaStringTable(cPtr, false);
  }

  public MegaFolderInfo getMegaFolderInfo() {
    long cPtr = megaJNI.MegaRequest_getMegaFolderInfo(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaFolderInfo(cPtr, false);
  }

  public MegaPushNotificationSettings getMegaPushNotificationSettings() {
    long cPtr = megaJNI.MegaRequest_getMegaPushNotificationSettings(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaPushNotificationSettings(cPtr, false);
  }

  public MegaBackgroundMediaUpload getMegaBackgroundMediaUploadPtr() {
    long cPtr = megaJNI.MegaRequest_getMegaBackgroundMediaUploadPtr(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaBackgroundMediaUpload(cPtr, false);
  }

  public MegaBannerList getMegaBannerList() {
    long cPtr = megaJNI.MegaRequest_getMegaBannerList(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaBannerList(cPtr, false);
  }

  public MegaStringList getMegaStringList() {
    long cPtr = megaJNI.MegaRequest_getMegaStringList(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaStringList(cPtr, false);
  }

  public MegaStringIntegerMap getMegaStringIntegerMap() {
    long cPtr = megaJNI.MegaRequest_getMegaStringIntegerMap(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaStringIntegerMap(cPtr, false);
  }

  public MegaScheduledMeetingList getMegaScheduledMeetingList() {
    long cPtr = megaJNI.MegaRequest_getMegaScheduledMeetingList(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaScheduledMeetingList(cPtr, false);
  }

  public MegaHandleList getMegaHandleList() {
    long cPtr = megaJNI.MegaRequest_getMegaHandleList(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaHandleList(cPtr, false);
  }

  public MegaRecentActionBucketList getRecentActions() {
    long cPtr = megaJNI.MegaRequest_getRecentActions(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaRecentActionBucketList(cPtr, false);
  }

  public MegaIntegerList getMegaIntegerList() {
    long cPtr = megaJNI.MegaRequest_getMegaIntegerList(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaIntegerList(cPtr, false);
  }

  public MegaSet getMegaSet() {
    long cPtr = megaJNI.MegaRequest_getMegaSet(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaSet(cPtr, false);
  }

  public MegaSetElementList getMegaSetElementList() {
    long cPtr = megaJNI.MegaRequest_getMegaSetElementList(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaSetElementList(cPtr, false);
  }

  public MegaBackupInfoList getMegaBackupInfoList() {
    long cPtr = megaJNI.MegaRequest_getMegaBackupInfoList(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaBackupInfoList(cPtr, false);
  }

  public MegaSyncStallList getMegaSyncStallList() {
    long cPtr = megaJNI.MegaRequest_getMegaSyncStallList(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaSyncStallList(cPtr, false);
  }

  public MegaSyncStallMap getMegaSyncStallMap() {
    long cPtr = megaJNI.MegaRequest_getMegaSyncStallMap(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaSyncStallMap(cPtr, false);
  }

  public MegaVpnRegionList getMegaVpnRegionsDetailed() {
    long cPtr = megaJNI.MegaRequest_getMegaVpnRegionsDetailed(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaVpnRegionList(cPtr, false);
  }

  public MegaVpnCredentials getMegaVpnCredentials() {
    long cPtr = megaJNI.MegaRequest_getMegaVpnCredentials(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaVpnCredentials(cPtr, false);
  }

  public MegaNetworkConnectivityTestResults getMegaNetworkConnectivityTestResults() {
    long cPtr = megaJNI.MegaRequest_getMegaNetworkConnectivityTestResults(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaNetworkConnectivityTestResults(cPtr, false);
  }

  public MegaNotificationList getMegaNotifications() {
    long cPtr = megaJNI.MegaRequest_getMegaNotifications(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaNotificationList(cPtr, false);
  }

  public MegaNodeTree getMegaNodeTree() {
    long cPtr = megaJNI.MegaRequest_getMegaNodeTree(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaNodeTree(cPtr, false);
  }

  public MegaCancelSubscriptionReasonList getMegaCancelSubscriptionReasons() {
    long cPtr = megaJNI.MegaRequest_getMegaCancelSubscriptionReasons(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaCancelSubscriptionReasonList(cPtr, false);
  }

  public MegaDiscountCodeList getMegaDiscountCodeList() {
    long cPtr = megaJNI.MegaRequest_getMegaDiscountCodeList(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaDiscountCodeList(cPtr, false);
  }

  public MegaDiscountCodeInfo getMegaDiscountCodeInfo() {
    long cPtr = megaJNI.MegaRequest_getMegaDiscountCodeInfo(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaDiscountCodeInfo(cPtr, false);
  }

  public MegaRequest() {
    this(megaJNI.new_MegaRequest(), true);
  }

  public final static int TYPE_LOGIN = 0;
  public final static int TYPE_CREATE_FOLDER = 1;
  public final static int TYPE_MOVE = 2;
  public final static int TYPE_COPY = 3;
  public final static int TYPE_RENAME = 4;
  public final static int TYPE_REMOVE = 5;
  public final static int TYPE_SHARE = 6;
  public final static int TYPE_IMPORT_LINK = 7;
  public final static int TYPE_EXPORT = 8;
  public final static int TYPE_FETCH_NODES = 9;
  public final static int TYPE_ACCOUNT_DETAILS = 10;
  public final static int TYPE_CHANGE_PW = 11;
  public final static int TYPE_UPLOAD = 12;
  public final static int TYPE_LOGOUT = 13;
  public final static int TYPE_GET_PUBLIC_NODE = 14;
  public final static int TYPE_GET_ATTR_FILE = 15;
  public final static int TYPE_SET_ATTR_FILE = 16;
  public final static int TYPE_GET_ATTR_USER = 17;
  public final static int TYPE_SET_ATTR_USER = 18;
  public final static int TYPE_RETRY_PENDING_CONNECTIONS = 19;
  public final static int TYPE_REMOVE_CONTACT = 20;
  public final static int TYPE_CREATE_ACCOUNT = 21;
  public final static int TYPE_CONFIRM_ACCOUNT = 22;
  public final static int TYPE_QUERY_SIGNUP_LINK = 23;
  public final static int TYPE_ADD_SYNC = 24;
  public final static int TYPE_REMOVE_SYNC = 25;
  public final static int TYPE_COPY_SYNC_CONFIG = 28;
  public final static int TYPE_COPY_CACHED_STATUS = 29;
  public final static int TYPE_IMPORT_SYNC_CONFIGS = 30;
  public final static int TYPE_REMOVE_SYNCS = 31;
  public final static int TYPE_PAUSE_TRANSFERS = 32;
  public final static int TYPE_CANCEL_TRANSFER = 33;
  public final static int TYPE_CANCEL_TRANSFERS = 34;
  public final static int TYPE_DELETE = 35;
  public final static int TYPE_REPORT_EVENT = 36;
  public final static int TYPE_CANCEL_ATTR_FILE = 37;
  public final static int TYPE_GET_PRICING = 38;
  public final static int TYPE_GET_PAYMENT_ID = 39;
  public final static int TYPE_GET_USER_DATA = 40;
  public final static int TYPE_LOAD_BALANCING = 41;
  public final static int TYPE_KILL_SESSION = 42;
  public final static int TYPE_SUBMIT_PURCHASE_RECEIPT = 43;
  public final static int TYPE_CREDIT_CARD_STORE = 44;
  public final static int TYPE_UPGRADE_ACCOUNT = 45;
  public final static int TYPE_CREDIT_CARD_QUERY_SUBSCRIPTIONS = 46;
  public final static int TYPE_CREDIT_CARD_CANCEL_SUBSCRIPTIONS = 47;
  public final static int TYPE_GET_SESSION_TRANSFER_URL = 48;
  public final static int TYPE_GET_PAYMENT_METHODS = 49;
  public final static int TYPE_INVITE_CONTACT = 50;
  public final static int TYPE_REPLY_CONTACT_REQUEST = 51;
  public final static int TYPE_SUBMIT_FEEDBACK = 52;
  public final static int TYPE_SEND_EVENT = 53;
  public final static int TYPE_CLEAN_RUBBISH_BIN = 54;
  public final static int TYPE_SET_ATTR_NODE = 55;
  public final static int TYPE_CHAT_CREATE = 56;
  public final static int TYPE_CHAT_FETCH = 57;
  public final static int TYPE_CHAT_INVITE = 58;
  public final static int TYPE_CHAT_REMOVE = 59;
  public final static int TYPE_CHAT_URL = 60;
  public final static int TYPE_CHAT_GRANT_ACCESS = 61;
  public final static int TYPE_CHAT_REMOVE_ACCESS = 62;
  public final static int TYPE_USE_HTTPS_ONLY = 63;
  public final static int TYPE_SET_PROXY = 64;
  public final static int TYPE_GET_RECOVERY_LINK = 65;
  public final static int TYPE_QUERY_RECOVERY_LINK = 66;
  public final static int TYPE_CONFIRM_RECOVERY_LINK = 67;
  public final static int TYPE_GET_CANCEL_LINK = 68;
  public final static int TYPE_CONFIRM_CANCEL_LINK = 69;
  public final static int TYPE_GET_CHANGE_EMAIL_LINK = 70;
  public final static int TYPE_CONFIRM_CHANGE_EMAIL_LINK = 71;
  public final static int TYPE_CHAT_UPDATE_PERMISSIONS = 72;
  public final static int TYPE_CHAT_TRUNCATE = 73;
  public final static int TYPE_CHAT_SET_TITLE = 74;
  public final static int TYPE_SET_MAX_CONNECTIONS = 75;
  public final static int TYPE_PAUSE_TRANSFER = 76;
  public final static int TYPE_MOVE_TRANSFER = 77;
  public final static int TYPE_CHAT_PRESENCE_URL = 78;
  public final static int TYPE_REGISTER_PUSH_NOTIFICATION = 79;
  public final static int TYPE_GET_USER_EMAIL = 80;
  public final static int TYPE_APP_VERSION = 81;
  public final static int TYPE_GET_LOCAL_SSL_CERT = 82;
  public final static int TYPE_SEND_SIGNUP_LINK = 83;
  public final static int TYPE_QUERY_DNS = 84;
  public final static int TYPE_QUERY_GELB = 85;
  public final static int TYPE_CHAT_STATS = 86;
  public final static int TYPE_DOWNLOAD_FILE = 87;
  public final static int TYPE_QUERY_TRANSFER_QUOTA = 88;
  public final static int TYPE_PASSWORD_LINK = 89;
  public final static int TYPE_GET_ACHIEVEMENTS = 90;
  public final static int TYPE_RESTORE = 91;
  public final static int TYPE_REMOVE_VERSIONS = 92;
  public final static int TYPE_CHAT_ARCHIVE = 93;
  public final static int TYPE_WHY_AM_I_BLOCKED = 94;
  public final static int TYPE_CONTACT_LINK_CREATE = 95;
  public final static int TYPE_CONTACT_LINK_QUERY = 96;
  public final static int TYPE_CONTACT_LINK_DELETE = 97;
  public final static int TYPE_FOLDER_INFO = 98;
  public final static int TYPE_RICH_LINK = 99;
  public final static int TYPE_KEEP_ME_ALIVE = 100;
  public final static int TYPE_MULTI_FACTOR_AUTH_CHECK = 101;
  public final static int TYPE_MULTI_FACTOR_AUTH_GET = 102;
  public final static int TYPE_MULTI_FACTOR_AUTH_SET = 103;
  public final static int TYPE_ADD_SCHEDULED_COPY = 104;
  public final static int TYPE_REMOVE_SCHEDULED_COPY = 105;
  public final static int TYPE_TIMER = 106;
  public final static int TYPE_ABORT_CURRENT_SCHEDULED_COPY = 107;
  public final static int TYPE_GET_PSA = 108;
  public final static int TYPE_FETCH_TIMEZONE = 109;
  public final static int TYPE_USERALERT_ACKNOWLEDGE = 110;
  public final static int TYPE_CHAT_LINK_HANDLE = 111;
  public final static int TYPE_CHAT_LINK_URL = 112;
  public final static int TYPE_SET_PRIVATE_MODE = 113;
  public final static int TYPE_AUTOJOIN_PUBLIC_CHAT = 114;
  public final static int TYPE_CATCHUP = 115;
  public final static int TYPE_PUBLIC_LINK_INFORMATION = 116;
  public final static int TYPE_GET_BACKGROUND_UPLOAD_URL = 117;
  public final static int TYPE_COMPLETE_BACKGROUND_UPLOAD = 118;
  public final static int TYPE_GET_CLOUD_STORAGE_USED = 119;
  public final static int TYPE_SEND_SMS_VERIFICATIONCODE = 120;
  public final static int TYPE_CHECK_SMS_VERIFICATIONCODE = 121;
  public final static int TYPE_GET_COUNTRY_CALLING_CODES = 123;
  public final static int TYPE_VERIFY_CREDENTIALS = 124;
  public final static int TYPE_GET_MISC_FLAGS = 125;
  public final static int TYPE_RESEND_VERIFICATION_EMAIL = 126;
  public final static int TYPE_SUPPORT_TICKET = 127;
  public final static int TYPE_SET_RETENTION_TIME = 128;
  public final static int TYPE_RESET_SMS_VERIFIED_NUMBER = 129;
  public final static int TYPE_SEND_DEV_COMMAND = 130;
  public final static int TYPE_GET_BANNERS = 131;
  public final static int TYPE_DISMISS_BANNER = 132;
  public final static int TYPE_BACKUP_PUT = 133;
  public final static int TYPE_BACKUP_REMOVE = 134;
  public final static int TYPE_BACKUP_PUT_HEART_BEAT = 135;
  public final static int TYPE_FETCH_ADS = 136;
  public final static int TYPE_QUERY_ADS = 137;
  public final static int TYPE_GET_ATTR_NODE = 138;
  public final static int TYPE_LOAD_EXTERNAL_DRIVE_BACKUPS = 139;
  public final static int TYPE_CLOSE_EXTERNAL_DRIVE_BACKUPS = 140;
  public final static int TYPE_GET_DOWNLOAD_URLS = 141;
  public final static int TYPE_START_CHAT_CALL = 142;
  public final static int TYPE_JOIN_CHAT_CALL = 143;
  public final static int TYPE_END_CHAT_CALL = 144;
  public final static int TYPE_GET_FA_UPLOAD_URL = 145;
  public final static int TYPE_EXECUTE_ON_THREAD = 146;
  public final static int TYPE_SET_CHAT_OPTIONS = 147;
  public final static int TYPE_GET_RECENT_ACTIONS = 148;
  public final static int TYPE_CHECK_RECOVERY_KEY = 149;
  public final static int TYPE_SET_MY_BACKUPS = 150;
  public final static int TYPE_PUT_SET = 151;
  public final static int TYPE_REMOVE_SET = 152;
  public final static int TYPE_FETCH_SET = 153;
  public final static int TYPE_PUT_SET_ELEMENT = 154;
  public final static int TYPE_REMOVE_SET_ELEMENT = 155;
  public final static int TYPE_REMOVE_OLD_BACKUP_NODES = 156;
  public final static int TYPE_SET_SYNC_RUNSTATE = 157;
  public final static int TYPE_ADD_UPDATE_SCHEDULED_MEETING = 158;
  public final static int TYPE_DEL_SCHEDULED_MEETING = 159;
  public final static int TYPE_FETCH_SCHEDULED_MEETING = 160;
  public final static int TYPE_FETCH_SCHEDULED_MEETING_OCCURRENCES = 161;
  public final static int TYPE_OPEN_SHARE_DIALOG = 162;
  public final static int TYPE_UPGRADE_SECURITY = 163;
  public final static int TYPE_PUT_SET_ELEMENTS = 164;
  public final static int TYPE_REMOVE_SET_ELEMENTS = 165;
  public final static int TYPE_EXPORT_SET = 166;
  public final static int TYPE_GET_EXPORTED_SET_ELEMENT = 167;
  public final static int TYPE_GET_RECOMMENDED_PRO_PLAN = 168;
  public final static int TYPE_BACKUP_INFO = 169;
  public final static int TYPE_BACKUP_REMOVE_MD = 170;
  public final static int TYPE_AB_TEST_ACTIVE = 171;
  public final static int TYPE_GET_VPN_REGIONS = 172;
  public final static int TYPE_GET_VPN_CREDENTIALS = 173;
  public final static int TYPE_PUT_VPN_CREDENTIAL = 174;
  public final static int TYPE_DEL_VPN_CREDENTIAL = 175;
  public final static int TYPE_CHECK_VPN_CREDENTIAL = 176;
  public final static int TYPE_GET_SYNC_STALL_LIST = 177;
  public final static int TYPE_FETCH_CREDIT_CARD_INFO = 178;
  public final static int TYPE_MOVE_TO_DEBRIS = 179;
  public final static int TYPE_RING_INDIVIDUAL_IN_CALL = 180;
  public final static int TYPE_CREATE_NODE_TREE = 181;
  public final static int TYPE_CREATE_PASSWORD_MANAGER_BASE = 182;
  public final static int TYPE_CREATE_PASSWORD_NODE = 183;
  public final static int TYPE_UPDATE_PASSWORD_NODE = 184;
  public final static int TYPE_GET_NOTIFICATIONS = 185;
  public final static int TYPE_TAG_NODE = 186;
  public final static int TYPE_ADD_MOUNT = 187;
  public final static int TYPE_DISABLE_MOUNT = 188;
  public final static int TYPE_ENABLE_MOUNT = 189;
  public final static int TYPE_REMOVE_MOUNT = 190;
  public final static int TYPE_SET_MOUNT_FLAGS = 191;
  public final static int TYPE_DEL_ATTR_USER = 192;
  public final static int TYPE_BACKUP_PAUSE_MD = 194;
  public final static int TYPE_BACKUP_RESUME_MD = 195;
  public final static int TYPE_IMPORT_PASSWORDS_FROM_FILE = 196;
  public final static int TYPE_GET_ACTIVE_SURVEY_TRIGGER_ACTIONS = 197;
  public final static int TYPE_GET_SURVEY = 198;
  public final static int TYPE_ANSWER_SURVEY = 199;
  public final static int TYPE_CHANGE_SYNC_ROOT = 200;
  public final static int TYPE_GET_MY_IP = 201;
  public final static int TYPE_SET_SYNC_UPLOAD_THROTTLE_VALUES = 202;
  public final static int TYPE_GET_SYNC_UPLOAD_THROTTLE_VALUES = 203;
  public final static int TYPE_GET_SYNC_UPLOAD_THROTTLE_LIMITS = 204;
  public final static int TYPE_CHECK_SYNC_UPLOAD_THROTTLED_ELEMENTS = 205;
  public final static int TYPE_RUN_NETWORK_CONNECTIVITY_TEST = 206;
  public final static int TYPE_ADD_SYNC_PREVALIDATION = 207;
  public final static int TYPE_GET_MAX_CONNECTIONS = 208;
  public final static int TYPE_GET_SUBSCRIPTION_CANCELLATION_DETAILS = 209;
  public final static int TYPE_GET_DISCOUNT_CODE_INFORMATION = 210;
  public final static int TOTAL_OF_REQUEST_TYPES = 211;

}
