/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaSyncStallMap {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaSyncStallMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaSyncStallMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaSyncStallMap obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaSyncStallMap(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public MegaSyncStallMap() {
    this(megaJNI.new_MegaSyncStallMap(), true);
  }

   MegaSyncStallMap copy() {
    long cPtr = megaJNI.MegaSyncStallMap_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaSyncStallMap(cPtr, false);
  }

  public long size() {
    return megaJNI.MegaSyncStallMap_size(swigCPtr, this);
  }

  public long getHash() {
    return megaJNI.MegaSyncStallMap_getHash(swigCPtr, this);
  }

  public MegaSyncStallList get(long key) {
    long cPtr = megaJNI.MegaSyncStallMap_get(swigCPtr, this, key);
    return (cPtr == 0) ? null : new MegaSyncStallList(cPtr, false);
  }

  public MegaHandleList getKeys() {
    long cPtr = megaJNI.MegaSyncStallMap_getKeys(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaHandleList(cPtr, false);
  }

}
