/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaFuseInodeCacheFlags {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaFuseInodeCacheFlags(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaFuseInodeCacheFlags obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaFuseInodeCacheFlags obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaFuseInodeCacheFlags(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public long getCleanAgeThreshold() {
    return megaJNI.MegaFuseInodeCacheFlags_getCleanAgeThreshold(swigCPtr, this);
  }

  public long getCleanInterval() {
    return megaJNI.MegaFuseInodeCacheFlags_getCleanInterval(swigCPtr, this);
  }

  public long getCleanSizeThreshold() {
    return megaJNI.MegaFuseInodeCacheFlags_getCleanSizeThreshold(swigCPtr, this);
  }

  public long getMaxSize() {
    return megaJNI.MegaFuseInodeCacheFlags_getMaxSize(swigCPtr, this);
  }

  public void setCleanAgeThreshold(SWIGTYPE_p_std__size_t seconds) {
    megaJNI.MegaFuseInodeCacheFlags_setCleanAgeThreshold(swigCPtr, this, SWIGTYPE_p_std__size_t.getCPtr(seconds));
  }

  public void setCleanInterval(SWIGTYPE_p_std__size_t seconds) {
    megaJNI.MegaFuseInodeCacheFlags_setCleanInterval(swigCPtr, this, SWIGTYPE_p_std__size_t.getCPtr(seconds));
  }

  public void setCleanSizeThreshold(SWIGTYPE_p_std__size_t size) {
    megaJNI.MegaFuseInodeCacheFlags_setCleanSizeThreshold(swigCPtr, this, SWIGTYPE_p_std__size_t.getCPtr(size));
  }

  public void setMaxSize(SWIGTYPE_p_std__size_t size) {
    megaJNI.MegaFuseInodeCacheFlags_setMaxSize(swigCPtr, this, SWIGTYPE_p_std__size_t.getCPtr(size));
  }

}
