/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaTransfer {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaTransfer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaTransfer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaTransfer obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaTransfer(swigCPtr);
      }
      swigCPtr = 0;
    }
}

   MegaTransfer copy() {
    long cPtr = megaJNI.MegaTransfer_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaTransfer(cPtr, true);
  }

  public int getType() {
    return megaJNI.MegaTransfer_getType(swigCPtr, this);
  }

  public String getTransferString() {
    return megaJNI.MegaTransfer_getTransferString(swigCPtr, this);
  }

  public String toString() {
    return megaJNI.MegaTransfer_toString(swigCPtr, this);
  }

  public long getStartTime() {
    return megaJNI.MegaTransfer_getStartTime(swigCPtr, this);
  }

  public long getTransferredBytes() {
    return megaJNI.MegaTransfer_getTransferredBytes(swigCPtr, this);
  }

  public long getTotalBytes() {
    return megaJNI.MegaTransfer_getTotalBytes(swigCPtr, this);
  }

  public String getPath() {
    return megaJNI.MegaTransfer_getPath(swigCPtr, this);
  }

  public String getParentPath() {
    return megaJNI.MegaTransfer_getParentPath(swigCPtr, this);
  }

  public long getNodeHandle() {
    return megaJNI.MegaTransfer_getNodeHandle(swigCPtr, this);
  }

  public long getParentHandle() {
    return megaJNI.MegaTransfer_getParentHandle(swigCPtr, this);
  }

  public long getStartPos() {
    return megaJNI.MegaTransfer_getStartPos(swigCPtr, this);
  }

  public long getEndPos() {
    return megaJNI.MegaTransfer_getEndPos(swigCPtr, this);
  }

  public String getFileName() {
    return megaJNI.MegaTransfer_getFileName(swigCPtr, this);
  }

  public int getNumRetry() {
    return megaJNI.MegaTransfer_getNumRetry(swigCPtr, this);
  }

  public int getMaxRetries() {
    return megaJNI.MegaTransfer_getMaxRetries(swigCPtr, this);
  }

  public long getStage() {
    return megaJNI.MegaTransfer_getStage(swigCPtr, this);
  }

  public long getUniqueId() {
    return megaJNI.MegaTransfer_getUniqueId(swigCPtr, this);
  }

  public int getTag() {
    return megaJNI.MegaTransfer_getTag(swigCPtr, this);
  }

  public long getSpeed() {
    return megaJNI.MegaTransfer_getSpeed(swigCPtr, this);
  }

  public long getMeanSpeed() {
    return megaJNI.MegaTransfer_getMeanSpeed(swigCPtr, this);
  }

  public long getDeltaSize() {
    return megaJNI.MegaTransfer_getDeltaSize(swigCPtr, this);
  }

  public long getUpdateTime() {
    return megaJNI.MegaTransfer_getUpdateTime(swigCPtr, this);
  }

  public MegaNode getPublicMegaNode() {
    long cPtr = megaJNI.MegaTransfer_getPublicMegaNode(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaNode(cPtr, true);
  }

  public boolean isSyncTransfer() {
    return megaJNI.MegaTransfer_isSyncTransfer(swigCPtr, this);
  }

  public boolean isBackupTransfer() {
    return megaJNI.MegaTransfer_isBackupTransfer(swigCPtr, this);
  }

  public boolean isForeignOverquota() {
    return megaJNI.MegaTransfer_isForeignOverquota(swigCPtr, this);
  }

  public boolean isForceNewUpload() {
    return megaJNI.MegaTransfer_isForceNewUpload(swigCPtr, this);
  }

  public boolean isStreamingTransfer() {
    return megaJNI.MegaTransfer_isStreamingTransfer(swigCPtr, this);
  }

  public boolean isFinished() {
    return megaJNI.MegaTransfer_isFinished(swigCPtr, this);
  }

  public String getLastBytes() {
    return megaJNI.MegaTransfer_getLastBytes(swigCPtr, this);
  }

  public MegaError getLastErrorExtended() {
    long cPtr = megaJNI.MegaTransfer_getLastErrorExtended(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaError(cPtr, false);
  }

  public boolean isFolderTransfer() {
    return megaJNI.MegaTransfer_isFolderTransfer(swigCPtr, this);
  }

  public int getFolderTransferTag() {
    return megaJNI.MegaTransfer_getFolderTransferTag(swigCPtr, this);
  }

  public String getAppData() {
    return megaJNI.MegaTransfer_getAppData(swigCPtr, this);
  }

  public int getState() {
    return megaJNI.MegaTransfer_getState(swigCPtr, this);
  }

  public java.math.BigInteger getPriority() {
    return megaJNI.MegaTransfer_getPriority(swigCPtr, this);
  }

  public long getNotificationNumber() {
    return megaJNI.MegaTransfer_getNotificationNumber(swigCPtr, this);
  }

  public boolean getTargetOverride() {
    return megaJNI.MegaTransfer_getTargetOverride(swigCPtr, this);
  }

  public MegaCancelToken getCancelToken() {
    long cPtr = megaJNI.MegaTransfer_getCancelToken(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaCancelToken(cPtr, false);
  }

  public static String stageToString(long stage) {
    return megaJNI.MegaTransfer_stageToString(stage);
  }

  public MegaTransfer() {
    this(megaJNI.new_MegaTransfer(), true);
  }

  public final static int TYPE_DOWNLOAD = 0;
  public final static int TYPE_UPLOAD = 1;
  public final static int TYPE_LOCAL_TCP_DOWNLOAD = 2;
  public final static int TYPE_LOCAL_HTTP_DOWNLOAD = 2;

  public final static int STATE_NONE = 0;
  public final static int STATE_QUEUED = STATE_NONE + 1;
  public final static int STATE_ACTIVE = STATE_QUEUED + 1;
  public final static int STATE_PAUSED = STATE_ACTIVE + 1;
  public final static int STATE_RETRYING = STATE_PAUSED + 1;
  public final static int STATE_COMPLETING = STATE_RETRYING + 1;
  public final static int STATE_COMPLETED = STATE_COMPLETING + 1;
  public final static int STATE_CANCELLED = STATE_COMPLETED + 1;
  public final static int STATE_FAILED = STATE_CANCELLED + 1;

  public final static int MOVE_TYPE_UP = 1;
  public final static int MOVE_TYPE_DOWN = MOVE_TYPE_UP + 1;
  public final static int MOVE_TYPE_TOP = MOVE_TYPE_DOWN + 1;
  public final static int MOVE_TYPE_BOTTOM = MOVE_TYPE_TOP + 1;

  public final static int STAGE_NONE = 0;
  public final static int STAGE_SCAN = STAGE_NONE + 1;
  public final static int STAGE_CREATE_TREE = STAGE_SCAN + 1;
  public final static int STAGE_TRANSFERRING_FILES = STAGE_CREATE_TREE + 1;
  public final static int STAGE_MAX = STAGE_TRANSFERRING_FILES;

  public final static int COLLISION_CHECK_ASSUMESAME = 1;
  public final static int COLLISION_CHECK_ALWAYSERROR = 2;
  public final static int COLLISION_CHECK_FINGERPRINT = 3;
  public final static int COLLISION_CHECK_METAMAC = 4;
  public final static int COLLISION_CHECK_ASSUMEDIFFERENT = 5;

  public final static int COLLISION_RESOLUTION_OVERWRITE = 1;
  public final static int COLLISION_RESOLUTION_NEW_WITH_N = 2;
  public final static int COLLISION_RESOLUTION_EXISTING_TO_OLDN = 3;

}
