/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaCancelToken {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaCancelToken(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaCancelToken obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaCancelToken obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaCancelToken(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public static MegaCancelToken createInstance() {
    long cPtr = megaJNI.MegaCancelToken_createInstance();
    return (cPtr == 0) ? null : new MegaCancelToken(cPtr, false);
  }

  public void cancel() {
    megaJNI.MegaCancelToken_cancel(swigCPtr, this);
  }

  public boolean isCancelled() {
    return megaJNI.MegaCancelToken_isCancelled(swigCPtr, this);
  }

}
