/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaBanner {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaBanner(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaBanner obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaBanner obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaBanner(swigCPtr);
      }
      swigCPtr = 0;
    }
}

   MegaBanner copy() {
    long cPtr = megaJNI.MegaBanner_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaBanner(cPtr, false);
  }

  public int getId() {
    return megaJNI.MegaBanner_getId(swigCPtr, this);
  }

  public String getTitle() {
    return megaJNI.MegaBanner_getTitle(swigCPtr, this);
  }

  public String getDescription() {
    return megaJNI.MegaBanner_getDescription(swigCPtr, this);
  }

  public String getImage() {
    return megaJNI.MegaBanner_getImage(swigCPtr, this);
  }

  public String getUrl() {
    return megaJNI.MegaBanner_getUrl(swigCPtr, this);
  }

  public String getBackgroundImage() {
    return megaJNI.MegaBanner_getBackgroundImage(swigCPtr, this);
  }

  public String getImageLocation() {
    return megaJNI.MegaBanner_getImageLocation(swigCPtr, this);
  }

  public int getVariant() {
    return megaJNI.MegaBanner_getVariant(swigCPtr, this);
  }

  public String getButton() {
    return megaJNI.MegaBanner_getButton(swigCPtr, this);
  }

}
