/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaScheduledFlags {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaScheduledFlags(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaScheduledFlags obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaScheduledFlags obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaScheduledFlags(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public static MegaScheduledFlags createInstance() {
    long cPtr = megaJNI.MegaScheduledFlags_createInstance();
    return (cPtr == 0) ? null : new MegaScheduledFlags(cPtr, false);
  }

  public void importFlagsValue(long arg0) {
    megaJNI.MegaScheduledFlags_importFlagsValue(swigCPtr, this, arg0);
  }

   MegaScheduledFlags copy() {
    long cPtr = megaJNI.MegaScheduledFlags_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaScheduledFlags(cPtr, false);
  }

  public void reset() {
    megaJNI.MegaScheduledFlags_reset(swigCPtr, this);
  }

  public long getNumericValue() {
    return megaJNI.MegaScheduledFlags_getNumericValue(swigCPtr, this);
  }

  public boolean isEmpty() {
    return megaJNI.MegaScheduledFlags_isEmpty(swigCPtr, this);
  }

  public MegaScheduledFlags() {
    this(megaJNI.new_MegaScheduledFlags(), true);
  }

  public final static int FLAGS_SEND_EMAILS = 0;
  public final static int FLAGS_SIZE = 1;

}
