/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaVpnRegion {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaVpnRegion(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaVpnRegion obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaVpnRegion obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaVpnRegion(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public String getName() {
    return megaJNI.MegaVpnRegion_getName(swigCPtr, this);
  }

  public String getCountryCode() {
    return megaJNI.MegaVpnRegion_getCountryCode(swigCPtr, this);
  }

  public String getCountryName() {
    return megaJNI.MegaVpnRegion_getCountryName(swigCPtr, this);
  }

  public String getRegionName() {
    return megaJNI.MegaVpnRegion_getRegionName(swigCPtr, this);
  }

  public String getTownName() {
    return megaJNI.MegaVpnRegion_getTownName(swigCPtr, this);
  }

  public MegaVpnClusterMap getClusters() {
    long cPtr = megaJNI.MegaVpnRegion_getClusters(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaVpnClusterMap(cPtr, false);
  }

   MegaVpnRegion copy() {
    long cPtr = megaJNI.MegaVpnRegion_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaVpnRegion(cPtr, false);
  }

}
