/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaVpnCredentials {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaVpnCredentials(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaVpnCredentials obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaVpnCredentials obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaVpnCredentials(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public MegaIntegerList getSlotIDs() {
    long cPtr = megaJNI.MegaVpnCredentials_getSlotIDs(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaIntegerList(cPtr, false);
  }

  public MegaStringList getVpnRegions() {
    long cPtr = megaJNI.MegaVpnCredentials_getVpnRegions(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaStringList(cPtr, false);
  }

  public MegaVpnRegionList getVpnRegionsDetailed() {
    long cPtr = megaJNI.MegaVpnCredentials_getVpnRegionsDetailed(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaVpnRegionList(cPtr, false);
  }

  public String getIPv4(int slotID) {
    return megaJNI.MegaVpnCredentials_getIPv4(swigCPtr, this, slotID);
  }

  public String getIPv6(int slotID) {
    return megaJNI.MegaVpnCredentials_getIPv6(swigCPtr, this, slotID);
  }

  public String getDeviceID(int slotID) {
    return megaJNI.MegaVpnCredentials_getDeviceID(swigCPtr, this, slotID);
  }

  public int getClusterID(int slotID) {
    return megaJNI.MegaVpnCredentials_getClusterID(swigCPtr, this, slotID);
  }

  public String getClusterPublicKey(int clusterID) {
    return megaJNI.MegaVpnCredentials_getClusterPublicKey(swigCPtr, this, clusterID);
  }

   MegaVpnCredentials copy() {
    long cPtr = megaJNI.MegaVpnCredentials_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaVpnCredentials(cPtr, false);
  }

}
