/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaUserAlert {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaUserAlert(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaUserAlert obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaUserAlert obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaUserAlert(swigCPtr);
      }
      swigCPtr = 0;
    }
}

   MegaUserAlert copy() {
    long cPtr = megaJNI.MegaUserAlert_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaUserAlert(cPtr, true);
  }

  public long getId() {
    return megaJNI.MegaUserAlert_getId(swigCPtr, this);
  }

  public boolean getSeen() {
    return megaJNI.MegaUserAlert_getSeen(swigCPtr, this);
  }

  public boolean getRelevant() {
    return megaJNI.MegaUserAlert_getRelevant(swigCPtr, this);
  }

  public int getType() {
    return megaJNI.MegaUserAlert_getType(swigCPtr, this);
  }

  public String getTypeString() {
    return megaJNI.MegaUserAlert_getTypeString(swigCPtr, this);
  }

  public long getUserHandle() {
    return megaJNI.MegaUserAlert_getUserHandle(swigCPtr, this);
  }

  public long getNodeHandle() {
    return megaJNI.MegaUserAlert_getNodeHandle(swigCPtr, this);
  }

  public long getPcrHandle() {
    return megaJNI.MegaUserAlert_getPcrHandle(swigCPtr, this);
  }

  public String getEmail() {
    return megaJNI.MegaUserAlert_getEmail(swigCPtr, this);
  }

  public String getPath() {
    return megaJNI.MegaUserAlert_getPath(swigCPtr, this);
  }

  public String getName() {
    return megaJNI.MegaUserAlert_getName(swigCPtr, this);
  }

  public String getHeading() {
    return megaJNI.MegaUserAlert_getHeading(swigCPtr, this);
  }

  public String getTitle() {
    return megaJNI.MegaUserAlert_getTitle(swigCPtr, this);
  }

  public long getNumber(long index) {
    return megaJNI.MegaUserAlert_getNumber(swigCPtr, this, index);
  }

  public long getTimestamp(long index) {
    return megaJNI.MegaUserAlert_getTimestamp(swigCPtr, this, index);
  }

  public long getHandle(long index) {
    return megaJNI.MegaUserAlert_getHandle(swigCPtr, this, index);
  }

  public String getString(long index) {
    return megaJNI.MegaUserAlert_getString(swigCPtr, this, index);
  }

  public long getSchedId() {
    return megaJNI.MegaUserAlert_getSchedId(swigCPtr, this);
  }

  public boolean hasSchedMeetingChanged(long arg0) {
    return megaJNI.MegaUserAlert_hasSchedMeetingChanged(swigCPtr, this, arg0);
  }

  public MegaStringList getUpdatedTitle() {
    long cPtr = megaJNI.MegaUserAlert_getUpdatedTitle(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaStringList(cPtr, false);
  }

  public MegaStringList getUpdatedTimeZone() {
    long cPtr = megaJNI.MegaUserAlert_getUpdatedTimeZone(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaStringList(cPtr, false);
  }

  public MegaIntegerList getUpdatedStartDate() {
    long cPtr = megaJNI.MegaUserAlert_getUpdatedStartDate(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaIntegerList(cPtr, false);
  }

  public MegaIntegerList getUpdatedEndDate() {
    long cPtr = megaJNI.MegaUserAlert_getUpdatedEndDate(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaIntegerList(cPtr, false);
  }

  public boolean isOwnChange() {
    return megaJNI.MegaUserAlert_isOwnChange(swigCPtr, this);
  }

  public boolean isRemoved() {
    return megaJNI.MegaUserAlert_isRemoved(swigCPtr, this);
  }

  public MegaUserAlert() {
    this(megaJNI.new_MegaUserAlert(), true);
  }

  public final static int TYPE_INCOMINGPENDINGCONTACT_REQUEST = 0;
  public final static int TYPE_INCOMINGPENDINGCONTACT_CANCELLED = TYPE_INCOMINGPENDINGCONTACT_REQUEST + 1;
  public final static int TYPE_INCOMINGPENDINGCONTACT_REMINDER = TYPE_INCOMINGPENDINGCONTACT_CANCELLED + 1;
  public final static int TYPE_CONTACTCHANGE_DELETEDYOU = TYPE_INCOMINGPENDINGCONTACT_REMINDER + 1;
  public final static int TYPE_CONTACTCHANGE_CONTACTESTABLISHED = TYPE_CONTACTCHANGE_DELETEDYOU + 1;
  public final static int TYPE_CONTACTCHANGE_ACCOUNTDELETED = TYPE_CONTACTCHANGE_CONTACTESTABLISHED + 1;
  public final static int TYPE_CONTACTCHANGE_BLOCKEDYOU = TYPE_CONTACTCHANGE_ACCOUNTDELETED + 1;
  public final static int TYPE_UPDATEDPENDINGCONTACTINCOMING_IGNORED = TYPE_CONTACTCHANGE_BLOCKEDYOU + 1;
  public final static int TYPE_UPDATEDPENDINGCONTACTINCOMING_ACCEPTED = TYPE_UPDATEDPENDINGCONTACTINCOMING_IGNORED + 1;
  public final static int TYPE_UPDATEDPENDINGCONTACTINCOMING_DENIED = TYPE_UPDATEDPENDINGCONTACTINCOMING_ACCEPTED + 1;
  public final static int TYPE_UPDATEDPENDINGCONTACTOUTGOING_ACCEPTED = TYPE_UPDATEDPENDINGCONTACTINCOMING_DENIED + 1;
  public final static int TYPE_UPDATEDPENDINGCONTACTOUTGOING_DENIED = TYPE_UPDATEDPENDINGCONTACTOUTGOING_ACCEPTED + 1;
  public final static int TYPE_NEWSHARE = TYPE_UPDATEDPENDINGCONTACTOUTGOING_DENIED + 1;
  public final static int TYPE_DELETEDSHARE = TYPE_NEWSHARE + 1;
  public final static int TYPE_NEWSHAREDNODES = TYPE_DELETEDSHARE + 1;
  public final static int TYPE_REMOVEDSHAREDNODES = TYPE_NEWSHAREDNODES + 1;
  public final static int TYPE_UPDATEDSHAREDNODES = TYPE_REMOVEDSHAREDNODES + 1;
  public final static int TYPE_PAYMENT_SUCCEEDED = TYPE_UPDATEDSHAREDNODES + 1;
  public final static int TYPE_PAYMENT_FAILED = TYPE_PAYMENT_SUCCEEDED + 1;
  public final static int TYPE_PAYMENTREMINDER = TYPE_PAYMENT_FAILED + 1;
  public final static int TYPE_TAKEDOWN = TYPE_PAYMENTREMINDER + 1;
  public final static int TYPE_TAKEDOWN_REINSTATED = TYPE_TAKEDOWN + 1;
  public final static int TYPE_SCHEDULEDMEETING_NEW = TYPE_TAKEDOWN_REINSTATED + 1;
  public final static int TYPE_SCHEDULEDMEETING_DELETED = TYPE_SCHEDULEDMEETING_NEW + 1;
  public final static int TYPE_SCHEDULEDMEETING_UPDATED = TYPE_SCHEDULEDMEETING_DELETED + 1;
  public final static int TYPE_SET_TAKEDOWN = TYPE_SCHEDULEDMEETING_UPDATED + 1;
  public final static int TYPE_SET_TAKEDOWN_REINSTATED = TYPE_SET_TAKEDOWN + 1;
  public final static int TOTAL_OF_ALERT_TYPES = TYPE_SET_TAKEDOWN_REINSTATED + 1;

  public final static int SM_CHANGE_TYPE_TITLE = 1;
  public final static int SM_CHANGE_TYPE_DESCRIPTION = 2;
  public final static int SM_CHANGE_TYPE_CANCELLED = 4;
  public final static int SM_CHANGE_TYPE_TIMEZONE = 8;
  public final static int SM_CHANGE_TYPE_STARTDATE = 16;
  public final static int SM_CHANGE_TYPE_ENDDATE = 32;
  public final static int SM_CHANGE_TYPE_RULES = 64;

}
