/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaAccountPurchase {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaAccountPurchase(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaAccountPurchase obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaAccountPurchase obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaAccountPurchase(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public long getTimestamp() {
    return megaJNI.MegaAccountPurchase_getTimestamp(swigCPtr, this);
  }

  public String getHandle() {
    return megaJNI.MegaAccountPurchase_getHandle(swigCPtr, this);
  }

  public String getCurrency() {
    return megaJNI.MegaAccountPurchase_getCurrency(swigCPtr, this);
  }

  public double getAmount() {
    return megaJNI.MegaAccountPurchase_getAmount(swigCPtr, this);
  }

  public int getMethod() {
    return megaJNI.MegaAccountPurchase_getMethod(swigCPtr, this);
  }

  public MegaAccountPurchase() {
    this(megaJNI.new_MegaAccountPurchase(), true);
  }

}
