/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaError {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaError(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaError obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaError obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaError(swigCPtr);
      }
      swigCPtr = 0;
    }
}

   MegaError copy() {
    long cPtr = megaJNI.MegaError_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaError(cPtr, true);
  }

  public int getErrorCode() {
    return megaJNI.MegaError_getErrorCode(swigCPtr, this);
  }

  public int getMountResult() {
    return megaJNI.MegaError_getMountResult(swigCPtr, this);
  }

  public int getSyncError() {
    return megaJNI.MegaError_getSyncError(swigCPtr, this);
  }

  public long getValue() {
    return megaJNI.MegaError_getValue(swigCPtr, this);
  }

  public boolean hasExtraInfo() {
    return megaJNI.MegaError_hasExtraInfo(swigCPtr, this);
  }

  public long getUserStatus() {
    return megaJNI.MegaError_getUserStatus(swigCPtr, this);
  }

  public long getLinkStatus() {
    return megaJNI.MegaError_getLinkStatus(swigCPtr, this);
  }

  public String getErrorString() {
    return megaJNI.MegaError_getErrorString__SWIG_0(swigCPtr, this);
  }

  public String toString() {
    return megaJNI.MegaError_toString(swigCPtr, this);
  }

  public static String getErrorString(int errorCode) {
    return megaJNI.MegaError_getErrorString__SWIG_1(errorCode);
  }

  public static String getErrorString(int errorCode, MegaError.ErrorContexts context) {
    return megaJNI.MegaError_getErrorString__SWIG_2(errorCode, context.swigValue());
  }

  public final static int API_OK = 0;
  public final static int API_EINTERNAL = -1;
  public final static int API_EARGS = -2;
  public final static int API_EAGAIN = -3;
  public final static int API_ERATELIMIT = -4;
  public final static int API_EFAILED = -5;
  public final static int API_ETOOMANY = -6;
  public final static int API_ERANGE = -7;
  public final static int API_EEXPIRED = -8;
  public final static int API_ENOENT = -9;
  public final static int API_ECIRCULAR = -10;
  public final static int API_EACCESS = -11;
  public final static int API_EEXIST = -12;
  public final static int API_EINCOMPLETE = -13;
  public final static int API_EKEY = -14;
  public final static int API_ESID = -15;
  public final static int API_EBLOCKED = -16;
  public final static int API_EOVERQUOTA = -17;
  public final static int API_ETEMPUNAVAIL = -18;
  public final static int API_ETOOMANYCONNECTIONS = -19;
  public final static int API_EWRITE = -20;
  public final static int API_EREAD = -21;
  public final static int API_EAPPKEY = -22;
  public final static int API_ESSL = -23;
  public final static int API_EGOINGOVERQUOTA = -24;
  public final static int API_EROLLEDBACK = -25;
  public final static int API_EMFAREQUIRED = -26;
  public final static int API_EMASTERONLY = -27;
  public final static int API_EBUSINESSPASTDUE = -28;
  public final static int API_EPAYWALL = -29;
  public final static int API_ESUBUSERKEYMISSING = -30;
  public final static int PAYMENT_ECARD = -101;
  public final static int PAYMENT_EBILLING = -102;
  public final static int PAYMENT_EFRAUD = -103;
  public final static int PAYMENT_ETOOMANY = -104;
  public final static int PAYMENT_EBALANCE = -105;
  public final static int PAYMENT_EGENERIC = -106;
  public final static int LOCAL_ENOSPC = -1000;
  public final static int LOCAL_ETIMEOUT = -1001;
  public final static int LOCAL_ENETWORK = -1003;

  public final static class ErrorContexts {
    public final static MegaError.ErrorContexts API_EC_DEFAULT = new MegaError.ErrorContexts("API_EC_DEFAULT", 0);
    public final static MegaError.ErrorContexts API_EC_DOWNLOAD = new MegaError.ErrorContexts("API_EC_DOWNLOAD", 1);
    public final static MegaError.ErrorContexts API_EC_IMPORT = new MegaError.ErrorContexts("API_EC_IMPORT", 2);
    public final static MegaError.ErrorContexts API_EC_UPLOAD = new MegaError.ErrorContexts("API_EC_UPLOAD", 3);

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static ErrorContexts swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + ErrorContexts.class + " with value " + swigValue);
    }

    private ErrorContexts(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private ErrorContexts(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private ErrorContexts(String swigName, ErrorContexts swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static ErrorContexts[] swigValues = { API_EC_DEFAULT, API_EC_DOWNLOAD, API_EC_IMPORT, API_EC_UPLOAD };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

  public final static class UserErrorCode {
    public final static MegaError.UserErrorCode USER_ETD_UNKNOWN = new MegaError.UserErrorCode("USER_ETD_UNKNOWN", -1);
    public final static MegaError.UserErrorCode USER_ENABLED = new MegaError.UserErrorCode("USER_ENABLED", 0);
    public final static MegaError.UserErrorCode USER_PENDINGCONFIRMATION = new MegaError.UserErrorCode("USER_PENDINGCONFIRMATION", 1);
    public final static MegaError.UserErrorCode USER_SUSPENDED_GENERIC = new MegaError.UserErrorCode("USER_SUSPENDED_GENERIC", 2);
    public final static MegaError.UserErrorCode USER_SUSPENDED_PAYMENT = new MegaError.UserErrorCode("USER_SUSPENDED_PAYMENT", 3);
    public final static MegaError.UserErrorCode USER_COPYRIGHT_SUSPENSION = new MegaError.UserErrorCode("USER_COPYRIGHT_SUSPENSION", 4);
    public final static MegaError.UserErrorCode USER_SUSPENDED_ADMIN_FULLDISABLE = new MegaError.UserErrorCode("USER_SUSPENDED_ADMIN_FULLDISABLE", 5);
    public final static MegaError.UserErrorCode USER_SUSPENDED_ADMIN_PARTIALDISABLE = new MegaError.UserErrorCode("USER_SUSPENDED_ADMIN_PARTIALDISABLE", 6);
    public final static MegaError.UserErrorCode USER_ETD_SUSPENSION = new MegaError.UserErrorCode("USER_ETD_SUSPENSION", 7);
    public final static MegaError.UserErrorCode USER_SUSPENDED_SMSVERIFICATIONREQUIRED = new MegaError.UserErrorCode("USER_SUSPENDED_SMSVERIFICATIONREQUIRED", 8);
    public final static MegaError.UserErrorCode USER_SUSPENDED_EMAILVERIFICATIONREQUIRED = new MegaError.UserErrorCode("USER_SUSPENDED_EMAILVERIFICATIONREQUIRED", 9);
    public final static MegaError.UserErrorCode USER_SUBACCOUNT_PENDINGCONFIRMATION = new MegaError.UserErrorCode("USER_SUBACCOUNT_PENDINGCONFIRMATION", 10);
    public final static MegaError.UserErrorCode USER_SUBACCOUNT_DISABLED = new MegaError.UserErrorCode("USER_SUBACCOUNT_DISABLED", 11);
    public final static MegaError.UserErrorCode USER_SUBACCOUNT_DELETED = new MegaError.UserErrorCode("USER_SUBACCOUNT_DELETED", 12);
    public final static MegaError.UserErrorCode USER_BUSINESSACCOUNT = new MegaError.UserErrorCode("USER_BUSINESSACCOUNT", 20);
    public final static MegaError.UserErrorCode USER_SUSPENDED_PASSWORD_CHANGE_REQUIRED = new MegaError.UserErrorCode("USER_SUSPENDED_PASSWORD_CHANGE_REQUIRED", 21);
    public final static MegaError.UserErrorCode USER_EPHEMERAL_RESELLER_USER = new MegaError.UserErrorCode("USER_EPHEMERAL_RESELLER_USER", 22);
    public final static MegaError.UserErrorCode USER_SUSPENDED_NOUSER = new MegaError.UserErrorCode("USER_SUSPENDED_NOUSER", 99);

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static UserErrorCode swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + UserErrorCode.class + " with value " + swigValue);
    }

    private UserErrorCode(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private UserErrorCode(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private UserErrorCode(String swigName, UserErrorCode swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static UserErrorCode[] swigValues = { USER_ETD_UNKNOWN, USER_ENABLED, USER_PENDINGCONFIRMATION, USER_SUSPENDED_GENERIC, USER_SUSPENDED_PAYMENT, USER_COPYRIGHT_SUSPENSION, USER_SUSPENDED_ADMIN_FULLDISABLE, USER_SUSPENDED_ADMIN_PARTIALDISABLE, USER_ETD_SUSPENSION, USER_SUSPENDED_SMSVERIFICATIONREQUIRED, USER_SUSPENDED_EMAILVERIFICATIONREQUIRED, USER_SUBACCOUNT_PENDINGCONFIRMATION, USER_SUBACCOUNT_DISABLED, USER_SUBACCOUNT_DELETED, USER_BUSINESSACCOUNT, USER_SUSPENDED_PASSWORD_CHANGE_REQUIRED, USER_EPHEMERAL_RESELLER_USER, USER_SUSPENDED_NOUSER };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

  public final static class LinkErrorCode {
    public final static MegaError.LinkErrorCode LINK_UNKNOWN = new MegaError.LinkErrorCode("LINK_UNKNOWN", -1);
    public final static MegaError.LinkErrorCode LINK_UNDELETED = new MegaError.LinkErrorCode("LINK_UNDELETED", 0);
    public final static MegaError.LinkErrorCode LINK_DELETED_DOWN = new MegaError.LinkErrorCode("LINK_DELETED_DOWN", 1);
    public final static MegaError.LinkErrorCode LINK_DOWN_ETD = new MegaError.LinkErrorCode("LINK_DOWN_ETD", 2);

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static LinkErrorCode swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + LinkErrorCode.class + " with value " + swigValue);
    }

    private LinkErrorCode(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private LinkErrorCode(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private LinkErrorCode(String swigName, LinkErrorCode swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static LinkErrorCode[] swigValues = { LINK_UNKNOWN, LINK_UNDELETED, LINK_DELETED_DOWN, LINK_DOWN_ETD };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
