/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaBackupInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaBackupInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaBackupInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaBackupInfo obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaBackupInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public long id() {
    return megaJNI.MegaBackupInfo_id(swigCPtr, this);
  }

  public int type() {
    return megaJNI.MegaBackupInfo_type(swigCPtr, this);
  }

  public long root() {
    return megaJNI.MegaBackupInfo_root(swigCPtr, this);
  }

  public String localFolder() {
    return megaJNI.MegaBackupInfo_localFolder(swigCPtr, this);
  }

  public String deviceId() {
    return megaJNI.MegaBackupInfo_deviceId(swigCPtr, this);
  }

  public String deviceUserAgent() {
    return megaJNI.MegaBackupInfo_deviceUserAgent(swigCPtr, this);
  }

  public int state() {
    return megaJNI.MegaBackupInfo_state(swigCPtr, this);
  }

  public int substate() {
    return megaJNI.MegaBackupInfo_substate(swigCPtr, this);
  }

  public String extra() {
    return megaJNI.MegaBackupInfo_extra(swigCPtr, this);
  }

  public String name() {
    return megaJNI.MegaBackupInfo_name(swigCPtr, this);
  }

  public long ts() {
    return megaJNI.MegaBackupInfo_ts(swigCPtr, this);
  }

  public int status() {
    return megaJNI.MegaBackupInfo_status(swigCPtr, this);
  }

  public int progress() {
    return megaJNI.MegaBackupInfo_progress(swigCPtr, this);
  }

  public int uploads() {
    return megaJNI.MegaBackupInfo_uploads(swigCPtr, this);
  }

  public int downloads() {
    return megaJNI.MegaBackupInfo_downloads(swigCPtr, this);
  }

  public long activityTs() {
    return megaJNI.MegaBackupInfo_activityTs(swigCPtr, this);
  }

  public long lastSync() {
    return megaJNI.MegaBackupInfo_lastSync(swigCPtr, this);
  }

   MegaBackupInfo copy() {
    long cPtr = megaJNI.MegaBackupInfo_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaBackupInfo(cPtr, false);
  }

  public MegaBackupInfo() {
    this(megaJNI.new_MegaBackupInfo(), true);
  }

  public final static int BACKUP_STATE_NOT_INITIALIZED = 0;
  public final static int BACKUP_STATE_ACTIVE = 1;
  public final static int BACKUP_STATE_FAILED = 2;
  public final static int BACKUP_STATE_TEMPORARY_DISABLED = 3;
  public final static int BACKUP_STATE_DISABLED = 4;
  public final static int BACKUP_STATE_PAUSE_UP = 5;
  public final static int BACKUP_STATE_PAUSE_DOWN = 6;
  public final static int BACKUP_STATE_PAUSE_FULL = 7;
  public final static int BACKUP_STATE_DELETED = 8;

  public final static int BACKUP_STATUS_NOT_INITIALIZED = 0;
  public final static int BACKUP_STATUS_UPTODATE = 1;
  public final static int BACKUP_STATUS_SYNCING = 2;
  public final static int BACKUP_STATUS_PENDING = 3;
  public final static int BACKUP_STATUS_INACTIVE = 4;
  public final static int BACKUP_STATUS_UNKNOWN = 5;
  public final static int BACKUP_STATUS_STALLED = 6;

}
