/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaStringList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaStringList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaStringList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaStringList obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaStringList(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public static MegaStringList createInstance() {
    long cPtr = megaJNI.MegaStringList_createInstance();
    return (cPtr == 0) ? null : new MegaStringList(cPtr, false);
  }

   MegaStringList copy() {
    long cPtr = megaJNI.MegaStringList_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaStringList(cPtr, true);
  }

  public String get(int i) {
    return megaJNI.MegaStringList_get(swigCPtr, this, i);
  }

  public int size() {
    return megaJNI.MegaStringList_size(swigCPtr, this);
  }

  public void add(String value) {
    megaJNI.MegaStringList_add(swigCPtr, this, value);
  }

  public MegaStringList() {
    this(megaJNI.new_MegaStringList(), true);
  }

}
