/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaTextChat {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaTextChat(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaTextChat obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaTextChat obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaTextChat(swigCPtr);
      }
      swigCPtr = 0;
    }
}

   MegaTextChat copy() {
    long cPtr = megaJNI.MegaTextChat_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaTextChat(cPtr, false);
  }

  public long getHandle() {
    return megaJNI.MegaTextChat_getHandle(swigCPtr, this);
  }

  public int getOwnPrivilege() {
    return megaJNI.MegaTextChat_getOwnPrivilege(swigCPtr, this);
  }

  public int getShard() {
    return megaJNI.MegaTextChat_getShard(swigCPtr, this);
  }

  public MegaTextChatPeerList getPeerList() {
    long cPtr = megaJNI.MegaTextChat_getPeerList(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaTextChatPeerList(cPtr, false);
  }

  public void setPeerList(MegaTextChatPeerList peers) {
    megaJNI.MegaTextChat_setPeerList(swigCPtr, this, MegaTextChatPeerList.getCPtr(peers), peers);
  }

  public boolean isGroup() {
    return megaJNI.MegaTextChat_isGroup(swigCPtr, this);
  }

  public long getOriginatingUser() {
    return megaJNI.MegaTextChat_getOriginatingUser(swigCPtr, this);
  }

  public String getTitle() {
    return megaJNI.MegaTextChat_getTitle(swigCPtr, this);
  }

  public String getUnifiedKey() {
    return megaJNI.MegaTextChat_getUnifiedKey(swigCPtr, this);
  }

  public short getChatOptions() {
    return megaJNI.MegaTextChat_getChatOptions(swigCPtr, this);
  }

  public boolean hasChanged(long changeType) {
    return megaJNI.MegaTextChat_hasChanged(swigCPtr, this, changeType);
  }

  public long getChanges() {
    return megaJNI.MegaTextChat_getChanges(swigCPtr, this);
  }

  public int isOwnChange() {
    return megaJNI.MegaTextChat_isOwnChange(swigCPtr, this);
  }

  public MegaScheduledMeetingList getScheduledMeetingList() {
    long cPtr = megaJNI.MegaTextChat_getScheduledMeetingList(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaScheduledMeetingList(cPtr, false);
  }

  public MegaScheduledMeetingList getUpdatedOccurrencesList() {
    long cPtr = megaJNI.MegaTextChat_getUpdatedOccurrencesList(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaScheduledMeetingList(cPtr, false);
  }

  public MegaHandleList getSchedMeetingsChanged() {
    long cPtr = megaJNI.MegaTextChat_getSchedMeetingsChanged(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaHandleList(cPtr, false);
  }

  public long getCreationTime() {
    return megaJNI.MegaTextChat_getCreationTime(swigCPtr, this);
  }

  public boolean isArchived() {
    return megaJNI.MegaTextChat_isArchived(swigCPtr, this);
  }

  public boolean isPublicChat() {
    return megaJNI.MegaTextChat_isPublicChat(swigCPtr, this);
  }

  public boolean isMeeting() {
    return megaJNI.MegaTextChat_isMeeting(swigCPtr, this);
  }

  public MegaTextChat() {
    this(megaJNI.new_MegaTextChat(), true);
  }

  public final static int CHANGE_TYPE_ATTACHMENT = 1;
  public final static int CHANGE_TYPE_FLAGS = 2;
  public final static int CHANGE_TYPE_MODE = 4;
  public final static int CHANGE_TYPE_CHAT_OPTIONS = 8;
  public final static int CHANGE_TYPE_SCHED_MEETING = 16;
  public final static int CHANGE_TYPE_SCHED_REPLACE_OCURR = 32;
  public final static int CHANGE_TYPE_SCHED_APPEND_OCURR = 64;

}
