/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaCurrency {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaCurrency(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaCurrency obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaCurrency obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaCurrency(swigCPtr);
      }
      swigCPtr = 0;
    }
}

   MegaCurrency copy() {
    long cPtr = megaJNI.MegaCurrency_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaCurrency(cPtr, false);
  }

  public String getCurrencySymbol() {
    return megaJNI.MegaCurrency_getCurrencySymbol(swigCPtr, this);
  }

  public String getCurrencyName() {
    return megaJNI.MegaCurrency_getCurrencyName(swigCPtr, this);
  }

  public String getLocalCurrencySymbol() {
    return megaJNI.MegaCurrency_getLocalCurrencySymbol(swigCPtr, this);
  }

  public String getLocalCurrencyName() {
    return megaJNI.MegaCurrency_getLocalCurrencyName(swigCPtr, this);
  }

  public MegaCurrency() {
    this(megaJNI.new_MegaCurrency(), true);
  }

}
