/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaUploadOptions {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaUploadOptions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaUploadOptions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaUploadOptions obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaUploadOptions(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public MegaUploadOptions() {
    this(megaJNI.new_MegaUploadOptions(), true);
  }

  public static MegaUploadOptions createInstance() {
    long cPtr = megaJNI.MegaUploadOptions_createInstance();
    return (cPtr == 0) ? null : new MegaUploadOptions(cPtr, false);
  }

  public void setFileName(String value) {
    megaJNI.MegaUploadOptions_fileName_set(swigCPtr, this, value);
  }

  public String getFileName() {
    return megaJNI.MegaUploadOptions_fileName_get(swigCPtr, this);
  }

  public void setMtime(long value) {
    megaJNI.MegaUploadOptions_mtime_set(swigCPtr, this, value);
  }

  public long getMtime() {
    return megaJNI.MegaUploadOptions_mtime_get(swigCPtr, this);
  }

  public void setAppData(String value) {
    megaJNI.MegaUploadOptions_appData_set(swigCPtr, this, value);
  }

  public String getAppData() {
    return megaJNI.MegaUploadOptions_appData_get(swigCPtr, this);
  }

  public void setIsSourceTemporary(boolean value) {
    megaJNI.MegaUploadOptions_isSourceTemporary_set(swigCPtr, this, value);
  }

  public boolean getIsSourceTemporary() {
    return megaJNI.MegaUploadOptions_isSourceTemporary_get(swigCPtr, this);
  }

  public void setStartFirst(boolean value) {
    megaJNI.MegaUploadOptions_startFirst_set(swigCPtr, this, value);
  }

  public boolean getStartFirst() {
    return megaJNI.MegaUploadOptions_startFirst_get(swigCPtr, this);
  }

  public void setPitagTrigger(char value) {
    megaJNI.MegaUploadOptions_pitagTrigger_set(swigCPtr, this, value);
  }

  public char getPitagTrigger() {
    return megaJNI.MegaUploadOptions_pitagTrigger_get(swigCPtr, this);
  }

  public void setIsChatUpload(boolean value) {
    megaJNI.MegaUploadOptions_isChatUpload_set(swigCPtr, this, value);
  }

  public boolean getIsChatUpload() {
    return megaJNI.MegaUploadOptions_isChatUpload_get(swigCPtr, this);
  }

  public void setPitagTarget(char value) {
    megaJNI.MegaUploadOptions_pitagTarget_set(swigCPtr, this, value);
  }

  public char getPitagTarget() {
    return megaJNI.MegaUploadOptions_pitagTarget_get(swigCPtr, this);
  }

  public final static long INVALID_CUSTOM_MOD_TIME = -1;
  public final static char PITAG_TRIGGER_NOT_APPLICABLE = '.';
  public final static char PITAG_TARGET_NOT_APPLICABLE = '.';
}
