/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaCancelSubscriptionReasonList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaCancelSubscriptionReasonList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaCancelSubscriptionReasonList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaCancelSubscriptionReasonList obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaCancelSubscriptionReasonList(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public static MegaCancelSubscriptionReasonList create() {
    long cPtr = megaJNI.MegaCancelSubscriptionReasonList_create();
    return (cPtr == 0) ? null : new MegaCancelSubscriptionReasonList(cPtr, false);
  }

  public void add(MegaCancelSubscriptionReason reason) {
    megaJNI.MegaCancelSubscriptionReasonList_add(swigCPtr, this, MegaCancelSubscriptionReason.getCPtr(reason), reason);
  }

  public MegaCancelSubscriptionReason get(long index) {
    long cPtr = megaJNI.MegaCancelSubscriptionReasonList_get(swigCPtr, this, index);
    return (cPtr == 0) ? null : new MegaCancelSubscriptionReason(cPtr, false);
  }

  public long size() {
    return megaJNI.MegaCancelSubscriptionReasonList_size(swigCPtr, this);
  }

   MegaCancelSubscriptionReasonList copy() {
    long cPtr = megaJNI.MegaCancelSubscriptionReasonList_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaCancelSubscriptionReasonList(cPtr, false);
  }

}
