/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaCancelSubscriptionReason {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaCancelSubscriptionReason(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaCancelSubscriptionReason obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaCancelSubscriptionReason obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaCancelSubscriptionReason(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public static MegaCancelSubscriptionReason create(String text, String position) {
    long cPtr = megaJNI.MegaCancelSubscriptionReason_create(text, position);
    return (cPtr == 0) ? null : new MegaCancelSubscriptionReason(cPtr, false);
  }

  public String text() {
    return megaJNI.MegaCancelSubscriptionReason_text(swigCPtr, this);
  }

  public String position() {
    return megaJNI.MegaCancelSubscriptionReason_position(swigCPtr, this);
  }

   MegaCancelSubscriptionReason copy() {
    long cPtr = megaJNI.MegaCancelSubscriptionReason_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaCancelSubscriptionReason(cPtr, false);
  }

}
