/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaStringIntegerMap {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaStringIntegerMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaStringIntegerMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaStringIntegerMap obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaStringIntegerMap(swigCPtr);
      }
      swigCPtr = 0;
    }
}

   MegaStringIntegerMap copy() {
    long cPtr = megaJNI.MegaStringIntegerMap_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaStringIntegerMap(cPtr, false);
  }

  public MegaStringList getKeys() {
    long cPtr = megaJNI.MegaStringIntegerMap_getKeys(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaStringList(cPtr, false);
  }

  public MegaIntegerList get(String key) {
    long cPtr = megaJNI.MegaStringIntegerMap_get(swigCPtr, this, key);
    return (cPtr == 0) ? null : new MegaIntegerList(cPtr, false);
  }

  public void set(String key, long value) {
    megaJNI.MegaStringIntegerMap_set(swigCPtr, this, key, value);
  }

  public long size() {
    return megaJNI.MegaStringIntegerMap_size(swigCPtr, this);
  }

}
