/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaMount {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaMount(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaMount obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaMount obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaMount(swigCPtr);
      }
      swigCPtr = 0;
    }
}

   MegaMount copy() {
    long cPtr = megaJNI.MegaMount_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaMount(cPtr, false);
  }

  public static MegaMount create() {
    long cPtr = megaJNI.MegaMount_create();
    return (cPtr == 0) ? null : new MegaMount(cPtr, false);
  }

  public MegaMountFlags getFlags() {
    long cPtr = megaJNI.MegaMount_getFlags(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaMountFlags(cPtr, false);
  }

  public long getHandle() {
    return megaJNI.MegaMount_getHandle(swigCPtr, this);
  }

  public String getPath() {
    return megaJNI.MegaMount_getPath(swigCPtr, this);
  }

  public static String getResultDescription(int result) {
    return megaJNI.MegaMount_getResultDescription(result);
  }

  public static String getResultString(int result) {
    return megaJNI.MegaMount_getResultString(result);
  }

  public void setFlags(MegaMountFlags flags) {
    megaJNI.MegaMount_setFlags(swigCPtr, this, MegaMountFlags.getCPtr(flags), flags);
  }

  public void setHandle(long handle) {
    megaJNI.MegaMount_setHandle(swigCPtr, this, handle);
  }

  public void setPath(String path) {
    megaJNI.MegaMount_setPath(swigCPtr, this, path);
  }

  public final static class Result {
    public final static MegaMount.Result ABORTED = new MegaMount.Result("ABORTED");
    public final static MegaMount.Result BACKEND_UNAVAILABLE = new MegaMount.Result("BACKEND_UNAVAILABLE");
    public final static MegaMount.Result BUSY = new MegaMount.Result("BUSY");
    public final static MegaMount.Result FAILED = new MegaMount.Result("FAILED");
    public final static MegaMount.Result LOCAL_EXISTS = new MegaMount.Result("LOCAL_EXISTS");
    public final static MegaMount.Result LOCAL_FILE = new MegaMount.Result("LOCAL_FILE");
    public final static MegaMount.Result LOCAL_SYNCING = new MegaMount.Result("LOCAL_SYNCING");
    public final static MegaMount.Result LOCAL_TAKEN = new MegaMount.Result("LOCAL_TAKEN");
    public final static MegaMount.Result LOCAL_UNKNOWN = new MegaMount.Result("LOCAL_UNKNOWN");
    public final static MegaMount.Result NAME_TAKEN = new MegaMount.Result("NAME_TAKEN");
    public final static MegaMount.Result NAME_TOO_LONG = new MegaMount.Result("NAME_TOO_LONG");
    public final static MegaMount.Result NAME_INVALID_CHAR = new MegaMount.Result("NAME_INVALID_CHAR");
    public final static MegaMount.Result NO_NAME = new MegaMount.Result("NO_NAME");
    public final static MegaMount.Result REMOTE_FILE = new MegaMount.Result("REMOTE_FILE");
    public final static MegaMount.Result REMOTE_UNKNOWN = new MegaMount.Result("REMOTE_UNKNOWN");
    public final static MegaMount.Result SUCCESS = new MegaMount.Result("SUCCESS");
    public final static MegaMount.Result UNEXPECTED = new MegaMount.Result("UNEXPECTED");
    public final static MegaMount.Result UNKNOWN = new MegaMount.Result("UNKNOWN");
    public final static MegaMount.Result UNSUPPORTED = new MegaMount.Result("UNSUPPORTED");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static Result swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + Result.class + " with value " + swigValue);
    }

    private Result(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private Result(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private Result(String swigName, Result swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static Result[] swigValues = { ABORTED, BACKEND_UNAVAILABLE, BUSY, FAILED, LOCAL_EXISTS, LOCAL_FILE, LOCAL_SYNCING, LOCAL_TAKEN, LOCAL_UNKNOWN, NAME_TAKEN, NAME_TOO_LONG, NAME_INVALID_CHAR, NO_NAME, REMOTE_FILE, REMOTE_UNKNOWN, SUCCESS, UNEXPECTED, UNKNOWN, UNSUPPORTED };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
