/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaSyncStallList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaSyncStallList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaSyncStallList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaSyncStallList obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaSyncStallList(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public MegaSyncStallList() {
    this(megaJNI.new_MegaSyncStallList(), true);
  }

   MegaSyncStallList copy() {
    long cPtr = megaJNI.MegaSyncStallList_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaSyncStallList(cPtr, true);
  }

  public MegaSyncStall get(long index) {
    long cPtr = megaJNI.MegaSyncStallList_get(swigCPtr, this, index);
    return (cPtr == 0) ? null : new MegaSyncStall(cPtr, false);
  }

  public long size() {
    return megaJNI.MegaSyncStallList_size(swigCPtr, this);
  }

  public long getHash() {
    return megaJNI.MegaSyncStallList_getHash(swigCPtr, this);
  }

}
