/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaScheduledCopyListener {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaScheduledCopyListener(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaScheduledCopyListener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaScheduledCopyListener obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaScheduledCopyListener(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public void onBackupStateChanged(MegaApi api, MegaScheduledCopy backup) {
    megaJNI.MegaScheduledCopyListener_onBackupStateChanged(swigCPtr, this, MegaApi.getCPtr(api), api, MegaScheduledCopy.getCPtr(backup), backup);
  }

  public void onBackupStart(MegaApi api, MegaScheduledCopy backup) {
    megaJNI.MegaScheduledCopyListener_onBackupStart(swigCPtr, this, MegaApi.getCPtr(api), api, MegaScheduledCopy.getCPtr(backup), backup);
  }

  public void onBackupFinish(MegaApi api, MegaScheduledCopy backup, MegaError error) {
    megaJNI.MegaScheduledCopyListener_onBackupFinish(swigCPtr, this, MegaApi.getCPtr(api), api, MegaScheduledCopy.getCPtr(backup), backup, MegaError.getCPtr(error), error);
  }

  public void onBackupUpdate(MegaApi api, MegaScheduledCopy backup) {
    megaJNI.MegaScheduledCopyListener_onBackupUpdate(swigCPtr, this, MegaApi.getCPtr(api), api, MegaScheduledCopy.getCPtr(backup), backup);
  }

  public void onBackupTemporaryError(MegaApi api, MegaScheduledCopy backup, MegaError error) {
    megaJNI.MegaScheduledCopyListener_onBackupTemporaryError(swigCPtr, this, MegaApi.getCPtr(api), api, MegaScheduledCopy.getCPtr(backup), backup, MegaError.getCPtr(error), error);
  }

  public MegaScheduledCopyListener() {
    this(megaJNI.new_MegaScheduledCopyListener(), true);
  }

}
