/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaFuseFlags {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaFuseFlags(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaFuseFlags obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaFuseFlags obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaFuseFlags(swigCPtr);
      }
      swigCPtr = 0;
    }
}

   MegaFuseFlags copy() {
    long cPtr = megaJNI.MegaFuseFlags_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaFuseFlags(cPtr, false);
  }

  public static MegaFuseFlags create() {
    long cPtr = megaJNI.MegaFuseFlags_create();
    return (cPtr == 0) ? null : new MegaFuseFlags(cPtr, false);
  }

  public long getFlushDelay() {
    return megaJNI.MegaFuseFlags_getFlushDelay(swigCPtr, this);
  }

  public int getLogLevel() {
    return megaJNI.MegaFuseFlags_getLogLevel(swigCPtr, this);
  }

  public int getFileExplorerView() {
    return megaJNI.MegaFuseFlags_getFileExplorerView(swigCPtr, this);
  }

  public MegaFuseInodeCacheFlags getInodeCacheFlags() {
    long cPtr = megaJNI.MegaFuseFlags_getInodeCacheFlags(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaFuseInodeCacheFlags(cPtr, false);
  }

  public MegaFuseExecutorFlags getMountExecutorFlags() {
    long cPtr = megaJNI.MegaFuseFlags_getMountExecutorFlags(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaFuseExecutorFlags(cPtr, false);
  }

  public MegaFuseExecutorFlags getSubsystemExecutorFlags() {
    long cPtr = megaJNI.MegaFuseFlags_getSubsystemExecutorFlags(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaFuseExecutorFlags(cPtr, false);
  }

  public void setFlushDelay(long seconds) {
    megaJNI.MegaFuseFlags_setFlushDelay(swigCPtr, this, seconds);
  }

  public void setLogLevel(int level) {
    megaJNI.MegaFuseFlags_setLogLevel(swigCPtr, this, level);
  }

  public void setFileExplorerView(int view) {
    megaJNI.MegaFuseFlags_setFileExplorerView(swigCPtr, this, view);
  }

  public final static class LogLevel {
    public final static MegaFuseFlags.LogLevel LOG_LEVEL_ERROR = new MegaFuseFlags.LogLevel("LOG_LEVEL_ERROR");
    public final static MegaFuseFlags.LogLevel LOG_LEVEL_WARNING = new MegaFuseFlags.LogLevel("LOG_LEVEL_WARNING");
    public final static MegaFuseFlags.LogLevel LOG_LEVEL_INFO = new MegaFuseFlags.LogLevel("LOG_LEVEL_INFO");
    public final static MegaFuseFlags.LogLevel LOG_LEVEL_DEBUG = new MegaFuseFlags.LogLevel("LOG_LEVEL_DEBUG");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static LogLevel swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + LogLevel.class + " with value " + swigValue);
    }

    private LogLevel(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private LogLevel(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private LogLevel(String swigName, LogLevel swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static LogLevel[] swigValues = { LOG_LEVEL_ERROR, LOG_LEVEL_WARNING, LOG_LEVEL_INFO, LOG_LEVEL_DEBUG };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

  public final static class FileExplorerView {
    public final static MegaFuseFlags.FileExplorerView FILE_EXPLORER_VIEW_NONE = new MegaFuseFlags.FileExplorerView("FILE_EXPLORER_VIEW_NONE", 0);
    public final static MegaFuseFlags.FileExplorerView FILE_EXPLORER_VIEW_LIST = new MegaFuseFlags.FileExplorerView("FILE_EXPLORER_VIEW_LIST", 1);

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static FileExplorerView swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + FileExplorerView.class + " with value " + swigValue);
    }

    private FileExplorerView(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private FileExplorerView(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private FileExplorerView(String swigName, FileExplorerView swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static FileExplorerView[] swigValues = { FILE_EXPLORER_VIEW_NONE, FILE_EXPLORER_VIEW_LIST };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
