/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaMountFlags {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaMountFlags(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaMountFlags obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaMountFlags obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaMountFlags(swigCPtr);
      }
      swigCPtr = 0;
    }
}

   MegaMountFlags copy() {
    long cPtr = megaJNI.MegaMountFlags_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaMountFlags(cPtr, false);
  }

  public static MegaMountFlags create() {
    long cPtr = megaJNI.MegaMountFlags_create();
    return (cPtr == 0) ? null : new MegaMountFlags(cPtr, false);
  }

  public boolean getEnableAtStartup() {
    return megaJNI.MegaMountFlags_getEnableAtStartup(swigCPtr, this);
  }

  public String getName() {
    return megaJNI.MegaMountFlags_getName(swigCPtr, this);
  }

  public boolean getPersistent() {
    return megaJNI.MegaMountFlags_getPersistent(swigCPtr, this);
  }

  public boolean getReadOnly() {
    return megaJNI.MegaMountFlags_getReadOnly(swigCPtr, this);
  }

  public void setEnableAtStartup(boolean enable) {
    megaJNI.MegaMountFlags_setEnableAtStartup(swigCPtr, this, enable);
  }

  public void setName(String name) {
    megaJNI.MegaMountFlags_setName(swigCPtr, this, name);
  }

  public void setPersistent(boolean persistent) {
    megaJNI.MegaMountFlags_setPersistent(swigCPtr, this, persistent);
  }

  public void setReadOnly(boolean readOnly) {
    megaJNI.MegaMountFlags_setReadOnly(swigCPtr, this, readOnly);
  }

}
