/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaAccountSubscription {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaAccountSubscription(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaAccountSubscription obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaAccountSubscription obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaAccountSubscription(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public String getId() {
    return megaJNI.MegaAccountSubscription_getId(swigCPtr, this);
  }

  public int getStatus() {
    return megaJNI.MegaAccountSubscription_getStatus(swigCPtr, this);
  }

  public String getCycle() {
    return megaJNI.MegaAccountSubscription_getCycle(swigCPtr, this);
  }

  public String getPaymentMethod() {
    return megaJNI.MegaAccountSubscription_getPaymentMethod(swigCPtr, this);
  }

  public long getPaymentMethodId() {
    return megaJNI.MegaAccountSubscription_getPaymentMethodId(swigCPtr, this);
  }

  public long getRenewTime() {
    return megaJNI.MegaAccountSubscription_getRenewTime(swigCPtr, this);
  }

  public long getAccountLevel() {
    return megaJNI.MegaAccountSubscription_getAccountLevel(swigCPtr, this);
  }

  public MegaStringList getFeatures() {
    long cPtr = megaJNI.MegaAccountSubscription_getFeatures(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaStringList(cPtr, false);
  }

  public boolean isTrial() {
    return megaJNI.MegaAccountSubscription_isTrial(swigCPtr, this);
  }

  public final static int SUBSCRIPTION_STATUS_NONE = 0;
  public final static int SUBSCRIPTION_STATUS_VALID = 1;
  public final static int SUBSCRIPTION_STATUS_INVALID = 2;

}
