/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaFuseExecutorFlags {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaFuseExecutorFlags(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaFuseExecutorFlags obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaFuseExecutorFlags obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaFuseExecutorFlags(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public long getMaxThreadCount() {
    return megaJNI.MegaFuseExecutorFlags_getMaxThreadCount(swigCPtr, this);
  }

  public long getMaxThreadIdleTime() {
    return megaJNI.MegaFuseExecutorFlags_getMaxThreadIdleTime(swigCPtr, this);
  }

  public long getMinThreadCount() {
    return megaJNI.MegaFuseExecutorFlags_getMinThreadCount(swigCPtr, this);
  }

  public boolean setMaxThreadCount(long max) {
    return megaJNI.MegaFuseExecutorFlags_setMaxThreadCount(swigCPtr, this, max);
  }

  public void setMaxThreadIdleTime(long seconds) {
    megaJNI.MegaFuseExecutorFlags_setMaxThreadIdleTime(swigCPtr, this, seconds);
  }

  public void setMinThreadCount(long min) {
    megaJNI.MegaFuseExecutorFlags_setMinThreadCount(swigCPtr, this, min);
  }

}
