/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaScheduledCopy {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaScheduledCopy(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaScheduledCopy obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaScheduledCopy obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaScheduledCopy(swigCPtr);
      }
      swigCPtr = 0;
    }
}

   MegaScheduledCopy copy() {
    long cPtr = megaJNI.MegaScheduledCopy_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaScheduledCopy(cPtr, false);
  }

  public long getMegaHandle() {
    return megaJNI.MegaScheduledCopy_getMegaHandle(swigCPtr, this);
  }

  public String getLocalFolder() {
    return megaJNI.MegaScheduledCopy_getLocalFolder(swigCPtr, this);
  }

  public int getTag() {
    return megaJNI.MegaScheduledCopy_getTag(swigCPtr, this);
  }

  public boolean getAttendPastBackups() {
    return megaJNI.MegaScheduledCopy_getAttendPastBackups(swigCPtr, this);
  }

  public long getPeriod() {
    return megaJNI.MegaScheduledCopy_getPeriod(swigCPtr, this);
  }

  public String getPeriodString() {
    return megaJNI.MegaScheduledCopy_getPeriodString(swigCPtr, this);
  }

  public long getNextStartTime(long oldStartTimeAbsolute) {
    return megaJNI.MegaScheduledCopy_getNextStartTime__SWIG_0(swigCPtr, this, oldStartTimeAbsolute);
  }

  public long getNextStartTime() {
    return megaJNI.MegaScheduledCopy_getNextStartTime__SWIG_1(swigCPtr, this);
  }

  public int getMaxBackups() {
    return megaJNI.MegaScheduledCopy_getMaxBackups(swigCPtr, this);
  }

  public int getState() {
    return megaJNI.MegaScheduledCopy_getState(swigCPtr, this);
  }

  public long getNumberFolders() {
    return megaJNI.MegaScheduledCopy_getNumberFolders(swigCPtr, this);
  }

  public long getNumberFiles() {
    return megaJNI.MegaScheduledCopy_getNumberFiles(swigCPtr, this);
  }

  public long getTotalFiles() {
    return megaJNI.MegaScheduledCopy_getTotalFiles(swigCPtr, this);
  }

  public long getCurrentBKStartTime() {
    return megaJNI.MegaScheduledCopy_getCurrentBKStartTime(swigCPtr, this);
  }

  public long getTransferredBytes() {
    return megaJNI.MegaScheduledCopy_getTransferredBytes(swigCPtr, this);
  }

  public long getTotalBytes() {
    return megaJNI.MegaScheduledCopy_getTotalBytes(swigCPtr, this);
  }

  public long getSpeed() {
    return megaJNI.MegaScheduledCopy_getSpeed(swigCPtr, this);
  }

  public long getMeanSpeed() {
    return megaJNI.MegaScheduledCopy_getMeanSpeed(swigCPtr, this);
  }

  public long getUpdateTime() {
    return megaJNI.MegaScheduledCopy_getUpdateTime(swigCPtr, this);
  }

  public MegaTransferList getFailedTransfers() {
    long cPtr = megaJNI.MegaScheduledCopy_getFailedTransfers(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaTransferList(cPtr, false);
  }

  public MegaScheduledCopy() {
    this(megaJNI.new_MegaScheduledCopy(), true);
  }

  public final static int SCHEDULED_COPY_FAILED = -2;
  public final static int SCHEDULED_COPY_CANCELED = -1;
  public final static int SCHEDULED_COPY_INITIALSCAN = 0;
  public final static int SCHEDULED_COPY_ACTIVE = SCHEDULED_COPY_INITIALSCAN + 1;
  public final static int SCHEDULED_COPY_ONGOING = SCHEDULED_COPY_ACTIVE + 1;
  public final static int SCHEDULED_COPY_SKIPPING = SCHEDULED_COPY_ONGOING + 1;
  public final static int SCHEDULED_COPY_REMOVING_EXCEEDING = SCHEDULED_COPY_SKIPPING + 1;

}
