/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaNotification {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaNotification(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaNotification obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaNotification obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaNotification(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public long getID() {
    return megaJNI.MegaNotification_getID(swigCPtr, this);
  }

  public String getTitle() {
    return megaJNI.MegaNotification_getTitle(swigCPtr, this);
  }

  public String getDescription() {
    return megaJNI.MegaNotification_getDescription(swigCPtr, this);
  }

  public String getImageName() {
    return megaJNI.MegaNotification_getImageName(swigCPtr, this);
  }

  public String getIconName() {
    return megaJNI.MegaNotification_getIconName(swigCPtr, this);
  }

  public String getImagePath() {
    return megaJNI.MegaNotification_getImagePath(swigCPtr, this);
  }

  public long getStart() {
    return megaJNI.MegaNotification_getStart(swigCPtr, this);
  }

  public long getEnd() {
    return megaJNI.MegaNotification_getEnd(swigCPtr, this);
  }

  public boolean showBanner() {
    return megaJNI.MegaNotification_showBanner(swigCPtr, this);
  }

  public MegaStringMap getCallToAction1() {
    long cPtr = megaJNI.MegaNotification_getCallToAction1(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaStringMap(cPtr, false);
  }

  public MegaStringMap getCallToAction2() {
    long cPtr = megaJNI.MegaNotification_getCallToAction2(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaStringMap(cPtr, false);
  }

  public MegaStringList getRenderModes() {
    long cPtr = megaJNI.MegaNotification_getRenderModes(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaStringList(cPtr, false);
  }

  public MegaStringMap getRenderModeFields(String mode) {
    long cPtr = megaJNI.MegaNotification_getRenderModeFields(swigCPtr, this, mode);
    return (cPtr == 0) ? null : new MegaStringMap(cPtr, false);
  }

   MegaNotification copy() {
    long cPtr = megaJNI.MegaNotification_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaNotification(cPtr, false);
  }

}
