/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaFolderInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaFolderInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaFolderInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaFolderInfo obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaFolderInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
}

   MegaFolderInfo copy() {
    long cPtr = megaJNI.MegaFolderInfo_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaFolderInfo(cPtr, false);
  }

  public int getNumVersions() {
    return megaJNI.MegaFolderInfo_getNumVersions(swigCPtr, this);
  }

  public int getNumFiles() {
    return megaJNI.MegaFolderInfo_getNumFiles(swigCPtr, this);
  }

  public int getNumFolders() {
    return megaJNI.MegaFolderInfo_getNumFolders(swigCPtr, this);
  }

  public long getCurrentSize() {
    return megaJNI.MegaFolderInfo_getCurrentSize(swigCPtr, this);
  }

  public long getVersionsSize() {
    return megaJNI.MegaFolderInfo_getVersionsSize(swigCPtr, this);
  }

  public MegaFolderInfo() {
    this(megaJNI.new_MegaFolderInfo(), true);
  }

}
