/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaNetworkConnectivityTestResults {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaNetworkConnectivityTestResults(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaNetworkConnectivityTestResults obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaNetworkConnectivityTestResults obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaNetworkConnectivityTestResults(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public int getIPv4UDP() {
    return megaJNI.MegaNetworkConnectivityTestResults_getIPv4UDP(swigCPtr, this);
  }

  public int getIPv4DNS() {
    return megaJNI.MegaNetworkConnectivityTestResults_getIPv4DNS(swigCPtr, this);
  }

  public int getIPv6UDP() {
    return megaJNI.MegaNetworkConnectivityTestResults_getIPv6UDP(swigCPtr, this);
  }

  public int getIPv6DNS() {
    return megaJNI.MegaNetworkConnectivityTestResults_getIPv6DNS(swigCPtr, this);
  }

   MegaNetworkConnectivityTestResults copy() {
    long cPtr = megaJNI.MegaNetworkConnectivityTestResults_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaNetworkConnectivityTestResults(cPtr, false);
  }

  public final static int NETWORK_CONNECTIVITY_TEST_PASS = 0;
  public final static int NETWORK_CONNECTIVITY_TEST_FAIL = 1;
  public final static int NETWORK_CONNECTIVITY_TEST_NET_UNREACHABLE = 2;

}
