/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaSearchPage {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaSearchPage(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaSearchPage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaSearchPage obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaSearchPage(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public static MegaSearchPage createInstance(long startingOffset, long size) {
    long cPtr = megaJNI.MegaSearchPage_createInstance(startingOffset, size);
    return (cPtr == 0) ? null : new MegaSearchPage(cPtr, false);
  }

   MegaSearchPage copy() {
    long cPtr = megaJNI.MegaSearchPage_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaSearchPage(cPtr, false);
  }

  public long startingOffset() {
    return megaJNI.MegaSearchPage_startingOffset(swigCPtr, this);
  }

  public long size() {
    return megaJNI.MegaSearchPage_size(swigCPtr, this);
  }

}
