/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaTotpTokenLifetime {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaTotpTokenLifetime(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaTotpTokenLifetime obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaTotpTokenLifetime obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaTotpTokenLifetime(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public void setToken(String value) {
    megaJNI.MegaTotpTokenLifetime_token_set(swigCPtr, this, value);
  }

  public String getToken() {
    return megaJNI.MegaTotpTokenLifetime_token_get(swigCPtr, this);
  }

  public void setRemainingLifeTimeSeconds(long value) {
    megaJNI.MegaTotpTokenLifetime_remainingLifeTimeSeconds_set(swigCPtr, this, value);
  }

  public long getRemainingLifeTimeSeconds() {
    return megaJNI.MegaTotpTokenLifetime_remainingLifeTimeSeconds_get(swigCPtr, this);
  }

  public MegaTotpTokenLifetime() {
    this(megaJNI.new_MegaTotpTokenLifetime(), true);
  }

}
