/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaIntegerMap {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaIntegerMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaIntegerMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaIntegerMap obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaIntegerMap(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public static MegaIntegerMap createInstance() {
    long cPtr = megaJNI.MegaIntegerMap_createInstance();
    return (cPtr == 0) ? null : new MegaIntegerMap(cPtr, false);
  }

   MegaIntegerMap copy() {
    long cPtr = megaJNI.MegaIntegerMap_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaIntegerMap(cPtr, false);
  }

  public MegaIntegerList getKeys() {
    long cPtr = megaJNI.MegaIntegerMap_getKeys(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaIntegerList(cPtr, false);
  }

  public MegaIntegerList get(long key) {
    long cPtr = megaJNI.MegaIntegerMap_get(swigCPtr, this, key);
    return (cPtr == 0) ? null : new MegaIntegerList(cPtr, false);
  }

  public void set(long key, long value) {
    megaJNI.MegaIntegerMap_set(swigCPtr, this, key, value);
  }

  public long size() {
    return megaJNI.MegaIntegerMap_size(swigCPtr, this);
  }

  public MegaIntegerMap() {
    this(megaJNI.new_MegaIntegerMap(), true);
  }

}
