/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaSyncStats {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaSyncStats(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaSyncStats obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaSyncStats obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaSyncStats(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public long getBackupId() {
    return megaJNI.MegaSyncStats_getBackupId(swigCPtr, this);
  }

  public boolean isScanning() {
    return megaJNI.MegaSyncStats_isScanning(swigCPtr, this);
  }

  public boolean isSyncing() {
    return megaJNI.MegaSyncStats_isSyncing(swigCPtr, this);
  }

  public int getFolderCount() {
    return megaJNI.MegaSyncStats_getFolderCount(swigCPtr, this);
  }

  public int getFileCount() {
    return megaJNI.MegaSyncStats_getFileCount(swigCPtr, this);
  }

  public int getUploadCount() {
    return megaJNI.MegaSyncStats_getUploadCount(swigCPtr, this);
  }

  public int getDownloadCount() {
    return megaJNI.MegaSyncStats_getDownloadCount(swigCPtr, this);
  }

   MegaSyncStats copy() {
    long cPtr = megaJNI.MegaSyncStats_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaSyncStats(cPtr, true);
  }

}
