/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

class MegaGlobalListener {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaGlobalListener(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaGlobalListener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaGlobalListener obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaGlobalListener(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    megaJNI.MegaGlobalListener_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    megaJNI.MegaGlobalListener_change_ownership(this, swigCPtr, true);
  }

  public void onUsersUpdate(MegaApi api, MegaUserList users) {
    if (getClass() == MegaGlobalListener.class) megaJNI.MegaGlobalListener_onUsersUpdate(swigCPtr, this, MegaApi.getCPtr(api), api, MegaUserList.getCPtr(users), users); else megaJNI.MegaGlobalListener_onUsersUpdateSwigExplicitMegaGlobalListener(swigCPtr, this, MegaApi.getCPtr(api), api, MegaUserList.getCPtr(users), users);
  }

  public void onUserAlertsUpdate(MegaApi api, MegaUserAlertList alerts) {
    if (getClass() == MegaGlobalListener.class) megaJNI.MegaGlobalListener_onUserAlertsUpdate(swigCPtr, this, MegaApi.getCPtr(api), api, MegaUserAlertList.getCPtr(alerts), alerts); else megaJNI.MegaGlobalListener_onUserAlertsUpdateSwigExplicitMegaGlobalListener(swigCPtr, this, MegaApi.getCPtr(api), api, MegaUserAlertList.getCPtr(alerts), alerts);
  }

  public void onNodesUpdate(MegaApi api, MegaNodeList nodes) {
    if (getClass() == MegaGlobalListener.class) megaJNI.MegaGlobalListener_onNodesUpdate(swigCPtr, this, MegaApi.getCPtr(api), api, MegaNodeList.getCPtr(nodes), nodes); else megaJNI.MegaGlobalListener_onNodesUpdateSwigExplicitMegaGlobalListener(swigCPtr, this, MegaApi.getCPtr(api), api, MegaNodeList.getCPtr(nodes), nodes);
  }

  public void onAccountUpdate(MegaApi api) {
    if (getClass() == MegaGlobalListener.class) megaJNI.MegaGlobalListener_onAccountUpdate(swigCPtr, this, MegaApi.getCPtr(api), api); else megaJNI.MegaGlobalListener_onAccountUpdateSwigExplicitMegaGlobalListener(swigCPtr, this, MegaApi.getCPtr(api), api);
  }

  public void onSetsUpdate(MegaApi api, MegaSetList sets) {
    if (getClass() == MegaGlobalListener.class) megaJNI.MegaGlobalListener_onSetsUpdate(swigCPtr, this, MegaApi.getCPtr(api), api, MegaSetList.getCPtr(sets), sets); else megaJNI.MegaGlobalListener_onSetsUpdateSwigExplicitMegaGlobalListener(swigCPtr, this, MegaApi.getCPtr(api), api, MegaSetList.getCPtr(sets), sets);
  }

  public void onSetElementsUpdate(MegaApi api, MegaSetElementList elements) {
    if (getClass() == MegaGlobalListener.class) megaJNI.MegaGlobalListener_onSetElementsUpdate(swigCPtr, this, MegaApi.getCPtr(api), api, MegaSetElementList.getCPtr(elements), elements); else megaJNI.MegaGlobalListener_onSetElementsUpdateSwigExplicitMegaGlobalListener(swigCPtr, this, MegaApi.getCPtr(api), api, MegaSetElementList.getCPtr(elements), elements);
  }

  public void onContactRequestsUpdate(MegaApi api, MegaContactRequestList requests) {
    if (getClass() == MegaGlobalListener.class) megaJNI.MegaGlobalListener_onContactRequestsUpdate(swigCPtr, this, MegaApi.getCPtr(api), api, MegaContactRequestList.getCPtr(requests), requests); else megaJNI.MegaGlobalListener_onContactRequestsUpdateSwigExplicitMegaGlobalListener(swigCPtr, this, MegaApi.getCPtr(api), api, MegaContactRequestList.getCPtr(requests), requests);
  }

  public void onSeqTagUpdate(MegaApi api, SWIGTYPE_p_std__string seqTag) {
    if (getClass() == MegaGlobalListener.class) megaJNI.MegaGlobalListener_onSeqTagUpdate(swigCPtr, this, MegaApi.getCPtr(api), api, SWIGTYPE_p_std__string.getCPtr(seqTag)); else megaJNI.MegaGlobalListener_onSeqTagUpdateSwigExplicitMegaGlobalListener(swigCPtr, this, MegaApi.getCPtr(api), api, SWIGTYPE_p_std__string.getCPtr(seqTag));
  }

  public void onGlobalSyncStateChanged(MegaApi api) {
    if (getClass() == MegaGlobalListener.class) megaJNI.MegaGlobalListener_onGlobalSyncStateChanged(swigCPtr, this, MegaApi.getCPtr(api), api); else megaJNI.MegaGlobalListener_onGlobalSyncStateChangedSwigExplicitMegaGlobalListener(swigCPtr, this, MegaApi.getCPtr(api), api);
  }

  public void onChatsUpdate(MegaApi api, MegaTextChatList chats) {
    if (getClass() == MegaGlobalListener.class) megaJNI.MegaGlobalListener_onChatsUpdate(swigCPtr, this, MegaApi.getCPtr(api), api, MegaTextChatList.getCPtr(chats), chats); else megaJNI.MegaGlobalListener_onChatsUpdateSwigExplicitMegaGlobalListener(swigCPtr, this, MegaApi.getCPtr(api), api, MegaTextChatList.getCPtr(chats), chats);
  }

  public void onEvent(MegaApi api, MegaEvent event) {
    if (getClass() == MegaGlobalListener.class) megaJNI.MegaGlobalListener_onEvent(swigCPtr, this, MegaApi.getCPtr(api), api, MegaEvent.getCPtr(event), event); else megaJNI.MegaGlobalListener_onEventSwigExplicitMegaGlobalListener(swigCPtr, this, MegaApi.getCPtr(api), api, MegaEvent.getCPtr(event), event);
  }

  public void onDrivePresenceChanged(MegaApi api, boolean present, String rootPathInUtf8) {
    if (getClass() == MegaGlobalListener.class) megaJNI.MegaGlobalListener_onDrivePresenceChanged(swigCPtr, this, MegaApi.getCPtr(api), api, present, rootPathInUtf8); else megaJNI.MegaGlobalListener_onDrivePresenceChangedSwigExplicitMegaGlobalListener(swigCPtr, this, MegaApi.getCPtr(api), api, present, rootPathInUtf8);
  }

  @SuppressWarnings("this-escape")
  public MegaGlobalListener() {
    this(megaJNI.new_MegaGlobalListener(), true);
    megaJNI.MegaGlobalListener_director_connect(this, swigCPtr, true, true);
  }

}
