/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaSet {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaSet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaSet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaSet obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaSet(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public long id() {
    return megaJNI.MegaSet_id(swigCPtr, this);
  }

  public long publicId() {
    return megaJNI.MegaSet_publicId(swigCPtr, this);
  }

  public long user() {
    return megaJNI.MegaSet_user(swigCPtr, this);
  }

  public long ts() {
    return megaJNI.MegaSet_ts(swigCPtr, this);
  }

  public long cts() {
    return megaJNI.MegaSet_cts(swigCPtr, this);
  }

  public int type() {
    return megaJNI.MegaSet_type(swigCPtr, this);
  }

  public String name() {
    return megaJNI.MegaSet_name(swigCPtr, this);
  }

  public long cover() {
    return megaJNI.MegaSet_cover(swigCPtr, this);
  }

  public boolean hasChanged(long arg0) {
    return megaJNI.MegaSet_hasChanged(swigCPtr, this, arg0);
  }

  public long getChanges() {
    return megaJNI.MegaSet_getChanges(swigCPtr, this);
  }

  public boolean isExported() {
    return megaJNI.MegaSet_isExported(swigCPtr, this);
  }

  public int getLinkDeletionReason() {
    return megaJNI.MegaSet_getLinkDeletionReason(swigCPtr, this);
  }

  public boolean isTakenDown() {
    return megaJNI.MegaSet_isTakenDown(swigCPtr, this);
  }

   MegaSet copy() {
    long cPtr = megaJNI.MegaSet_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaSet(cPtr, true);
  }

  public MegaSet() {
    this(megaJNI.new_MegaSet(), true);
  }

  public final static int CHANGE_TYPE_NEW = 1;
  public final static int CHANGE_TYPE_NAME = 2;
  public final static int CHANGE_TYPE_COVER = 4;
  public final static int CHANGE_TYPE_REMOVED = 8;
  public final static int CHANGE_TYPE_EXPORT = 16;

  public final static int SET_TYPE_ALBUM = 0;
  public final static int SET_TYPE_PLAYLIST = 1;
  public final static int SET_TYPE_IGNORE = SET_TYPE_ALBUM;
  public final static int SET_TYPE_INVALID = -1;

  public final static int DELETION_LINK_NO_REMOVED = 0;
  public final static int DELETION_LINK_BY_USER = 1;
  public final static int DELETION_LINK_DISPUTE = 2;
  public final static int DELETION_LINK_ETD = 3;
  public final static int DELETION_LINK_ATD = 4;

}
