/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaGfxProvider {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaGfxProvider(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaGfxProvider obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaGfxProvider obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaGfxProvider(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public static MegaGfxProvider createIsolatedInstance(String endpointName, String executable, long keepAliveInSeconds, MegaStringList extraArgs) {
    long cPtr = megaJNI.MegaGfxProvider_createIsolatedInstance__SWIG_0(endpointName, executable, keepAliveInSeconds, MegaStringList.getCPtr(extraArgs), extraArgs);
    return (cPtr == 0) ? null : new MegaGfxProvider(cPtr, false);
  }

  public static MegaGfxProvider createIsolatedInstance(String endpointName, String executable, long keepAliveInSeconds) {
    long cPtr = megaJNI.MegaGfxProvider_createIsolatedInstance__SWIG_1(endpointName, executable, keepAliveInSeconds);
    return (cPtr == 0) ? null : new MegaGfxProvider(cPtr, false);
  }

  public static MegaGfxProvider createIsolatedInstance(String endpointName, String executable) {
    long cPtr = megaJNI.MegaGfxProvider_createIsolatedInstance__SWIG_2(endpointName, executable);
    return (cPtr == 0) ? null : new MegaGfxProvider(cPtr, false);
  }

  public static MegaGfxProvider createExternalInstance(MegaGfxProcessor processor) {
    long cPtr = megaJNI.MegaGfxProvider_createExternalInstance(MegaGfxProcessor.getCPtr(processor), processor);
    return (cPtr == 0) ? null : new MegaGfxProvider(cPtr, false);
  }

  public static MegaGfxProvider createInternalInstance() {
    long cPtr = megaJNI.MegaGfxProvider_createInternalInstance();
    return (cPtr == 0) ? null : new MegaGfxProvider(cPtr, false);
  }

  public MegaGfxProvider() {
    this(megaJNI.new_MegaGfxProvider(), true);
  }

}
