/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaTotpTokenGenResult {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaTotpTokenGenResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaTotpTokenGenResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaTotpTokenGenResult obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaTotpTokenGenResult(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public void setErrorCode(int value) {
    megaJNI.MegaTotpTokenGenResult_errorCode_set(swigCPtr, this, value);
  }

  public int getErrorCode() {
    return megaJNI.MegaTotpTokenGenResult_errorCode_get(swigCPtr, this);
  }

  public void setResult(MegaTotpTokenLifetime value) {
    megaJNI.MegaTotpTokenGenResult_result_set(swigCPtr, this, MegaTotpTokenLifetime.getCPtr(value), value);
  }

  public MegaTotpTokenLifetime getResult() {
    long cPtr = megaJNI.MegaTotpTokenGenResult_result_get(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaTotpTokenLifetime(cPtr, false);
  }

  public MegaTotpTokenGenResult() {
    this(megaJNI.new_MegaTotpTokenGenResult(), true);
  }

}
