/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaVpnCluster {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaVpnCluster(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaVpnCluster obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaVpnCluster obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaVpnCluster(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public String getHost() {
    return megaJNI.MegaVpnCluster_getHost(swigCPtr, this);
  }

  public MegaStringList getDns() {
    long cPtr = megaJNI.MegaVpnCluster_getDns(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaStringList(cPtr, false);
  }

  public MegaStringList getAdBlockingDns() {
    long cPtr = megaJNI.MegaVpnCluster_getAdBlockingDns(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaStringList(cPtr, false);
  }

   MegaVpnCluster copy() {
    long cPtr = megaJNI.MegaVpnCluster_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaVpnCluster(cPtr, false);
  }

}
