/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaSync {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaSync(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaSync obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaSync obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaSync(swigCPtr);
      }
      swigCPtr = 0;
    }
}

   MegaSync copy() {
    long cPtr = megaJNI.MegaSync_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaSync(cPtr, true);
  }

  public long getMegaHandle() {
    return megaJNI.MegaSync_getMegaHandle(swigCPtr, this);
  }

  public String getLocalFolder() {
    return megaJNI.MegaSync_getLocalFolder(swigCPtr, this);
  }

  public String getName() {
    return megaJNI.MegaSync_getName(swigCPtr, this);
  }

  public String getLastKnownMegaFolder() {
    return megaJNI.MegaSync_getLastKnownMegaFolder(swigCPtr, this);
  }

  public long getBackupId() {
    return megaJNI.MegaSync_getBackupId(swigCPtr, this);
  }

  public int getError() {
    return megaJNI.MegaSync_getError(swigCPtr, this);
  }

  public int getWarning() {
    return megaJNI.MegaSync_getWarning(swigCPtr, this);
  }

  public int getType() {
    return megaJNI.MegaSync_getType(swigCPtr, this);
  }

  public int getRunState() {
    return megaJNI.MegaSync_getRunState(swigCPtr, this);
  }

  public String getMegaSyncErrorCode() {
    return megaJNI.MegaSync_getMegaSyncErrorCode__SWIG_0(swigCPtr, this);
  }

  public static String getMegaSyncErrorCode(int errorCode) {
    return megaJNI.MegaSync_getMegaSyncErrorCode__SWIG_1(errorCode);
  }

  public String getMegaSyncWarningCode() {
    return megaJNI.MegaSync_getMegaSyncWarningCode__SWIG_0(swigCPtr, this);
  }

  public static String getMegaSyncWarningCode(int warningCode) {
    return megaJNI.MegaSync_getMegaSyncWarningCode__SWIG_1(warningCode);
  }

  public MegaSync() {
    this(megaJNI.new_MegaSync(), true);
  }

  public final static class Error {
    public final static MegaSync.Error NO_SYNC_ERROR = new MegaSync.Error("NO_SYNC_ERROR", 0);
    public final static MegaSync.Error UNKNOWN_ERROR = new MegaSync.Error("UNKNOWN_ERROR", 1);
    public final static MegaSync.Error UNSUPPORTED_FILE_SYSTEM = new MegaSync.Error("UNSUPPORTED_FILE_SYSTEM", 2);
    public final static MegaSync.Error INVALID_REMOTE_TYPE = new MegaSync.Error("INVALID_REMOTE_TYPE", 3);
    public final static MegaSync.Error INVALID_LOCAL_TYPE = new MegaSync.Error("INVALID_LOCAL_TYPE", 4);
    public final static MegaSync.Error INITIAL_SCAN_FAILED = new MegaSync.Error("INITIAL_SCAN_FAILED", 5);
    public final static MegaSync.Error LOCAL_PATH_TEMPORARY_UNAVAILABLE = new MegaSync.Error("LOCAL_PATH_TEMPORARY_UNAVAILABLE", 6);
    public final static MegaSync.Error LOCAL_PATH_UNAVAILABLE = new MegaSync.Error("LOCAL_PATH_UNAVAILABLE", 7);
    public final static MegaSync.Error REMOTE_NODE_NOT_FOUND = new MegaSync.Error("REMOTE_NODE_NOT_FOUND", 8);
    public final static MegaSync.Error STORAGE_OVERQUOTA = new MegaSync.Error("STORAGE_OVERQUOTA", 9);
    public final static MegaSync.Error ACCOUNT_EXPIRED = new MegaSync.Error("ACCOUNT_EXPIRED", 10);
    public final static MegaSync.Error FOREIGN_TARGET_OVERSTORAGE = new MegaSync.Error("FOREIGN_TARGET_OVERSTORAGE", 11);
    public final static MegaSync.Error REMOTE_PATH_HAS_CHANGED = new MegaSync.Error("REMOTE_PATH_HAS_CHANGED", 12);
    public final static MegaSync.Error SHARE_NON_FULL_ACCESS = new MegaSync.Error("SHARE_NON_FULL_ACCESS", 14);
    public final static MegaSync.Error LOCAL_FILESYSTEM_MISMATCH = new MegaSync.Error("LOCAL_FILESYSTEM_MISMATCH", 15);
    public final static MegaSync.Error PUT_NODES_ERROR = new MegaSync.Error("PUT_NODES_ERROR", 16);
    public final static MegaSync.Error ACTIVE_SYNC_BELOW_PATH = new MegaSync.Error("ACTIVE_SYNC_BELOW_PATH", 17);
    public final static MegaSync.Error ACTIVE_SYNC_ABOVE_PATH = new MegaSync.Error("ACTIVE_SYNC_ABOVE_PATH", 18);
    public final static MegaSync.Error REMOTE_NODE_MOVED_TO_RUBBISH = new MegaSync.Error("REMOTE_NODE_MOVED_TO_RUBBISH", 19);
    public final static MegaSync.Error REMOTE_NODE_INSIDE_RUBBISH = new MegaSync.Error("REMOTE_NODE_INSIDE_RUBBISH", 20);
    public final static MegaSync.Error VBOXSHAREDFOLDER_UNSUPPORTED = new MegaSync.Error("VBOXSHAREDFOLDER_UNSUPPORTED", 21);
    public final static MegaSync.Error LOCAL_PATH_SYNC_COLLISION = new MegaSync.Error("LOCAL_PATH_SYNC_COLLISION", 22);
    public final static MegaSync.Error ACCOUNT_BLOCKED = new MegaSync.Error("ACCOUNT_BLOCKED", 23);
    public final static MegaSync.Error UNKNOWN_TEMPORARY_ERROR = new MegaSync.Error("UNKNOWN_TEMPORARY_ERROR", 24);
    public final static MegaSync.Error TOO_MANY_ACTION_PACKETS = new MegaSync.Error("TOO_MANY_ACTION_PACKETS", 25);
    public final static MegaSync.Error LOGGED_OUT = new MegaSync.Error("LOGGED_OUT", 26);
    public final static MegaSync.Error BACKUP_MODIFIED = new MegaSync.Error("BACKUP_MODIFIED", 29);
    public final static MegaSync.Error BACKUP_SOURCE_NOT_BELOW_DRIVE = new MegaSync.Error("BACKUP_SOURCE_NOT_BELOW_DRIVE", 30);
    public final static MegaSync.Error SYNC_CONFIG_WRITE_FAILURE = new MegaSync.Error("SYNC_CONFIG_WRITE_FAILURE", 31);
    public final static MegaSync.Error ACTIVE_SYNC_SAME_PATH = new MegaSync.Error("ACTIVE_SYNC_SAME_PATH", 32);
    public final static MegaSync.Error COULD_NOT_MOVE_CLOUD_NODES = new MegaSync.Error("COULD_NOT_MOVE_CLOUD_NODES", 33);
    public final static MegaSync.Error COULD_NOT_CREATE_IGNORE_FILE = new MegaSync.Error("COULD_NOT_CREATE_IGNORE_FILE", 34);
    public final static MegaSync.Error SYNC_CONFIG_READ_FAILURE = new MegaSync.Error("SYNC_CONFIG_READ_FAILURE", 35);
    public final static MegaSync.Error UNKNOWN_DRIVE_PATH = new MegaSync.Error("UNKNOWN_DRIVE_PATH", 36);
    public final static MegaSync.Error INVALID_SCAN_INTERVAL = new MegaSync.Error("INVALID_SCAN_INTERVAL", 37);
    public final static MegaSync.Error NOTIFICATION_SYSTEM_UNAVAILABLE = new MegaSync.Error("NOTIFICATION_SYSTEM_UNAVAILABLE", 38);
    public final static MegaSync.Error UNABLE_TO_ADD_WATCH = new MegaSync.Error("UNABLE_TO_ADD_WATCH", 39);
    public final static MegaSync.Error UNABLE_TO_RETRIEVE_ROOT_FSID = new MegaSync.Error("UNABLE_TO_RETRIEVE_ROOT_FSID", 40);
    public final static MegaSync.Error UNABLE_TO_OPEN_DATABASE = new MegaSync.Error("UNABLE_TO_OPEN_DATABASE", 41);
    public final static MegaSync.Error INSUFFICIENT_DISK_SPACE = new MegaSync.Error("INSUFFICIENT_DISK_SPACE", 42);
    public final static MegaSync.Error FAILURE_ACCESSING_PERSISTENT_STORAGE = new MegaSync.Error("FAILURE_ACCESSING_PERSISTENT_STORAGE", 43);
    public final static MegaSync.Error MISMATCH_OF_ROOT_FSID = new MegaSync.Error("MISMATCH_OF_ROOT_FSID", 44);
    public final static MegaSync.Error FILESYSTEM_FILE_IDS_ARE_UNSTABLE = new MegaSync.Error("FILESYSTEM_FILE_IDS_ARE_UNSTABLE", 45);
    public final static MegaSync.Error FILESYSTEM_ID_UNAVAILABLE = new MegaSync.Error("FILESYSTEM_ID_UNAVAILABLE", 46);
    public final static MegaSync.Error UNABLE_TO_RETRIEVE_DEVICE_ID = new MegaSync.Error("UNABLE_TO_RETRIEVE_DEVICE_ID", 47);
    public final static MegaSync.Error LOCAL_PATH_MOUNTED = new MegaSync.Error("LOCAL_PATH_MOUNTED", 48);

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static Error swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + Error.class + " with value " + swigValue);
    }

    private Error(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private Error(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private Error(String swigName, Error swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static Error[] swigValues = { NO_SYNC_ERROR, UNKNOWN_ERROR, UNSUPPORTED_FILE_SYSTEM, INVALID_REMOTE_TYPE, INVALID_LOCAL_TYPE, INITIAL_SCAN_FAILED, LOCAL_PATH_TEMPORARY_UNAVAILABLE, LOCAL_PATH_UNAVAILABLE, REMOTE_NODE_NOT_FOUND, STORAGE_OVERQUOTA, ACCOUNT_EXPIRED, FOREIGN_TARGET_OVERSTORAGE, REMOTE_PATH_HAS_CHANGED, SHARE_NON_FULL_ACCESS, LOCAL_FILESYSTEM_MISMATCH, PUT_NODES_ERROR, ACTIVE_SYNC_BELOW_PATH, ACTIVE_SYNC_ABOVE_PATH, REMOTE_NODE_MOVED_TO_RUBBISH, REMOTE_NODE_INSIDE_RUBBISH, VBOXSHAREDFOLDER_UNSUPPORTED, LOCAL_PATH_SYNC_COLLISION, ACCOUNT_BLOCKED, UNKNOWN_TEMPORARY_ERROR, TOO_MANY_ACTION_PACKETS, LOGGED_OUT, BACKUP_MODIFIED, BACKUP_SOURCE_NOT_BELOW_DRIVE, SYNC_CONFIG_WRITE_FAILURE, ACTIVE_SYNC_SAME_PATH, COULD_NOT_MOVE_CLOUD_NODES, COULD_NOT_CREATE_IGNORE_FILE, SYNC_CONFIG_READ_FAILURE, UNKNOWN_DRIVE_PATH, INVALID_SCAN_INTERVAL, NOTIFICATION_SYSTEM_UNAVAILABLE, UNABLE_TO_ADD_WATCH, UNABLE_TO_RETRIEVE_ROOT_FSID, UNABLE_TO_OPEN_DATABASE, INSUFFICIENT_DISK_SPACE, FAILURE_ACCESSING_PERSISTENT_STORAGE, MISMATCH_OF_ROOT_FSID, FILESYSTEM_FILE_IDS_ARE_UNSTABLE, FILESYSTEM_ID_UNAVAILABLE, UNABLE_TO_RETRIEVE_DEVICE_ID, LOCAL_PATH_MOUNTED };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

  public final static class Warning {
    public final static MegaSync.Warning NO_SYNC_WARNING = new MegaSync.Warning("NO_SYNC_WARNING", 0);
    public final static MegaSync.Warning LOCAL_IS_FAT = new MegaSync.Warning("LOCAL_IS_FAT", 1);
    public final static MegaSync.Warning LOCAL_IS_HGFS = new MegaSync.Warning("LOCAL_IS_HGFS", 2);

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static Warning swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + Warning.class + " with value " + swigValue);
    }

    private Warning(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private Warning(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private Warning(String swigName, Warning swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static Warning[] swigValues = { NO_SYNC_WARNING, LOCAL_IS_FAT, LOCAL_IS_HGFS };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

  public final static class SyncType {
    public final static MegaSync.SyncType TYPE_UNKNOWN = new MegaSync.SyncType("TYPE_UNKNOWN", 0);
    public final static MegaSync.SyncType TYPE_TWOWAY = new MegaSync.SyncType("TYPE_TWOWAY", 3);
    public final static MegaSync.SyncType TYPE_BACKUP = new MegaSync.SyncType("TYPE_BACKUP");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static SyncType swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + SyncType.class + " with value " + swigValue);
    }

    private SyncType(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private SyncType(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private SyncType(String swigName, SyncType swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static SyncType[] swigValues = { TYPE_UNKNOWN, TYPE_TWOWAY, TYPE_BACKUP };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

  public final static class SyncRunningState {
    public final static MegaSync.SyncRunningState RUNSTATE_PENDING = new MegaSync.SyncRunningState("RUNSTATE_PENDING", 0);
    public final static MegaSync.SyncRunningState RUNSTATE_LOADING = new MegaSync.SyncRunningState("RUNSTATE_LOADING", 1);
    public final static MegaSync.SyncRunningState RUNSTATE_RUNNING = new MegaSync.SyncRunningState("RUNSTATE_RUNNING", 2);
    public final static MegaSync.SyncRunningState RUNSTATE_SUSPENDED = new MegaSync.SyncRunningState("RUNSTATE_SUSPENDED", 4);
    public final static MegaSync.SyncRunningState RUNSTATE_DISABLED = new MegaSync.SyncRunningState("RUNSTATE_DISABLED", 5);

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static SyncRunningState swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + SyncRunningState.class + " with value " + swigValue);
    }

    private SyncRunningState(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private SyncRunningState(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private SyncRunningState(String swigName, SyncRunningState swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static SyncRunningState[] swigValues = { RUNSTATE_PENDING, RUNSTATE_LOADING, RUNSTATE_RUNNING, RUNSTATE_SUSPENDED, RUNSTATE_DISABLED };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
