/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaUser {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaUser(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaUser obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaUser obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaUser(swigCPtr);
      }
      swigCPtr = 0;
    }
}

   MegaUser copy() {
    long cPtr = megaJNI.MegaUser_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaUser(cPtr, true);
  }

  public String getEmail() {
    return megaJNI.MegaUser_getEmail(swigCPtr, this);
  }

  public long getHandle() {
    return megaJNI.MegaUser_getHandle(swigCPtr, this);
  }

  public int getVisibility() {
    return megaJNI.MegaUser_getVisibility(swigCPtr, this);
  }

  public long getTimestamp() {
    return megaJNI.MegaUser_getTimestamp(swigCPtr, this);
  }

  public boolean hasChanged(long changeType) {
    return megaJNI.MegaUser_hasChanged(swigCPtr, this, changeType);
  }

  public long getChanges() {
    return megaJNI.MegaUser_getChanges(swigCPtr, this);
  }

  public int isOwnChange() {
    return megaJNI.MegaUser_isOwnChange(swigCPtr, this);
  }

  /*
  * Manually injected constants resolved the uint64_t overflow issue.
  */
  public final static long CHANGE_TYPE_RECENT_CLEAR_TIMESTAMP = 0x100000000L;
  
  public MegaUser() {
    this(megaJNI.new_MegaUser(), true);
  }

  public final static int VISIBILITY_UNKNOWN = -1;
  public final static int VISIBILITY_HIDDEN = 0;
  public final static int VISIBILITY_VISIBLE = 1;
  public final static int VISIBILITY_INACTIVE = 2;
  public final static int VISIBILITY_BLOCKED = 3;

  public final static int CHANGE_TYPE_AUTHRING = 1;
  public final static int CHANGE_TYPE_LSTINT = 2;
  public final static int CHANGE_TYPE_AVATAR = 4;
  public final static int CHANGE_TYPE_FIRSTNAME = 8;
  public final static int CHANGE_TYPE_LASTNAME = 16;
  public final static int CHANGE_TYPE_EMAIL = 32;
  public final static int CHANGE_TYPE_KEYRING = 64;
  public final static int CHANGE_TYPE_COUNTRY = 128;
  public final static int CHANGE_TYPE_BIRTHDAY = 256;
  public final static int CHANGE_TYPE_PUBKEY_CU255 = 512;
  public final static int CHANGE_TYPE_PUBKEY_ED255 = 1024;
  public final static int CHANGE_TYPE_SIG_PUBKEY_RSA = 2048;
  public final static int CHANGE_TYPE_SIG_PUBKEY_CU255 = 4096;
  public final static int CHANGE_TYPE_LANGUAGE = 8192;
  public final static int CHANGE_TYPE_PWD_REMINDER = 16384;
  public final static int CHANGE_TYPE_DISABLE_VERSIONS = 32768;
  public final static int CHANGE_TYPE_CONTACT_LINK_VERIFICATION = 65536;
  public final static int CHANGE_TYPE_RICH_PREVIEWS = 131072;
  public final static int CHANGE_TYPE_RUBBISH_TIME = 262144;
  public final static int CHANGE_TYPE_STORAGE_STATE = 524288;
  public final static int CHANGE_TYPE_GEOLOCATION = 1048576;
  public final static int CHANGE_TYPE_CAMERA_UPLOADS_FOLDER = 2097152;
  public final static int CHANGE_TYPE_MY_CHAT_FILES_FOLDER = 4194304;
  public final static int CHANGE_TYPE_PUSH_SETTINGS = 8388608;
  public final static int CHANGE_TYPE_ALIAS = 16777216;
  public final static int CHANGE_TYPE_UNSHAREABLE_KEY = 33554432;
  public final static int CHANGE_TYPE_DEVICE_NAMES = 67108864;
  public final static int CHANGE_TYPE_MY_BACKUPS_FOLDER = 134217728;
  public final static int CHANGE_TYPE_COOKIE_SETTINGS = 268435456;
  public final static int CHANGE_TYPE_NO_CALLKIT = 536870912;
  public final static int CHANGE_APPS_PREFS = 1073741824;
  public final static int CHANGE_CC_PREFS = 0x80000000;

}
