/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaStringTable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaStringTable(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaStringTable obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaStringTable obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaStringTable(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public static MegaStringTable createInstance() {
    long cPtr = megaJNI.MegaStringTable_createInstance();
    return (cPtr == 0) ? null : new MegaStringTable(cPtr, false);
  }

   MegaStringTable copy() {
    long cPtr = megaJNI.MegaStringTable_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaStringTable(cPtr, false);
  }

  public void append(MegaStringList value) {
    megaJNI.MegaStringTable_append(swigCPtr, this, MegaStringList.getCPtr(value), value);
  }

  public MegaStringList get(int i) {
    long cPtr = megaJNI.MegaStringTable_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new MegaStringList(cPtr, false);
  }

  public int size() {
    return megaJNI.MegaStringTable_size(swigCPtr, this);
  }

}
