/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaBackgroundMediaUpload {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaBackgroundMediaUpload(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaBackgroundMediaUpload obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaBackgroundMediaUpload obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaBackgroundMediaUpload(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public static MegaBackgroundMediaUpload createInstance(MegaApi api) {
    long cPtr = megaJNI.MegaBackgroundMediaUpload_createInstance(MegaApi.getCPtr(api), api);
    return (cPtr == 0) ? null : new MegaBackgroundMediaUpload(cPtr, false);
  }

  public boolean analyseMediaInfo(String inputFilepath) {
    return megaJNI.MegaBackgroundMediaUpload_analyseMediaInfo(swigCPtr, this, inputFilepath);
  }

  public String encryptFile(String inputFilepath, long startPos, SWIGTYPE_p_long_long length, String outputFilepath, boolean adjustsizeonly) {
    return megaJNI.MegaBackgroundMediaUpload_encryptFile(swigCPtr, this, inputFilepath, startPos, SWIGTYPE_p_long_long.getCPtr(length), outputFilepath, adjustsizeonly);
  }

  public String getUploadURL() {
    return megaJNI.MegaBackgroundMediaUpload_getUploadURL(swigCPtr, this);
  }

  public void setThumbnail(long h) {
    megaJNI.MegaBackgroundMediaUpload_setThumbnail(swigCPtr, this, h);
  }

  public void setPreview(long h) {
    megaJNI.MegaBackgroundMediaUpload_setPreview(swigCPtr, this, h);
  }

  public void setCoordinates(double latitude, double longitude, boolean unshareable) {
    megaJNI.MegaBackgroundMediaUpload_setCoordinates(swigCPtr, this, latitude, longitude, unshareable);
  }

  public String serialize() {
    return megaJNI.MegaBackgroundMediaUpload_serialize(swigCPtr, this);
  }

  public static MegaBackgroundMediaUpload unserialize(String data, MegaApi api) {
    long cPtr = megaJNI.MegaBackgroundMediaUpload_unserialize(data, MegaApi.getCPtr(api), api);
    return (cPtr == 0) ? null : new MegaBackgroundMediaUpload(cPtr, false);
  }

}
