/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaNodeTree {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaNodeTree(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaNodeTree obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaNodeTree obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaNodeTree(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public static MegaNodeTree createInstance(MegaNodeTree nodeTreeChild, String name, String s4AttributeValue, MegaCompleteUploadData completeUploadData, long sourceHandle) {
    long cPtr = megaJNI.MegaNodeTree_createInstance__SWIG_0(MegaNodeTree.getCPtr(nodeTreeChild), nodeTreeChild, name, s4AttributeValue, MegaCompleteUploadData.getCPtr(completeUploadData), completeUploadData, sourceHandle);
    return (cPtr == 0) ? null : new MegaNodeTree(cPtr, false);
  }

  public static MegaNodeTree createInstance(MegaNodeTree nodeTreeChild, String name, String s4AttributeValue, MegaCompleteUploadData completeUploadData) {
    long cPtr = megaJNI.MegaNodeTree_createInstance__SWIG_1(MegaNodeTree.getCPtr(nodeTreeChild), nodeTreeChild, name, s4AttributeValue, MegaCompleteUploadData.getCPtr(completeUploadData), completeUploadData);
    return (cPtr == 0) ? null : new MegaNodeTree(cPtr, false);
  }

  public MegaNodeTree getNodeTreeChild() {
    long cPtr = megaJNI.MegaNodeTree_getNodeTreeChild(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaNodeTree(cPtr, false);
  }

  public long getNodeHandle() {
    return megaJNI.MegaNodeTree_getNodeHandle(swigCPtr, this);
  }

   MegaNodeTree copy() {
    long cPtr = megaJNI.MegaNodeTree_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaNodeTree(cPtr, false);
  }

}
