/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaEvent {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaEvent obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
}

   MegaEvent copy() {
    long cPtr = megaJNI.MegaEvent_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaEvent(cPtr, true);
  }

  public int getType() {
    return megaJNI.MegaEvent_getType(swigCPtr, this);
  }

  public String getText() {
    return megaJNI.MegaEvent_getText(swigCPtr, this);
  }

  public long getNumber() {
    return megaJNI.MegaEvent_getNumber__SWIG_0(swigCPtr, this);
  }

  public long getHandle() {
    return megaJNI.MegaEvent_getHandle(swigCPtr, this);
  }

  public String getEventString() {
    return megaJNI.MegaEvent_getEventString(swigCPtr, this);
  }

  public SWIGTYPE_p_std__optionalT_long_long_t getNumber(String key) {
    return new SWIGTYPE_p_std__optionalT_long_long_t(megaJNI.MegaEvent_getNumber__SWIG_1(swigCPtr, this, key), true);
  }

  public MegaEvent() {
    this(megaJNI.new_MegaEvent(), true);
  }

  public final static int EVENT_COMMIT_DB = 0;
  public final static int EVENT_ACCOUNT_CONFIRMATION = 1;
  public final static int EVENT_CHANGE_TO_HTTPS = 2;
  public final static int EVENT_DISCONNECT = 3;
  public final static int EVENT_ACCOUNT_BLOCKED = 4;
  public final static int EVENT_STORAGE = 5;
  public final static int EVENT_NODES_CURRENT = 6;
  public final static int EVENT_MEDIA_INFO_READY = 7;
  public final static int EVENT_STORAGE_SUM_CHANGED = 8;
  public final static int EVENT_BUSINESS_STATUS = 9;
  public final static int EVENT_KEY_MODIFIED = 10;
  public final static int EVENT_MISC_FLAGS_READY = 11;
  public final static int EVENT_SYNCS_DISABLED = 13;
  public final static int EVENT_SYNCS_RESTORED = 14;
  public final static int EVENT_REQSTAT_PROGRESS = 15;
  public final static int EVENT_RELOADING = 16;
  public final static int EVENT_FATAL_ERROR = 17;
  public final static int EVENT_UPGRADE_SECURITY = 18;
  public final static int EVENT_DOWNGRADE_ATTACK = 19;
  public final static int EVENT_CONFIRM_USER_EMAIL = 20;
  public final static int EVENT_CREDIT_CARD_EXPIRY = 21;
  public final static int EVENT_NETWORK_ACTIVITY = 22;

  public final static int REASON_ERROR_UNKNOWN = -1;
  public final static int REASON_ERROR_NO_ERROR = 0;
  public final static int REASON_ERROR_FAILURE_UNSERIALIZE_NODE = 1;
  public final static int REASON_ERROR_DB_IO_FAILURE = 2;
  public final static int REASON_ERROR_DB_FULL = 3;
  public final static int REASON_ERROR_DB_INDEX_OVERFLOW = 4;
  public final static int REASON_ERROR_NO_JSCD = 5;
  public final static int REASON_ERROR_REGENERATE_JSCD = 6;
  public final static int REASON_ERROR_DB_CORRUPT = 7;

  public final static class NetworkActivityChannel {
    public final static MegaEvent.NetworkActivityChannel SC = new MegaEvent.NetworkActivityChannel("SC", 0);
    public final static MegaEvent.NetworkActivityChannel CS = new MegaEvent.NetworkActivityChannel("CS", 1);

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static NetworkActivityChannel swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + NetworkActivityChannel.class + " with value " + swigValue);
    }

    private NetworkActivityChannel(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private NetworkActivityChannel(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private NetworkActivityChannel(String swigName, NetworkActivityChannel swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static NetworkActivityChannel[] swigValues = { SC, CS };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

  public final static class NetworkActivityType {
    public final static MegaEvent.NetworkActivityType REQUEST_SENT = new MegaEvent.NetworkActivityType("REQUEST_SENT", 0);
    public final static MegaEvent.NetworkActivityType REQUEST_RECEIVED = new MegaEvent.NetworkActivityType("REQUEST_RECEIVED", 1);
    public final static MegaEvent.NetworkActivityType REQUEST_ERROR = new MegaEvent.NetworkActivityType("REQUEST_ERROR", 2);

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static NetworkActivityType swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + NetworkActivityType.class + " with value " + swigValue);
    }

    private NetworkActivityType(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private NetworkActivityType(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private NetworkActivityType(String swigName, NetworkActivityType swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static NetworkActivityType[] swigValues = { REQUEST_SENT, REQUEST_RECEIVED, REQUEST_ERROR };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
