/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaRecentActionBucket {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaRecentActionBucket(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaRecentActionBucket obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaRecentActionBucket obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaRecentActionBucket(swigCPtr);
      }
      swigCPtr = 0;
    }
}

   MegaRecentActionBucket copy() {
    long cPtr = megaJNI.MegaRecentActionBucket_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaRecentActionBucket(cPtr, true);
  }

  public long getTimestamp() {
    return megaJNI.MegaRecentActionBucket_getTimestamp(swigCPtr, this);
  }

  public String getUserEmail() {
    return megaJNI.MegaRecentActionBucket_getUserEmail(swigCPtr, this);
  }

  public long getParentHandle() {
    return megaJNI.MegaRecentActionBucket_getParentHandle(swigCPtr, this);
  }

  public boolean isUpdate() {
    return megaJNI.MegaRecentActionBucket_isUpdate(swigCPtr, this);
  }

  public boolean isMedia() {
    return megaJNI.MegaRecentActionBucket_isMedia(swigCPtr, this);
  }

  public MegaNodeList getNodes() {
    long cPtr = megaJNI.MegaRecentActionBucket_getNodes(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaNodeList(cPtr, false);
  }

  public MegaRecentActionBucket() {
    this(megaJNI.new_MegaRecentActionBucket(), true);
  }

}
