/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaSearchFilter {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaSearchFilter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaSearchFilter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaSearchFilter obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaSearchFilter(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public static MegaSearchFilter createInstance() {
    long cPtr = megaJNI.MegaSearchFilter_createInstance();
    return (cPtr == 0) ? null : new MegaSearchFilter(cPtr, false);
  }

   MegaSearchFilter copy() {
    long cPtr = megaJNI.MegaSearchFilter_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaSearchFilter(cPtr, false);
  }

  public void byName(String searchString) {
    megaJNI.MegaSearchFilter_byName__SWIG_0(swigCPtr, this, searchString);
  }

  public void byNodeType(int nodeType) {
    megaJNI.MegaSearchFilter_byNodeType__SWIG_0(swigCPtr, this, nodeType);
  }

  public void byCategory(int mimeType) {
    megaJNI.MegaSearchFilter_byCategory__SWIG_0(swigCPtr, this, mimeType);
  }

  public void byFavourite(int boolFilterOption) {
    megaJNI.MegaSearchFilter_byFavourite__SWIG_0(swigCPtr, this, boolFilterOption);
  }

  public void bySensitivity(int boolFilterOption) {
    megaJNI.MegaSearchFilter_bySensitivity__SWIG_0(swigCPtr, this, boolFilterOption);
  }

  public void byLocationHandle(long ancestorHandle) {
    megaJNI.MegaSearchFilter_byLocationHandle__SWIG_0(swigCPtr, this, ancestorHandle);
  }

  public void byLocation(int locationType) {
    megaJNI.MegaSearchFilter_byLocation__SWIG_0(swigCPtr, this, locationType);
  }

  public void byCreationTime(long lowerLimit, long upperLimit) {
    megaJNI.MegaSearchFilter_byCreationTime(swigCPtr, this, lowerLimit, upperLimit);
  }

  public void byModificationTime(long lowerLimit, long upperLimit) {
    megaJNI.MegaSearchFilter_byModificationTime(swigCPtr, this, lowerLimit, upperLimit);
  }

  public void byDescription(String searchString) {
    megaJNI.MegaSearchFilter_byDescription__SWIG_0(swigCPtr, this, searchString);
  }

  public void byTag(String searchString) {
    megaJNI.MegaSearchFilter_byTag__SWIG_0(swigCPtr, this, searchString);
  }

  public void useAndForTextQuery(boolean useAnd) {
    megaJNI.MegaSearchFilter_useAndForTextQuery__SWIG_0(swigCPtr, this, useAnd);
  }

  public String byName() {
    return megaJNI.MegaSearchFilter_byName__SWIG_1(swigCPtr, this);
  }

  public int byNodeType() {
    return megaJNI.MegaSearchFilter_byNodeType__SWIG_1(swigCPtr, this);
  }

  public int byCategory() {
    return megaJNI.MegaSearchFilter_byCategory__SWIG_1(swigCPtr, this);
  }

  public int byFavourite() {
    return megaJNI.MegaSearchFilter_byFavourite__SWIG_1(swigCPtr, this);
  }

  public int bySensitivity() {
    return megaJNI.MegaSearchFilter_bySensitivity__SWIG_1(swigCPtr, this);
  }

  public long byLocationHandle() {
    return megaJNI.MegaSearchFilter_byLocationHandle__SWIG_1(swigCPtr, this);
  }

  public int byLocation() {
    return megaJNI.MegaSearchFilter_byLocation__SWIG_1(swigCPtr, this);
  }

  public long byCreationTimeLowerLimit() {
    return megaJNI.MegaSearchFilter_byCreationTimeLowerLimit(swigCPtr, this);
  }

  public long byCreationTimeUpperLimit() {
    return megaJNI.MegaSearchFilter_byCreationTimeUpperLimit(swigCPtr, this);
  }

  public long byModificationTimeLowerLimit() {
    return megaJNI.MegaSearchFilter_byModificationTimeLowerLimit(swigCPtr, this);
  }

  public long byModificationTimeUpperLimit() {
    return megaJNI.MegaSearchFilter_byModificationTimeUpperLimit(swigCPtr, this);
  }

  public String byDescription() {
    return megaJNI.MegaSearchFilter_byDescription__SWIG_1(swigCPtr, this);
  }

  public String byTag() {
    return megaJNI.MegaSearchFilter_byTag__SWIG_1(swigCPtr, this);
  }

  public boolean useAndForTextQuery() {
    return megaJNI.MegaSearchFilter_useAndForTextQuery__SWIG_1(swigCPtr, this);
  }

  public final static int BOOL_FILTER_DISABLED = 0;
  public final static int BOOL_FILTER_ONLY_TRUE = BOOL_FILTER_DISABLED + 1;
  public final static int BOOL_FILTER_ONLY_FALSE = BOOL_FILTER_ONLY_TRUE + 1;

}
