/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaDiscountCodeInfo extends MegaDiscountCode {
  private transient long swigCPtr;

  protected MegaDiscountCodeInfo(long cPtr, boolean cMemoryOwn) {
    super(megaJNI.MegaDiscountCodeInfo_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaDiscountCodeInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaDiscountCodeInfo obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaDiscountCodeInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

   MegaDiscountCode copy() {
    long cPtr = megaJNI.MegaDiscountCodeInfo_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaDiscountCodeInfo(cPtr, false);
  }

  public int getExpiry() {
    return megaJNI.MegaDiscountCodeInfo_getExpiry(swigCPtr, this);
  }

  public int getCompulsorySubscription() {
    return megaJNI.MegaDiscountCodeInfo_getCompulsorySubscription(swigCPtr, this);
  }

  public int getMultiDiscount() {
    return megaJNI.MegaDiscountCodeInfo_getMultiDiscount(swigCPtr, this);
  }

  public MegaStringIntegerMap getFeatures() {
    long cPtr = megaJNI.MegaDiscountCodeInfo_getFeatures(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaStringIntegerMap(cPtr, false);
  }

  public int getTaxValue() {
    return megaJNI.MegaDiscountCodeInfo_getTaxValue(swigCPtr, this);
  }

  public boolean isTaxExempt() {
    return megaJNI.MegaDiscountCodeInfo_isTaxExempt(swigCPtr, this);
  }

  public boolean isTaxAppliedOnTop() {
    return megaJNI.MegaDiscountCodeInfo_isTaxAppliedOnTop(swigCPtr, this);
  }

  public int getTaxRate() {
    return megaJNI.MegaDiscountCodeInfo_getTaxRate(swigCPtr, this);
  }

  public String getTaxName() {
    return megaJNI.MegaDiscountCodeInfo_getTaxName(swigCPtr, this);
  }

  public String getTaxCountry() {
    return megaJNI.MegaDiscountCodeInfo_getTaxCountry(swigCPtr, this);
  }

  public double getEuroTotalPrice() {
    return megaJNI.MegaDiscountCodeInfo_getEuroTotalPrice(swigCPtr, this);
  }

  public double getEuroDiscountAmount() {
    return megaJNI.MegaDiscountCodeInfo_getEuroDiscountAmount(swigCPtr, this);
  }

  public double getEuroDiscountedTotalPrice() {
    return megaJNI.MegaDiscountCodeInfo_getEuroDiscountedTotalPrice(swigCPtr, this);
  }

  public double getEuroDiscountedMonthlyPrice() {
    return megaJNI.MegaDiscountCodeInfo_getEuroDiscountedMonthlyPrice(swigCPtr, this);
  }

  public double getEuroTotalPriceNet() {
    return megaJNI.MegaDiscountCodeInfo_getEuroTotalPriceNet(swigCPtr, this);
  }

  public double getEuroDiscountAmountNet() {
    return megaJNI.MegaDiscountCodeInfo_getEuroDiscountAmountNet(swigCPtr, this);
  }

  public double getEuroDiscountedTotalPriceNet() {
    return megaJNI.MegaDiscountCodeInfo_getEuroDiscountedTotalPriceNet(swigCPtr, this);
  }

  public double getEuroDiscountedMonthlyPriceNet() {
    return megaJNI.MegaDiscountCodeInfo_getEuroDiscountedMonthlyPriceNet(swigCPtr, this);
  }

  public String getLocalCurrencyCode() {
    return megaJNI.MegaDiscountCodeInfo_getLocalCurrencyCode(swigCPtr, this);
  }

  public String getLocalCurrencySymbol() {
    return megaJNI.MegaDiscountCodeInfo_getLocalCurrencySymbol(swigCPtr, this);
  }

  public double getLocalTotalPrice() {
    return megaJNI.MegaDiscountCodeInfo_getLocalTotalPrice(swigCPtr, this);
  }

  public double getLocalDiscountAmount() {
    return megaJNI.MegaDiscountCodeInfo_getLocalDiscountAmount(swigCPtr, this);
  }

  public double getLocalDiscountedTotalPrice() {
    return megaJNI.MegaDiscountCodeInfo_getLocalDiscountedTotalPrice(swigCPtr, this);
  }

  public double getLocalDiscountedMonthlyPrice() {
    return megaJNI.MegaDiscountCodeInfo_getLocalDiscountedMonthlyPrice(swigCPtr, this);
  }

  public double getLocalTotalPriceNet() {
    return megaJNI.MegaDiscountCodeInfo_getLocalTotalPriceNet(swigCPtr, this);
  }

  public double getLocalDiscountAmountNet() {
    return megaJNI.MegaDiscountCodeInfo_getLocalDiscountAmountNet(swigCPtr, this);
  }

  public double getLocalDiscountedTotalPriceNet() {
    return megaJNI.MegaDiscountCodeInfo_getLocalDiscountedTotalPriceNet(swigCPtr, this);
  }

  public double getLocalDiscountedMonthlyPriceNet() {
    return megaJNI.MegaDiscountCodeInfo_getLocalDiscountedMonthlyPriceNet(swigCPtr, this);
  }

}
