/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaBannerList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaBannerList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaBannerList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaBannerList obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaBannerList(swigCPtr);
      }
      swigCPtr = 0;
    }
}

   MegaBannerList copy() {
    long cPtr = megaJNI.MegaBannerList_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaBannerList(cPtr, false);
  }

  public MegaBanner get(int i) {
    long cPtr = megaJNI.MegaBannerList_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new MegaBanner(cPtr, false);
  }

  public int size() {
    return megaJNI.MegaBannerList_size(swigCPtr, this);
  }

}
