/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaPushNotificationSettings {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaPushNotificationSettings(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaPushNotificationSettings obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaPushNotificationSettings obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaPushNotificationSettings(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public static MegaPushNotificationSettings createInstance() {
    long cPtr = megaJNI.MegaPushNotificationSettings_createInstance();
    return (cPtr == 0) ? null : new MegaPushNotificationSettings(cPtr, false);
  }

   MegaPushNotificationSettings copy() {
    long cPtr = megaJNI.MegaPushNotificationSettings_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaPushNotificationSettings(cPtr, false);
  }

  public boolean isGlobalDndEnabled() {
    return megaJNI.MegaPushNotificationSettings_isGlobalDndEnabled(swigCPtr, this);
  }

  public boolean isGlobalChatsDndEnabled() {
    return megaJNI.MegaPushNotificationSettings_isGlobalChatsDndEnabled(swigCPtr, this);
  }

  public long getGlobalDnd() {
    return megaJNI.MegaPushNotificationSettings_getGlobalDnd(swigCPtr, this);
  }

  public boolean isGlobalScheduleEnabled() {
    return megaJNI.MegaPushNotificationSettings_isGlobalScheduleEnabled(swigCPtr, this);
  }

  public int getGlobalScheduleStart() {
    return megaJNI.MegaPushNotificationSettings_getGlobalScheduleStart(swigCPtr, this);
  }

  public int getGlobalScheduleEnd() {
    return megaJNI.MegaPushNotificationSettings_getGlobalScheduleEnd(swigCPtr, this);
  }

  public String getGlobalScheduleTimezone() {
    return megaJNI.MegaPushNotificationSettings_getGlobalScheduleTimezone(swigCPtr, this);
  }

  public boolean isChatDndEnabled(long chatid) {
    return megaJNI.MegaPushNotificationSettings_isChatDndEnabled(swigCPtr, this, chatid);
  }

  public long getChatDnd(long chatid) {
    return megaJNI.MegaPushNotificationSettings_getChatDnd(swigCPtr, this, chatid);
  }

  public boolean isChatAlwaysNotifyEnabled(long chatid) {
    return megaJNI.MegaPushNotificationSettings_isChatAlwaysNotifyEnabled(swigCPtr, this, chatid);
  }

  public boolean isContactsEnabled() {
    return megaJNI.MegaPushNotificationSettings_isContactsEnabled(swigCPtr, this);
  }

  public boolean isSharesEnabled() {
    return megaJNI.MegaPushNotificationSettings_isSharesEnabled(swigCPtr, this);
  }

  public long getGlobalChatsDnd() {
    return megaJNI.MegaPushNotificationSettings_getGlobalChatsDnd(swigCPtr, this);
  }

  public void enableGlobal(boolean enable) {
    megaJNI.MegaPushNotificationSettings_enableGlobal(swigCPtr, this, enable);
  }

  public void setGlobalDnd(long timestamp) {
    megaJNI.MegaPushNotificationSettings_setGlobalDnd(swigCPtr, this, timestamp);
  }

  public void disableGlobalDnd() {
    megaJNI.MegaPushNotificationSettings_disableGlobalDnd(swigCPtr, this);
  }

  public void setGlobalSchedule(int start, int end, String timezone) {
    megaJNI.MegaPushNotificationSettings_setGlobalSchedule(swigCPtr, this, start, end, timezone);
  }

  public void disableGlobalSchedule() {
    megaJNI.MegaPushNotificationSettings_disableGlobalSchedule(swigCPtr, this);
  }

  public void enableChat(long chatid, boolean enable) {
    megaJNI.MegaPushNotificationSettings_enableChat(swigCPtr, this, chatid, enable);
  }

  public void setChatDnd(long chatid, long timestamp) {
    megaJNI.MegaPushNotificationSettings_setChatDnd(swigCPtr, this, chatid, timestamp);
  }

  public void setGlobalChatsDnd(long timestamp) {
    megaJNI.MegaPushNotificationSettings_setGlobalChatsDnd(swigCPtr, this, timestamp);
  }

  public void enableChatAlwaysNotify(long chatid, boolean enable) {
    megaJNI.MegaPushNotificationSettings_enableChatAlwaysNotify(swigCPtr, this, chatid, enable);
  }

  public void enableContacts(boolean enable) {
    megaJNI.MegaPushNotificationSettings_enableContacts(swigCPtr, this, enable);
  }

  public void enableShares(boolean enable) {
    megaJNI.MegaPushNotificationSettings_enableShares(swigCPtr, this, enable);
  }

  public void enableChats(boolean enable) {
    megaJNI.MegaPushNotificationSettings_enableChats(swigCPtr, this, enable);
  }

}
