/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaNode {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaNode(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaNode obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaNode obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaNode(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  static public class CreditCardNodeData {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected CreditCardNodeData(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(CreditCardNodeData obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    protected static long swigRelease(CreditCardNodeData obj) {
      long ptr = 0;
      if (obj != null) {
        if (!obj.swigCMemOwn)
          throw new RuntimeException("Cannot release ownership as memory is not owned");
        ptr = obj.swigCPtr;
        obj.swigCMemOwn = false;
        obj.delete();
      }
      return ptr;
    }
  
    @SuppressWarnings({"deprecation", "removal"})
    protected void finalize() {
      delete();
    }
  
    protected synchronized void delete() {   
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          megaJNI.delete_MegaNode_CreditCardNodeData(swigCPtr);
        }
        swigCPtr = 0;
      }
  }
  
    public static MegaNode.CreditCardNodeData createInstance(String cardNumber, String notes, String cardHolderName, String cvv, String expirationDate) {
      long cPtr = megaJNI.MegaNode_CreditCardNodeData_createInstance(cardNumber, notes, cardHolderName, cvv, expirationDate);
      return (cPtr == 0) ? null : new MegaNode.CreditCardNodeData(cPtr, false);
    }
  
    public void setCardNumber(String cardNumber) {
      megaJNI.MegaNode_CreditCardNodeData_setCardNumber(swigCPtr, this, cardNumber);
    }
  
    public void setNotes(String notes) {
      megaJNI.MegaNode_CreditCardNodeData_setNotes(swigCPtr, this, notes);
    }
  
    public void setCardHolderName(String cardHolderName) {
      megaJNI.MegaNode_CreditCardNodeData_setCardHolderName(swigCPtr, this, cardHolderName);
    }
  
    public void setCvv(String cvv) {
      megaJNI.MegaNode_CreditCardNodeData_setCvv(swigCPtr, this, cvv);
    }
  
    public void setExpirationDate(String expirationDate) {
      megaJNI.MegaNode_CreditCardNodeData_setExpirationDate(swigCPtr, this, expirationDate);
    }
  
    public String cardNumber() {
      return megaJNI.MegaNode_CreditCardNodeData_cardNumber(swigCPtr, this);
    }
  
    public String notes() {
      return megaJNI.MegaNode_CreditCardNodeData_notes(swigCPtr, this);
    }
  
    public String cardHolderName() {
      return megaJNI.MegaNode_CreditCardNodeData_cardHolderName(swigCPtr, this);
    }
  
    public String cvv() {
      return megaJNI.MegaNode_CreditCardNodeData_cvv(swigCPtr, this);
    }
  
    public String expirationDate() {
      return megaJNI.MegaNode_CreditCardNodeData_expirationDate(swigCPtr, this);
    }
  
  }

  static public class PasswordNodeData {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected PasswordNodeData(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(PasswordNodeData obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    protected static long swigRelease(PasswordNodeData obj) {
      long ptr = 0;
      if (obj != null) {
        if (!obj.swigCMemOwn)
          throw new RuntimeException("Cannot release ownership as memory is not owned");
        ptr = obj.swigCPtr;
        obj.swigCMemOwn = false;
        obj.delete();
      }
      return ptr;
    }
  
    @SuppressWarnings({"deprecation", "removal"})
    protected void finalize() {
      delete();
    }
  
    protected synchronized void delete() {   
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          megaJNI.delete_MegaNode_PasswordNodeData(swigCPtr);
        }
        swigCPtr = 0;
      }
  }
  
      static public class TotpData {
        private transient long swigCPtr;
        protected transient boolean swigCMemOwn;
      
        protected TotpData(long cPtr, boolean cMemoryOwn) {
          swigCMemOwn = cMemoryOwn;
          swigCPtr = cPtr;
        }
      
        protected static long getCPtr(TotpData obj) {
          return (obj == null) ? 0 : obj.swigCPtr;
        }
      
        protected static long swigRelease(TotpData obj) {
          long ptr = 0;
          if (obj != null) {
            if (!obj.swigCMemOwn)
              throw new RuntimeException("Cannot release ownership as memory is not owned");
            ptr = obj.swigCPtr;
            obj.swigCMemOwn = false;
            obj.delete();
          }
          return ptr;
        }
      
        @SuppressWarnings({"deprecation", "removal"})
        protected void finalize() {
          delete();
        }
      
        protected synchronized void delete() {   
          if (swigCPtr != 0) {
            if (swigCMemOwn) {
              swigCMemOwn = false;
              megaJNI.delete_MegaNode_PasswordNodeData_TotpData(swigCPtr);
            }
            swigCPtr = 0;
          }
      }
      
            static public class Validation {
              private transient long swigCPtr;
              protected transient boolean swigCMemOwn;
            
              protected Validation(long cPtr, boolean cMemoryOwn) {
                swigCMemOwn = cMemoryOwn;
                swigCPtr = cPtr;
              }
            
              protected static long getCPtr(Validation obj) {
                return (obj == null) ? 0 : obj.swigCPtr;
              }
            
              protected static long swigRelease(Validation obj) {
                long ptr = 0;
                if (obj != null) {
                  if (!obj.swigCMemOwn)
                    throw new RuntimeException("Cannot release ownership as memory is not owned");
                  ptr = obj.swigCPtr;
                  obj.swigCMemOwn = false;
                  obj.delete();
                }
                return ptr;
              }
            
              @SuppressWarnings({"deprecation", "removal"})
              protected void finalize() {
                delete();
              }
            
              protected synchronized void delete() {   
                if (swigCPtr != 0) {
                  if (swigCMemOwn) {
                    swigCMemOwn = false;
                    megaJNI.delete_MegaNode_PasswordNodeData_TotpData_Validation(swigCPtr);
                  }
                  swigCPtr = 0;
                }
            }
            
              public boolean sharedSecretExist() {
                return megaJNI.MegaNode_PasswordNodeData_TotpData_Validation_sharedSecretExist(swigCPtr, this);
              }
            
              public boolean sharedSecretValid() {
                return megaJNI.MegaNode_PasswordNodeData_TotpData_Validation_sharedSecretValid(swigCPtr, this);
              }
            
              public boolean algorithmExist() {
                return megaJNI.MegaNode_PasswordNodeData_TotpData_Validation_algorithmExist(swigCPtr, this);
              }
            
              public boolean algorithmValid() {
                return megaJNI.MegaNode_PasswordNodeData_TotpData_Validation_algorithmValid(swigCPtr, this);
              }
            
              public boolean expirationTimeExist() {
                return megaJNI.MegaNode_PasswordNodeData_TotpData_Validation_expirationTimeExist(swigCPtr, this);
              }
            
              public boolean expirationTimeValid() {
                return megaJNI.MegaNode_PasswordNodeData_TotpData_Validation_expirationTimeValid(swigCPtr, this);
              }
            
              public boolean nDigitsExist() {
                return megaJNI.MegaNode_PasswordNodeData_TotpData_Validation_nDigitsExist(swigCPtr, this);
              }
            
              public boolean nDigitsValid() {
                return megaJNI.MegaNode_PasswordNodeData_TotpData_Validation_nDigitsValid(swigCPtr, this);
              }
            
              public boolean isValidForCreate() {
                return megaJNI.MegaNode_PasswordNodeData_TotpData_Validation_isValidForCreate(swigCPtr, this);
              }
            
              public boolean isValidForUpdate() {
                return megaJNI.MegaNode_PasswordNodeData_TotpData_Validation_isValidForUpdate(swigCPtr, this);
              }
            
            }
      
        public static MegaNode.PasswordNodeData.TotpData createRemovalInstance() {
          long cPtr = megaJNI.MegaNode_PasswordNodeData_TotpData_createRemovalInstance();
          return (cPtr == 0) ? null : new MegaNode.PasswordNodeData.TotpData(cPtr, false);
        }
      
        public static MegaNode.PasswordNodeData.TotpData createInstance(String sharedSecret, int expirationTimeSecs, int hashAlgorithm, int ndigits) {
          long cPtr = megaJNI.MegaNode_PasswordNodeData_TotpData_createInstance(sharedSecret, expirationTimeSecs, hashAlgorithm, ndigits);
          return (cPtr == 0) ? null : new MegaNode.PasswordNodeData.TotpData(cPtr, false);
        }
      
        public String sharedSecret() {
          return megaJNI.MegaNode_PasswordNodeData_TotpData_sharedSecret(swigCPtr, this);
        }
      
        public int expirationTime() {
          return megaJNI.MegaNode_PasswordNodeData_TotpData_expirationTime(swigCPtr, this);
        }
      
        public int hashAlgorithm() {
          return megaJNI.MegaNode_PasswordNodeData_TotpData_hashAlgorithm(swigCPtr, this);
        }
      
        public int nDigits() {
          return megaJNI.MegaNode_PasswordNodeData_TotpData_nDigits(swigCPtr, this);
        }
      
        public boolean markedToRemove() {
          return megaJNI.MegaNode_PasswordNodeData_TotpData_markedToRemove(swigCPtr, this);
        }
      
        public void setSharedSecret(String sharedSecret) {
          megaJNI.MegaNode_PasswordNodeData_TotpData_setSharedSecret(swigCPtr, this, sharedSecret);
        }
      
        public void setExpirationTime(int expirationTimeSecs) {
          megaJNI.MegaNode_PasswordNodeData_TotpData_setExpirationTime(swigCPtr, this, expirationTimeSecs);
        }
      
        public void setHashAlgorithm(int algorithm) {
          megaJNI.MegaNode_PasswordNodeData_TotpData_setHashAlgorithm(swigCPtr, this, algorithm);
        }
      
        public void setNdigits(int n) {
          megaJNI.MegaNode_PasswordNodeData_TotpData_setNdigits(swigCPtr, this, n);
        }
      
         MegaNode.PasswordNodeData.TotpData copy() {
          long cPtr = megaJNI.MegaNode_PasswordNodeData_TotpData_copy(swigCPtr, this);
          return (cPtr == 0) ? null : new MegaNode.PasswordNodeData.TotpData(cPtr, false);
        }
      
        public MegaNode.PasswordNodeData.TotpData.Validation getValidation() {
          long cPtr = megaJNI.MegaNode_PasswordNodeData_TotpData_getValidation(swigCPtr, this);
          return (cPtr == 0) ? null : new MegaNode.PasswordNodeData.TotpData.Validation(cPtr, false);
        }
      
        public final static int HASH_ALGO_SHA1 = 0;
        public final static int HASH_ALGO_SHA256 = 1;
        public final static int HASH_ALGO_SHA512 = 2;
      
        public final static int DEFAULT_HASH_ALGO = 0;
        public final static int DEFAULT_EXPIRATION_TIME_SECS = 30;
        public final static int DEFAULT_NDIGITS = 6;
        public final static int TOTPNULLOPT = -1;
      }
  
    public static MegaNode.PasswordNodeData createInstance(String pwd, String notes, String url, String userName, MegaNode.PasswordNodeData.TotpData totpData) {
      long cPtr = megaJNI.MegaNode_PasswordNodeData_createInstance(pwd, notes, url, userName, MegaNode.PasswordNodeData.TotpData.getCPtr(totpData), totpData);
      return (cPtr == 0) ? null : new MegaNode.PasswordNodeData(cPtr, true);
    }
  
    public void setTotpData(MegaNode.PasswordNodeData.TotpData totpData) {
      megaJNI.MegaNode_PasswordNodeData_setTotpData(swigCPtr, this, MegaNode.PasswordNodeData.TotpData.getCPtr(totpData), totpData);
    }
  
    public void setPassword(String pwd) {
      megaJNI.MegaNode_PasswordNodeData_setPassword(swigCPtr, this, pwd);
    }
  
    public void setNotes(String n) {
      megaJNI.MegaNode_PasswordNodeData_setNotes(swigCPtr, this, n);
    }
  
    public void setUrl(String u) {
      megaJNI.MegaNode_PasswordNodeData_setUrl(swigCPtr, this, u);
    }
  
    public void setUserName(String un) {
      megaJNI.MegaNode_PasswordNodeData_setUserName(swigCPtr, this, un);
    }
  
    public String password() {
      return megaJNI.MegaNode_PasswordNodeData_password(swigCPtr, this);
    }
  
    public String notes() {
      return megaJNI.MegaNode_PasswordNodeData_notes(swigCPtr, this);
    }
  
    public String url() {
      return megaJNI.MegaNode_PasswordNodeData_url(swigCPtr, this);
    }
  
    public String userName() {
      return megaJNI.MegaNode_PasswordNodeData_userName(swigCPtr, this);
    }
  
    public MegaNode.PasswordNodeData.TotpData totpData() {
      long cPtr = megaJNI.MegaNode_PasswordNodeData_totpData(swigCPtr, this);
      return (cPtr == 0) ? null : new MegaNode.PasswordNodeData.TotpData(cPtr, false);
    }
  
  }

  public static double getINVALID_COORDINATE() {
    return megaJNI.MegaNode_INVALID_COORDINATE_get();
  }

   MegaNode copy() {
    long cPtr = megaJNI.MegaNode_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaNode(cPtr, true);
  }

  public int getType() {
    return megaJNI.MegaNode_getType(swigCPtr, this);
  }

  public String getName() {
    return megaJNI.MegaNode_getName(swigCPtr, this);
  }

  public String getFingerprint() {
    return megaJNI.MegaNode_getFingerprint(swigCPtr, this);
  }

  public String getOriginalFingerprint() {
    return megaJNI.MegaNode_getOriginalFingerprint(swigCPtr, this);
  }

  public boolean hasCustomAttrs() {
    return megaJNI.MegaNode_hasCustomAttrs(swigCPtr, this);
  }

  public MegaStringList getCustomAttrNames() {
    long cPtr = megaJNI.MegaNode_getCustomAttrNames(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaStringList(cPtr, true);
  }

  public String getCustomAttr(String attrName) {
    return megaJNI.MegaNode_getCustomAttr(swigCPtr, this, attrName);
  }

  public int getDuration() {
    return megaJNI.MegaNode_getDuration(swigCPtr, this);
  }

  public int getWidth() {
    return megaJNI.MegaNode_getWidth(swigCPtr, this);
  }

  public int getHeight() {
    return megaJNI.MegaNode_getHeight(swigCPtr, this);
  }

  public int getShortformat() {
    return megaJNI.MegaNode_getShortformat(swigCPtr, this);
  }

  public int getVideocodecid() {
    return megaJNI.MegaNode_getVideocodecid(swigCPtr, this);
  }

  public boolean isFavourite() {
    return megaJNI.MegaNode_isFavourite(swigCPtr, this);
  }

  public boolean isMarkedSensitive() {
    return megaJNI.MegaNode_isMarkedSensitive(swigCPtr, this);
  }

  public int getLabel() {
    return megaJNI.MegaNode_getLabel(swigCPtr, this);
  }

  public double getLatitude() {
    return megaJNI.MegaNode_getLatitude(swigCPtr, this);
  }

  public double getLongitude() {
    return megaJNI.MegaNode_getLongitude(swigCPtr, this);
  }

  public String getDescription() {
    return megaJNI.MegaNode_getDescription(swigCPtr, this);
  }

  public MegaStringList getTags() {
    long cPtr = megaJNI.MegaNode_getTags(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaStringList(cPtr, true);
  }

  public String getBase64Handle() {
    return megaJNI.MegaNode_getBase64Handle(swigCPtr, this);
  }

  public long getSize() {
    return megaJNI.MegaNode_getSize(swigCPtr, this);
  }

  public long getCreationTime() {
    return megaJNI.MegaNode_getCreationTime(swigCPtr, this);
  }

  public long getModificationTime() {
    return megaJNI.MegaNode_getModificationTime(swigCPtr, this);
  }

  public long getHandle() {
    return megaJNI.MegaNode_getHandle(swigCPtr, this);
  }

  public long getRestoreHandle() {
    return megaJNI.MegaNode_getRestoreHandle(swigCPtr, this);
  }

  public long getParentHandle() {
    return megaJNI.MegaNode_getParentHandle(swigCPtr, this);
  }

  public String getBase64Key() {
    return megaJNI.MegaNode_getBase64Key(swigCPtr, this);
  }

  public long getExpirationTime() {
    return megaJNI.MegaNode_getExpirationTime(swigCPtr, this);
  }

  public long getPublicHandle() {
    return megaJNI.MegaNode_getPublicHandle(swigCPtr, this);
  }

  public MegaNode getPublicNode() {
    long cPtr = megaJNI.MegaNode_getPublicNode(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaNode(cPtr, true);
  }

  public String getPublicLink(boolean includeKey) {
    return megaJNI.MegaNode_getPublicLink__SWIG_0(swigCPtr, this, includeKey);
  }

  public String getPublicLink() {
    return megaJNI.MegaNode_getPublicLink__SWIG_1(swigCPtr, this);
  }

  public long getPublicLinkCreationTime() {
    return megaJNI.MegaNode_getPublicLinkCreationTime(swigCPtr, this);
  }

  public String getWritableLinkAuthKey() {
    return megaJNI.MegaNode_getWritableLinkAuthKey(swigCPtr, this);
  }

  public boolean isFile() {
    return megaJNI.MegaNode_isFile(swigCPtr, this);
  }

  public boolean isFolder() {
    return megaJNI.MegaNode_isFolder(swigCPtr, this);
  }

  public boolean isRemoved() {
    return megaJNI.MegaNode_isRemoved(swigCPtr, this);
  }

  public boolean hasChanged(long changeType) {
    return megaJNI.MegaNode_hasChanged(swigCPtr, this, changeType);
  }

  public long getChanges() {
    return megaJNI.MegaNode_getChanges(swigCPtr, this);
  }

  public boolean hasThumbnail() {
    return megaJNI.MegaNode_hasThumbnail(swigCPtr, this);
  }

  public boolean hasPreview() {
    return megaJNI.MegaNode_hasPreview(swigCPtr, this);
  }

  public boolean isPublic() {
    return megaJNI.MegaNode_isPublic(swigCPtr, this);
  }

  public boolean isShared() {
    return megaJNI.MegaNode_isShared(swigCPtr, this);
  }

  public boolean isOutShare() {
    return megaJNI.MegaNode_isOutShare(swigCPtr, this);
  }

  public boolean isInShare() {
    return megaJNI.MegaNode_isInShare(swigCPtr, this);
  }

  public boolean isExported() {
    return megaJNI.MegaNode_isExported(swigCPtr, this);
  }

  public boolean isExpired() {
    return megaJNI.MegaNode_isExpired(swigCPtr, this);
  }

  public boolean isTakenDown() {
    return megaJNI.MegaNode_isTakenDown(swigCPtr, this);
  }

  public boolean isForeign() {
    return megaJNI.MegaNode_isForeign(swigCPtr, this);
  }

  public boolean isCreditCardNode() {
    return megaJNI.MegaNode_isCreditCardNode(swigCPtr, this);
  }

  public boolean isPasswordNode() {
    return megaJNI.MegaNode_isPasswordNode(swigCPtr, this);
  }

  public boolean isPasswordManagerNode() {
    return megaJNI.MegaNode_isPasswordManagerNode(swigCPtr, this);
  }

  public MegaNode.CreditCardNodeData getCreditCardData() {
    long cPtr = megaJNI.MegaNode_getCreditCardData(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaNode.CreditCardNodeData(cPtr, true);
  }

  public MegaNode.PasswordNodeData getPasswordData() {
    long cPtr = megaJNI.MegaNode_getPasswordData(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaNode.PasswordNodeData(cPtr, true);
  }

  public boolean isNodeKeyDecrypted() {
    return megaJNI.MegaNode_isNodeKeyDecrypted(swigCPtr, this);
  }

  public String getFileAttrString() {
    return megaJNI.MegaNode_getFileAttrString(swigCPtr, this);
  }

  public void setPrivateAuth(String privateAuth) {
    megaJNI.MegaNode_setPrivateAuth(swigCPtr, this, privateAuth);
  }

  public MegaNodeList getChildren() {
    long cPtr = megaJNI.MegaNode_getChildren(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaNodeList(cPtr, false);
  }

  public long getOwner() {
    return megaJNI.MegaNode_getOwner(swigCPtr, this);
  }

  public String getDeviceId() {
    return megaJNI.MegaNode_getDeviceId(swigCPtr, this);
  }

  public String getS4() {
    return megaJNI.MegaNode_getS4(swigCPtr, this);
  }

  public String serialize() {
    return megaJNI.MegaNode_serialize(swigCPtr, this);
  }

  public static MegaNode unserialize(String d) {
    long cPtr = megaJNI.MegaNode_unserialize(d);
    return (cPtr == 0) ? null : new MegaNode(cPtr, true);
  }

  public MegaNode() {
    this(megaJNI.new_MegaNode(), true);
  }

  public final static int TYPE_UNKNOWN = -1;
  public final static int TYPE_FILE = 0;
  public final static int TYPE_FOLDER = 1;
  public final static int TYPE_ROOT = 2;
  public final static int TYPE_VAULT = 3;
  public final static int TYPE_INCOMING = TYPE_VAULT;
  public final static int TYPE_RUBBISH = 4;

  public final static int NODE_LBL_UNKNOWN = 0;
  public final static int NODE_LBL_RED = NODE_LBL_UNKNOWN + 1;
  public final static int NODE_LBL_ORANGE = NODE_LBL_RED + 1;
  public final static int NODE_LBL_YELLOW = NODE_LBL_ORANGE + 1;
  public final static int NODE_LBL_GREEN = NODE_LBL_YELLOW + 1;
  public final static int NODE_LBL_BLUE = NODE_LBL_GREEN + 1;
  public final static int NODE_LBL_PURPLE = NODE_LBL_BLUE + 1;
  public final static int NODE_LBL_GREY = NODE_LBL_PURPLE + 1;

  public final static int CHANGE_TYPE_REMOVED = 1;
  public final static int CHANGE_TYPE_ATTRIBUTES = 2;
  public final static int CHANGE_TYPE_OWNER = 4;
  public final static int CHANGE_TYPE_TIMESTAMP = 8;
  public final static int CHANGE_TYPE_FILE_ATTRIBUTES = 16;
  public final static int CHANGE_TYPE_INSHARE = 32;
  public final static int CHANGE_TYPE_OUTSHARE = 64;
  public final static int CHANGE_TYPE_PARENT = 128;
  public final static int CHANGE_TYPE_PENDINGSHARE = 256;
  public final static int CHANGE_TYPE_PUBLIC_LINK = 512;
  public final static int CHANGE_TYPE_NEW = 1024;
  public final static int CHANGE_TYPE_NAME = 2048;
  public final static int CHANGE_TYPE_FAVOURITE = 4096;
  public final static int CHANGE_TYPE_COUNTER = 8192;
  public final static int CHANGE_TYPE_SENSITIVE = 16384;
  public final static int CHANGE_TYPE_PWD = 32768;
  public final static int CHANGE_TYPE_DESCRIPTION = 65536;
  public final static int CHANGE_TYPE_TAGS = 131072;

  public final static int INVALID_DURATION = -1;
}
