/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

class MegaListener {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaListener(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaListener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaListener obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaListener(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    megaJNI.MegaListener_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    megaJNI.MegaListener_change_ownership(this, swigCPtr, true);
  }

  public void onRequestStart(MegaApi api, MegaRequest request) {
    if (getClass() == MegaListener.class) megaJNI.MegaListener_onRequestStart(swigCPtr, this, MegaApi.getCPtr(api), api, MegaRequest.getCPtr(request), request); else megaJNI.MegaListener_onRequestStartSwigExplicitMegaListener(swigCPtr, this, MegaApi.getCPtr(api), api, MegaRequest.getCPtr(request), request);
  }

  public void onRequestFinish(MegaApi api, MegaRequest request, MegaError e) {
    if (getClass() == MegaListener.class) megaJNI.MegaListener_onRequestFinish(swigCPtr, this, MegaApi.getCPtr(api), api, MegaRequest.getCPtr(request), request, MegaError.getCPtr(e), e); else megaJNI.MegaListener_onRequestFinishSwigExplicitMegaListener(swigCPtr, this, MegaApi.getCPtr(api), api, MegaRequest.getCPtr(request), request, MegaError.getCPtr(e), e);
  }

  public void onRequestUpdate(MegaApi api, MegaRequest request) {
    if (getClass() == MegaListener.class) megaJNI.MegaListener_onRequestUpdate(swigCPtr, this, MegaApi.getCPtr(api), api, MegaRequest.getCPtr(request), request); else megaJNI.MegaListener_onRequestUpdateSwigExplicitMegaListener(swigCPtr, this, MegaApi.getCPtr(api), api, MegaRequest.getCPtr(request), request);
  }

  public void onRequestTemporaryError(MegaApi api, MegaRequest request, MegaError error) {
    if (getClass() == MegaListener.class) megaJNI.MegaListener_onRequestTemporaryError(swigCPtr, this, MegaApi.getCPtr(api), api, MegaRequest.getCPtr(request), request, MegaError.getCPtr(error), error); else megaJNI.MegaListener_onRequestTemporaryErrorSwigExplicitMegaListener(swigCPtr, this, MegaApi.getCPtr(api), api, MegaRequest.getCPtr(request), request, MegaError.getCPtr(error), error);
  }

  public void onTransferStart(MegaApi api, MegaTransfer transfer) {
    if (getClass() == MegaListener.class) megaJNI.MegaListener_onTransferStart(swigCPtr, this, MegaApi.getCPtr(api), api, MegaTransfer.getCPtr(transfer), transfer); else megaJNI.MegaListener_onTransferStartSwigExplicitMegaListener(swigCPtr, this, MegaApi.getCPtr(api), api, MegaTransfer.getCPtr(transfer), transfer);
  }

  public void onTransferFinish(MegaApi api, MegaTransfer transfer, MegaError error) {
    if (getClass() == MegaListener.class) megaJNI.MegaListener_onTransferFinish(swigCPtr, this, MegaApi.getCPtr(api), api, MegaTransfer.getCPtr(transfer), transfer, MegaError.getCPtr(error), error); else megaJNI.MegaListener_onTransferFinishSwigExplicitMegaListener(swigCPtr, this, MegaApi.getCPtr(api), api, MegaTransfer.getCPtr(transfer), transfer, MegaError.getCPtr(error), error);
  }

  public void onTransferUpdate(MegaApi api, MegaTransfer transfer) {
    if (getClass() == MegaListener.class) megaJNI.MegaListener_onTransferUpdate(swigCPtr, this, MegaApi.getCPtr(api), api, MegaTransfer.getCPtr(transfer), transfer); else megaJNI.MegaListener_onTransferUpdateSwigExplicitMegaListener(swigCPtr, this, MegaApi.getCPtr(api), api, MegaTransfer.getCPtr(transfer), transfer);
  }

  public void onTransferTemporaryError(MegaApi api, MegaTransfer transfer, MegaError error) {
    if (getClass() == MegaListener.class) megaJNI.MegaListener_onTransferTemporaryError(swigCPtr, this, MegaApi.getCPtr(api), api, MegaTransfer.getCPtr(transfer), transfer, MegaError.getCPtr(error), error); else megaJNI.MegaListener_onTransferTemporaryErrorSwigExplicitMegaListener(swigCPtr, this, MegaApi.getCPtr(api), api, MegaTransfer.getCPtr(transfer), transfer, MegaError.getCPtr(error), error);
  }

  public void onUsersUpdate(MegaApi api, MegaUserList users) {
    if (getClass() == MegaListener.class) megaJNI.MegaListener_onUsersUpdate(swigCPtr, this, MegaApi.getCPtr(api), api, MegaUserList.getCPtr(users), users); else megaJNI.MegaListener_onUsersUpdateSwigExplicitMegaListener(swigCPtr, this, MegaApi.getCPtr(api), api, MegaUserList.getCPtr(users), users);
  }

  public void onUserAlertsUpdate(MegaApi api, MegaUserAlertList alerts) {
    if (getClass() == MegaListener.class) megaJNI.MegaListener_onUserAlertsUpdate(swigCPtr, this, MegaApi.getCPtr(api), api, MegaUserAlertList.getCPtr(alerts), alerts); else megaJNI.MegaListener_onUserAlertsUpdateSwigExplicitMegaListener(swigCPtr, this, MegaApi.getCPtr(api), api, MegaUserAlertList.getCPtr(alerts), alerts);
  }

  public void onNodesUpdate(MegaApi api, MegaNodeList nodes) {
    if (getClass() == MegaListener.class) megaJNI.MegaListener_onNodesUpdate(swigCPtr, this, MegaApi.getCPtr(api), api, MegaNodeList.getCPtr(nodes), nodes); else megaJNI.MegaListener_onNodesUpdateSwigExplicitMegaListener(swigCPtr, this, MegaApi.getCPtr(api), api, MegaNodeList.getCPtr(nodes), nodes);
  }

  public void onAccountUpdate(MegaApi api) {
    if (getClass() == MegaListener.class) megaJNI.MegaListener_onAccountUpdate(swigCPtr, this, MegaApi.getCPtr(api), api); else megaJNI.MegaListener_onAccountUpdateSwigExplicitMegaListener(swigCPtr, this, MegaApi.getCPtr(api), api);
  }

  public void onSetsUpdate(MegaApi api, MegaSetList sets) {
    if (getClass() == MegaListener.class) megaJNI.MegaListener_onSetsUpdate(swigCPtr, this, MegaApi.getCPtr(api), api, MegaSetList.getCPtr(sets), sets); else megaJNI.MegaListener_onSetsUpdateSwigExplicitMegaListener(swigCPtr, this, MegaApi.getCPtr(api), api, MegaSetList.getCPtr(sets), sets);
  }

  public void onSetElementsUpdate(MegaApi api, MegaSetElementList elements) {
    if (getClass() == MegaListener.class) megaJNI.MegaListener_onSetElementsUpdate(swigCPtr, this, MegaApi.getCPtr(api), api, MegaSetElementList.getCPtr(elements), elements); else megaJNI.MegaListener_onSetElementsUpdateSwigExplicitMegaListener(swigCPtr, this, MegaApi.getCPtr(api), api, MegaSetElementList.getCPtr(elements), elements);
  }

  public void onContactRequestsUpdate(MegaApi api, MegaContactRequestList requests) {
    if (getClass() == MegaListener.class) megaJNI.MegaListener_onContactRequestsUpdate(swigCPtr, this, MegaApi.getCPtr(api), api, MegaContactRequestList.getCPtr(requests), requests); else megaJNI.MegaListener_onContactRequestsUpdateSwigExplicitMegaListener(swigCPtr, this, MegaApi.getCPtr(api), api, MegaContactRequestList.getCPtr(requests), requests);
  }

  public void onSyncAdded(MegaApi api, MegaSync sync) {
    if (getClass() == MegaListener.class) megaJNI.MegaListener_onSyncAdded(swigCPtr, this, MegaApi.getCPtr(api), api, MegaSync.getCPtr(sync), sync); else megaJNI.MegaListener_onSyncAddedSwigExplicitMegaListener(swigCPtr, this, MegaApi.getCPtr(api), api, MegaSync.getCPtr(sync), sync);
  }

  public void onSyncDeleted(MegaApi api, MegaSync sync) {
    if (getClass() == MegaListener.class) megaJNI.MegaListener_onSyncDeleted(swigCPtr, this, MegaApi.getCPtr(api), api, MegaSync.getCPtr(sync), sync); else megaJNI.MegaListener_onSyncDeletedSwigExplicitMegaListener(swigCPtr, this, MegaApi.getCPtr(api), api, MegaSync.getCPtr(sync), sync);
  }

  public void onSyncStateChanged(MegaApi api, MegaSync sync) {
    if (getClass() == MegaListener.class) megaJNI.MegaListener_onSyncStateChanged(swigCPtr, this, MegaApi.getCPtr(api), api, MegaSync.getCPtr(sync), sync); else megaJNI.MegaListener_onSyncStateChangedSwigExplicitMegaListener(swigCPtr, this, MegaApi.getCPtr(api), api, MegaSync.getCPtr(sync), sync);
  }

  public void onSyncStatsUpdated(MegaApi api, MegaSyncStats syncStats) {
    if (getClass() == MegaListener.class) megaJNI.MegaListener_onSyncStatsUpdated(swigCPtr, this, MegaApi.getCPtr(api), api, MegaSyncStats.getCPtr(syncStats), syncStats); else megaJNI.MegaListener_onSyncStatsUpdatedSwigExplicitMegaListener(swigCPtr, this, MegaApi.getCPtr(api), api, MegaSyncStats.getCPtr(syncStats), syncStats);
  }

  public void onGlobalSyncStateChanged(MegaApi api) {
    if (getClass() == MegaListener.class) megaJNI.MegaListener_onGlobalSyncStateChanged(swigCPtr, this, MegaApi.getCPtr(api), api); else megaJNI.MegaListener_onGlobalSyncStateChangedSwigExplicitMegaListener(swigCPtr, this, MegaApi.getCPtr(api), api);
  }

  public void onSyncRemoteRootChanged(MegaApi api, MegaSync sync) {
    if (getClass() == MegaListener.class) megaJNI.MegaListener_onSyncRemoteRootChanged(swigCPtr, this, MegaApi.getCPtr(api), api, MegaSync.getCPtr(sync), sync); else megaJNI.MegaListener_onSyncRemoteRootChangedSwigExplicitMegaListener(swigCPtr, this, MegaApi.getCPtr(api), api, MegaSync.getCPtr(sync), sync);
  }

  public void onBackupStateChanged(MegaApi api, MegaScheduledCopy backup) {
    if (getClass() == MegaListener.class) megaJNI.MegaListener_onBackupStateChanged(swigCPtr, this, MegaApi.getCPtr(api), api, MegaScheduledCopy.getCPtr(backup), backup); else megaJNI.MegaListener_onBackupStateChangedSwigExplicitMegaListener(swigCPtr, this, MegaApi.getCPtr(api), api, MegaScheduledCopy.getCPtr(backup), backup);
  }

  public void onBackupStart(MegaApi api, MegaScheduledCopy backup) {
    if (getClass() == MegaListener.class) megaJNI.MegaListener_onBackupStart(swigCPtr, this, MegaApi.getCPtr(api), api, MegaScheduledCopy.getCPtr(backup), backup); else megaJNI.MegaListener_onBackupStartSwigExplicitMegaListener(swigCPtr, this, MegaApi.getCPtr(api), api, MegaScheduledCopy.getCPtr(backup), backup);
  }

  public void onBackupFinish(MegaApi api, MegaScheduledCopy backup, MegaError error) {
    if (getClass() == MegaListener.class) megaJNI.MegaListener_onBackupFinish(swigCPtr, this, MegaApi.getCPtr(api), api, MegaScheduledCopy.getCPtr(backup), backup, MegaError.getCPtr(error), error); else megaJNI.MegaListener_onBackupFinishSwigExplicitMegaListener(swigCPtr, this, MegaApi.getCPtr(api), api, MegaScheduledCopy.getCPtr(backup), backup, MegaError.getCPtr(error), error);
  }

  public void onBackupUpdate(MegaApi api, MegaScheduledCopy backup) {
    if (getClass() == MegaListener.class) megaJNI.MegaListener_onBackupUpdate(swigCPtr, this, MegaApi.getCPtr(api), api, MegaScheduledCopy.getCPtr(backup), backup); else megaJNI.MegaListener_onBackupUpdateSwigExplicitMegaListener(swigCPtr, this, MegaApi.getCPtr(api), api, MegaScheduledCopy.getCPtr(backup), backup);
  }

  public void onBackupTemporaryError(MegaApi api, MegaScheduledCopy backup, MegaError error) {
    if (getClass() == MegaListener.class) megaJNI.MegaListener_onBackupTemporaryError(swigCPtr, this, MegaApi.getCPtr(api), api, MegaScheduledCopy.getCPtr(backup), backup, MegaError.getCPtr(error), error); else megaJNI.MegaListener_onBackupTemporaryErrorSwigExplicitMegaListener(swigCPtr, this, MegaApi.getCPtr(api), api, MegaScheduledCopy.getCPtr(backup), backup, MegaError.getCPtr(error), error);
  }

  public void onChatsUpdate(MegaApi api, MegaTextChatList chats) {
    if (getClass() == MegaListener.class) megaJNI.MegaListener_onChatsUpdate(swigCPtr, this, MegaApi.getCPtr(api), api, MegaTextChatList.getCPtr(chats), chats); else megaJNI.MegaListener_onChatsUpdateSwigExplicitMegaListener(swigCPtr, this, MegaApi.getCPtr(api), api, MegaTextChatList.getCPtr(chats), chats);
  }

  public void onEvent(MegaApi api, MegaEvent event) {
    if (getClass() == MegaListener.class) megaJNI.MegaListener_onEvent(swigCPtr, this, MegaApi.getCPtr(api), api, MegaEvent.getCPtr(event), event); else megaJNI.MegaListener_onEventSwigExplicitMegaListener(swigCPtr, this, MegaApi.getCPtr(api), api, MegaEvent.getCPtr(event), event);
  }

  public void onMountAdded(MegaApi api, String path, int megaMountResult) {
    if (getClass() == MegaListener.class) megaJNI.MegaListener_onMountAdded(swigCPtr, this, MegaApi.getCPtr(api), api, path, megaMountResult); else megaJNI.MegaListener_onMountAddedSwigExplicitMegaListener(swigCPtr, this, MegaApi.getCPtr(api), api, path, megaMountResult);
  }

  public void onMountChanged(MegaApi api, String path, int megaMountResult) {
    if (getClass() == MegaListener.class) megaJNI.MegaListener_onMountChanged(swigCPtr, this, MegaApi.getCPtr(api), api, path, megaMountResult); else megaJNI.MegaListener_onMountChangedSwigExplicitMegaListener(swigCPtr, this, MegaApi.getCPtr(api), api, path, megaMountResult);
  }

  public void onMountDisabled(MegaApi api, String path, int megaMountResult) {
    if (getClass() == MegaListener.class) megaJNI.MegaListener_onMountDisabled(swigCPtr, this, MegaApi.getCPtr(api), api, path, megaMountResult); else megaJNI.MegaListener_onMountDisabledSwigExplicitMegaListener(swigCPtr, this, MegaApi.getCPtr(api), api, path, megaMountResult);
  }

  public void onMountEnabled(MegaApi api, String path, int megaMountResult) {
    if (getClass() == MegaListener.class) megaJNI.MegaListener_onMountEnabled(swigCPtr, this, MegaApi.getCPtr(api), api, path, megaMountResult); else megaJNI.MegaListener_onMountEnabledSwigExplicitMegaListener(swigCPtr, this, MegaApi.getCPtr(api), api, path, megaMountResult);
  }

  public void onMountRemoved(MegaApi api, String path, int megaMountResult) {
    if (getClass() == MegaListener.class) megaJNI.MegaListener_onMountRemoved(swigCPtr, this, MegaApi.getCPtr(api), api, path, megaMountResult); else megaJNI.MegaListener_onMountRemovedSwigExplicitMegaListener(swigCPtr, this, MegaApi.getCPtr(api), api, path, megaMountResult);
  }

  @SuppressWarnings("this-escape")
  public MegaListener() {
    this(megaJNI.new_MegaListener(), true);
    megaJNI.MegaListener_director_connect(this, swigCPtr, true, true);
  }

}
