/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaScheduledMeeting {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaScheduledMeeting(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaScheduledMeeting obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaScheduledMeeting obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaScheduledMeeting(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public static MegaScheduledMeeting createInstance(long chatid, long schedId, long parentSchedId, long organizerUserId, int cancelled, String timezone, long startDateTime, long endDateTime, String title, String description, String attributes, long overrides, MegaScheduledFlags flags, MegaScheduledRules rules) {
    long cPtr = megaJNI.MegaScheduledMeeting_createInstance(chatid, schedId, parentSchedId, organizerUserId, cancelled, timezone, startDateTime, endDateTime, title, description, attributes, overrides, MegaScheduledFlags.getCPtr(flags), flags, MegaScheduledRules.getCPtr(rules), rules);
    return (cPtr == 0) ? null : new MegaScheduledMeeting(cPtr, false);
  }

   MegaScheduledMeeting copy() {
    long cPtr = megaJNI.MegaScheduledMeeting_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaScheduledMeeting(cPtr, false);
  }

  public int cancelled() {
    return megaJNI.MegaScheduledMeeting_cancelled(swigCPtr, this);
  }

  public long chatid() {
    return megaJNI.MegaScheduledMeeting_chatid(swigCPtr, this);
  }

  public long schedId() {
    return megaJNI.MegaScheduledMeeting_schedId(swigCPtr, this);
  }

  public long organizerUserid() {
    return megaJNI.MegaScheduledMeeting_organizerUserid(swigCPtr, this);
  }

  public long parentSchedId() {
    return megaJNI.MegaScheduledMeeting_parentSchedId(swigCPtr, this);
  }

  public String timezone() {
    return megaJNI.MegaScheduledMeeting_timezone(swigCPtr, this);
  }

  public long startDateTime() {
    return megaJNI.MegaScheduledMeeting_startDateTime(swigCPtr, this);
  }

  public long endDateTime() {
    return megaJNI.MegaScheduledMeeting_endDateTime(swigCPtr, this);
  }

  public String title() {
    return megaJNI.MegaScheduledMeeting_title(swigCPtr, this);
  }

  public String description() {
    return megaJNI.MegaScheduledMeeting_description(swigCPtr, this);
  }

  public String attributes() {
    return megaJNI.MegaScheduledMeeting_attributes(swigCPtr, this);
  }

  public long overrides() {
    return megaJNI.MegaScheduledMeeting_overrides(swigCPtr, this);
  }

  public MegaScheduledFlags flags() {
    long cPtr = megaJNI.MegaScheduledMeeting_flags(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaScheduledFlags(cPtr, false);
  }

  public MegaScheduledRules rules() {
    long cPtr = megaJNI.MegaScheduledMeeting_rules(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaScheduledRules(cPtr, false);
  }

  public MegaScheduledMeeting() {
    this(megaJNI.new_MegaScheduledMeeting(), true);
  }

}
