/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaFlag {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaFlag(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaFlag obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaFlag obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaFlag(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public long getType() {
    return megaJNI.MegaFlag_getType(swigCPtr, this);
  }

  public long getGroup() {
    return megaJNI.MegaFlag_getGroup(swigCPtr, this);
  }

  public final static int FLAG_TYPE_INVALID = 0;
  public final static int FLAG_TYPE_AB_TEST = 1;
  public final static int FLAG_TYPE_FEATURE = 2;

}
