/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaCompleteUploadData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaCompleteUploadData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaCompleteUploadData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaCompleteUploadData obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaCompleteUploadData(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public static MegaCompleteUploadData createInstance(String fingerprint, String string64UploadToken, String string64FileKey) {
    long cPtr = megaJNI.MegaCompleteUploadData_createInstance(fingerprint, string64UploadToken, string64FileKey);
    return (cPtr == 0) ? null : new MegaCompleteUploadData(cPtr, false);
  }

   MegaCompleteUploadData copy() {
    long cPtr = megaJNI.MegaCompleteUploadData_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaCompleteUploadData(cPtr, false);
  }

}
