/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaStringListMap {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaStringListMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaStringListMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaStringListMap obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaStringListMap(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public static MegaStringListMap createInstance() {
    long cPtr = megaJNI.MegaStringListMap_createInstance();
    return (cPtr == 0) ? null : new MegaStringListMap(cPtr, false);
  }

   MegaStringListMap copy() {
    long cPtr = megaJNI.MegaStringListMap_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaStringListMap(cPtr, false);
  }

  public MegaStringList get(String key) {
    long cPtr = megaJNI.MegaStringListMap_get(swigCPtr, this, key);
    return (cPtr == 0) ? null : new MegaStringList(cPtr, false);
  }

  public MegaStringList getKeys() {
    long cPtr = megaJNI.MegaStringListMap_getKeys(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaStringList(cPtr, false);
  }

  public void set(String key, MegaStringList value) {
    megaJNI.MegaStringListMap_set(swigCPtr, this, key, MegaStringList.getCPtr(value), value);
  }

  public int size() {
    return megaJNI.MegaStringListMap_size(swigCPtr, this);
  }

}
