/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaSearchLexicographicalOffset {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaSearchLexicographicalOffset(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaSearchLexicographicalOffset obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaSearchLexicographicalOffset obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaSearchLexicographicalOffset(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public void setMLastName(String value) {
    megaJNI.MegaSearchLexicographicalOffset_mLastName_set(swigCPtr, this, value);
  }

  public String getMLastName() {
    return megaJNI.MegaSearchLexicographicalOffset_mLastName_get(swigCPtr, this);
  }

  public void setMLastType(SWIGTYPE_p_std__optionalT_int_t value) {
    megaJNI.MegaSearchLexicographicalOffset_mLastType_set(swigCPtr, this, SWIGTYPE_p_std__optionalT_int_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__optionalT_int_t getMLastType() {
    return new SWIGTYPE_p_std__optionalT_int_t(megaJNI.MegaSearchLexicographicalOffset_mLastType_get(swigCPtr, this), true);
  }

  public void setMLastHandle(SWIGTYPE_p_std__optionalT_long_long_t value) {
    megaJNI.MegaSearchLexicographicalOffset_mLastHandle_set(swigCPtr, this, SWIGTYPE_p_std__optionalT_long_long_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__optionalT_long_long_t getMLastHandle() {
    return new SWIGTYPE_p_std__optionalT_long_long_t(megaJNI.MegaSearchLexicographicalOffset_mLastHandle_get(swigCPtr, this), true);
  }

  public MegaSearchLexicographicalOffset() {
    this(megaJNI.new_MegaSearchLexicographicalOffset(), true);
  }

}
