/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaNotificationList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaNotificationList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaNotificationList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaNotificationList obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaNotificationList(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public MegaNotification get(long i) {
    long cPtr = megaJNI.MegaNotificationList_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new MegaNotification(cPtr, false);
  }

  public long size() {
    return megaJNI.MegaNotificationList_size(swigCPtr, this);
  }

   MegaNotificationList copy() {
    long cPtr = megaJNI.MegaNotificationList_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaNotificationList(cPtr, false);
  }

}
