/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaScheduledRules {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaScheduledRules(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaScheduledRules obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaScheduledRules obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaScheduledRules(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public static MegaScheduledRules createInstance(int freq, int interval, long until, MegaIntegerList byWeekDay, MegaIntegerList byMonthDay, MegaIntegerMap byMonthWeekDay) {
    long cPtr = megaJNI.MegaScheduledRules_createInstance__SWIG_0(freq, interval, until, MegaIntegerList.getCPtr(byWeekDay), byWeekDay, MegaIntegerList.getCPtr(byMonthDay), byMonthDay, MegaIntegerMap.getCPtr(byMonthWeekDay), byMonthWeekDay);
    return (cPtr == 0) ? null : new MegaScheduledRules(cPtr, false);
  }

  public static MegaScheduledRules createInstance(int freq, int interval, long until, MegaIntegerList byWeekDay, MegaIntegerList byMonthDay) {
    long cPtr = megaJNI.MegaScheduledRules_createInstance__SWIG_1(freq, interval, until, MegaIntegerList.getCPtr(byWeekDay), byWeekDay, MegaIntegerList.getCPtr(byMonthDay), byMonthDay);
    return (cPtr == 0) ? null : new MegaScheduledRules(cPtr, false);
  }

  public static MegaScheduledRules createInstance(int freq, int interval, long until, MegaIntegerList byWeekDay) {
    long cPtr = megaJNI.MegaScheduledRules_createInstance__SWIG_2(freq, interval, until, MegaIntegerList.getCPtr(byWeekDay), byWeekDay);
    return (cPtr == 0) ? null : new MegaScheduledRules(cPtr, false);
  }

  public static MegaScheduledRules createInstance(int freq, int interval, long until) {
    long cPtr = megaJNI.MegaScheduledRules_createInstance__SWIG_3(freq, interval, until);
    return (cPtr == 0) ? null : new MegaScheduledRules(cPtr, false);
  }

  public static MegaScheduledRules createInstance(int freq, int interval) {
    long cPtr = megaJNI.MegaScheduledRules_createInstance__SWIG_4(freq, interval);
    return (cPtr == 0) ? null : new MegaScheduledRules(cPtr, false);
  }

  public static MegaScheduledRules createInstance(int freq) {
    long cPtr = megaJNI.MegaScheduledRules_createInstance__SWIG_5(freq);
    return (cPtr == 0) ? null : new MegaScheduledRules(cPtr, false);
  }

   MegaScheduledRules copy() {
    long cPtr = megaJNI.MegaScheduledRules_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaScheduledRules(cPtr, false);
  }

  public int freq() {
    return megaJNI.MegaScheduledRules_freq(swigCPtr, this);
  }

  public int interval() {
    return megaJNI.MegaScheduledRules_interval(swigCPtr, this);
  }

  public long until() {
    return megaJNI.MegaScheduledRules_until(swigCPtr, this);
  }

  public MegaIntegerList byWeekDay() {
    long cPtr = megaJNI.MegaScheduledRules_byWeekDay(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaIntegerList(cPtr, false);
  }

  public MegaIntegerList byMonthDay() {
    long cPtr = megaJNI.MegaScheduledRules_byMonthDay(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaIntegerList(cPtr, false);
  }

  public MegaIntegerMap byMonthWeekDay() {
    long cPtr = megaJNI.MegaScheduledRules_byMonthWeekDay(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaIntegerMap(cPtr, false);
  }

  public static boolean isValidFreq(int freq) {
    return megaJNI.MegaScheduledRules_isValidFreq(freq);
  }

  public static boolean isValidInterval(int interval) {
    return megaJNI.MegaScheduledRules_isValidInterval(interval);
  }

  public MegaScheduledRules() {
    this(megaJNI.new_MegaScheduledRules(), true);
  }

  public final static int FREQ_INVALID = -1;
  public final static int FREQ_DAILY = 0;
  public final static int FREQ_WEEKLY = 1;
  public final static int FREQ_MONTHLY = 2;

  public final static int INTERVAL_INVALID = 0;
}
