/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaAccountDetails {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaAccountDetails(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaAccountDetails obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaAccountDetails obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaAccountDetails(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public int getProLevel() {
    return megaJNI.MegaAccountDetails_getProLevel(swigCPtr, this);
  }

  public long getProExpiration() {
    return megaJNI.MegaAccountDetails_getProExpiration(swigCPtr, this);
  }

  public int getSubscriptionStatus() {
    return megaJNI.MegaAccountDetails_getSubscriptionStatus(swigCPtr, this);
  }

  public long getSubscriptionRenewTime() {
    return megaJNI.MegaAccountDetails_getSubscriptionRenewTime(swigCPtr, this);
  }

  public String getSubscriptionMethod() {
    return megaJNI.MegaAccountDetails_getSubscriptionMethod(swigCPtr, this);
  }

  public int getSubscriptionMethodId() {
    return megaJNI.MegaAccountDetails_getSubscriptionMethodId(swigCPtr, this);
  }

  public String getSubscriptionCycle() {
    return megaJNI.MegaAccountDetails_getSubscriptionCycle(swigCPtr, this);
  }

  public long getStorageMax() {
    return megaJNI.MegaAccountDetails_getStorageMax(swigCPtr, this);
  }

  public long getStorageUsed() {
    return megaJNI.MegaAccountDetails_getStorageUsed__SWIG_0(swigCPtr, this);
  }

  public long getVersionStorageUsed() {
    return megaJNI.MegaAccountDetails_getVersionStorageUsed__SWIG_0(swigCPtr, this);
  }

  public long getTransferMax() {
    return megaJNI.MegaAccountDetails_getTransferMax(swigCPtr, this);
  }

  public long getTransferOwnUsed() {
    return megaJNI.MegaAccountDetails_getTransferOwnUsed(swigCPtr, this);
  }

  public long getTransferSrvUsed() {
    return megaJNI.MegaAccountDetails_getTransferSrvUsed(swigCPtr, this);
  }

  public long getTransferUsed() {
    return megaJNI.MegaAccountDetails_getTransferUsed(swigCPtr, this);
  }

  public int getNumUsageItems() {
    return megaJNI.MegaAccountDetails_getNumUsageItems(swigCPtr, this);
  }

  public long getStorageUsed(long handle) {
    return megaJNI.MegaAccountDetails_getStorageUsed__SWIG_1(swigCPtr, this, handle);
  }

  public long getNumFiles(long handle) {
    return megaJNI.MegaAccountDetails_getNumFiles(swigCPtr, this, handle);
  }

  public long getNumFolders(long handle) {
    return megaJNI.MegaAccountDetails_getNumFolders(swigCPtr, this, handle);
  }

  public long getVersionStorageUsed(long handle) {
    return megaJNI.MegaAccountDetails_getVersionStorageUsed__SWIG_1(swigCPtr, this, handle);
  }

  public long getNumVersionFiles(long handle) {
    return megaJNI.MegaAccountDetails_getNumVersionFiles(swigCPtr, this, handle);
  }

   MegaAccountDetails copy() {
    long cPtr = megaJNI.MegaAccountDetails_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaAccountDetails(cPtr, true);
  }

  public int getNumBalances() {
    return megaJNI.MegaAccountDetails_getNumBalances(swigCPtr, this);
  }

  public MegaAccountBalance getBalance(int i) {
    long cPtr = megaJNI.MegaAccountDetails_getBalance(swigCPtr, this, i);
    return (cPtr == 0) ? null : new MegaAccountBalance(cPtr, true);
  }

  public int getNumSessions() {
    return megaJNI.MegaAccountDetails_getNumSessions(swigCPtr, this);
  }

  public MegaAccountSession getSession(int i) {
    long cPtr = megaJNI.MegaAccountDetails_getSession(swigCPtr, this, i);
    return (cPtr == 0) ? null : new MegaAccountSession(cPtr, true);
  }

  public int getNumPurchases() {
    return megaJNI.MegaAccountDetails_getNumPurchases(swigCPtr, this);
  }

  public MegaAccountPurchase getPurchase(int i) {
    long cPtr = megaJNI.MegaAccountDetails_getPurchase(swigCPtr, this, i);
    return (cPtr == 0) ? null : new MegaAccountPurchase(cPtr, true);
  }

  public int getNumTransactions() {
    return megaJNI.MegaAccountDetails_getNumTransactions(swigCPtr, this);
  }

  public MegaAccountTransaction getTransaction(int i) {
    long cPtr = megaJNI.MegaAccountDetails_getTransaction(swigCPtr, this, i);
    return (cPtr == 0) ? null : new MegaAccountTransaction(cPtr, true);
  }

  public int getTemporalBandwidthInterval() {
    return megaJNI.MegaAccountDetails_getTemporalBandwidthInterval(swigCPtr, this);
  }

  public long getTemporalBandwidth() {
    return megaJNI.MegaAccountDetails_getTemporalBandwidth(swigCPtr, this);
  }

  public boolean isTemporalBandwidthValid() {
    return megaJNI.MegaAccountDetails_isTemporalBandwidthValid(swigCPtr, this);
  }

  public int getNumActiveFeatures() {
    return megaJNI.MegaAccountDetails_getNumActiveFeatures(swigCPtr, this);
  }

  public MegaAccountFeature getActiveFeature(int featureIndex) {
    long cPtr = megaJNI.MegaAccountDetails_getActiveFeature(swigCPtr, this, featureIndex);
    return (cPtr == 0) ? null : new MegaAccountFeature(cPtr, false);
  }

  public long getSubscriptionLevel() {
    return megaJNI.MegaAccountDetails_getSubscriptionLevel(swigCPtr, this);
  }

  public MegaStringIntegerMap getSubscriptionFeatures() {
    long cPtr = megaJNI.MegaAccountDetails_getSubscriptionFeatures(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaStringIntegerMap(cPtr, false);
  }

  public int getNumSubscriptions() {
    return megaJNI.MegaAccountDetails_getNumSubscriptions(swigCPtr, this);
  }

  public MegaAccountSubscription getSubscription(int subscriptionsIndex) {
    long cPtr = megaJNI.MegaAccountDetails_getSubscription(swigCPtr, this, subscriptionsIndex);
    return (cPtr == 0) ? null : new MegaAccountSubscription(cPtr, true);
  }

  public int getNumPlans() {
    return megaJNI.MegaAccountDetails_getNumPlans(swigCPtr, this);
  }

  public MegaAccountPlan getPlan(int plansIndex) {
    long cPtr = megaJNI.MegaAccountDetails_getPlan(swigCPtr, this, plansIndex);
    return (cPtr == 0) ? null : new MegaAccountPlan(cPtr, true);
  }

  public final static int ACCOUNT_TYPE_FREE = 0;
  public final static int ACCOUNT_TYPE_PROI = 1;
  public final static int ACCOUNT_TYPE_PROII = 2;
  public final static int ACCOUNT_TYPE_PROIII = 3;
  public final static int ACCOUNT_TYPE_LITE = 4;
  public final static int ACCOUNT_TYPE_STARTER = 11;
  public final static int ACCOUNT_TYPE_BASIC = 12;
  public final static int ACCOUNT_TYPE_ESSENTIAL = 13;
  public final static int ACCOUNT_TYPE_BUSINESS = 100;
  public final static int ACCOUNT_TYPE_PRO_FLEXI = 101;
  public final static int ACCOUNT_TYPE_FEATURE = 99999;

  public final static int SUBSCRIPTION_STATUS_NONE = 0;
  public final static int SUBSCRIPTION_STATUS_VALID = 1;
  public final static int SUBSCRIPTION_STATUS_INVALID = 2;

}
