/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaDiscountCode {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaDiscountCode(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaDiscountCode obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaDiscountCode obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaDiscountCode(swigCPtr);
      }
      swigCPtr = 0;
    }
}

   MegaDiscountCode copy() {
    long cPtr = megaJNI.MegaDiscountCode_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaDiscountCode(cPtr, false);
  }

  public String getCode() {
    return megaJNI.MegaDiscountCode_getCode(swigCPtr, this);
  }

  public int getItem() {
    return megaJNI.MegaDiscountCode_getItem(swigCPtr, this);
  }

  public int getAccountLevel() {
    return megaJNI.MegaDiscountCode_getAccountLevel(swigCPtr, this);
  }

  public int getMonths() {
    return megaJNI.MegaDiscountCode_getMonths(swigCPtr, this);
  }

  public int getPercentageDiscount() {
    return megaJNI.MegaDiscountCode_getPercentageDiscount(swigCPtr, this);
  }

  public int getBehaviorType() {
    return megaJNI.MegaDiscountCode_getBehaviorType(swigCPtr, this);
  }

}
