/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaSetElementList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaSetElementList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaSetElementList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaSetElementList obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaSetElementList(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public MegaSetElement get(long arg0) {
    long cPtr = megaJNI.MegaSetElementList_get(swigCPtr, this, arg0);
    return (cPtr == 0) ? null : new MegaSetElement(cPtr, false);
  }

  public long size() {
    return megaJNI.MegaSetElementList_size(swigCPtr, this);
  }

   MegaSetElementList copy() {
    long cPtr = megaJNI.MegaSetElementList_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaSetElementList(cPtr, false);
  }

  public MegaSetElementList() {
    this(megaJNI.new_MegaSetElementList(), true);
  }

}
