/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaSetElement {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaSetElement(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaSetElement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaSetElement obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaSetElement(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public long id() {
    return megaJNI.MegaSetElement_id(swigCPtr, this);
  }

  public long node() {
    return megaJNI.MegaSetElement_node(swigCPtr, this);
  }

  public long setId() {
    return megaJNI.MegaSetElement_setId(swigCPtr, this);
  }

  public long order() {
    return megaJNI.MegaSetElement_order(swigCPtr, this);
  }

  public long ts() {
    return megaJNI.MegaSetElement_ts(swigCPtr, this);
  }

  public String name() {
    return megaJNI.MegaSetElement_name(swigCPtr, this);
  }

  public boolean hasChanged(long arg0) {
    return megaJNI.MegaSetElement_hasChanged(swigCPtr, this, arg0);
  }

  public long getChanges() {
    return megaJNI.MegaSetElement_getChanges(swigCPtr, this);
  }

   MegaSetElement copy() {
    long cPtr = megaJNI.MegaSetElement_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaSetElement(cPtr, true);
  }

  public MegaSetElement() {
    this(megaJNI.new_MegaSetElement(), true);
  }

  public final static int CHANGE_TYPE_ELEM_NEW = 1;
  public final static int CHANGE_TYPE_ELEM_NAME = 2;
  public final static int CHANGE_TYPE_ELEM_ORDER = 4;
  public final static int CHANGE_TYPE_ELEM_REMOVED = 8;

}
