/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaTimeZoneDetails {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaTimeZoneDetails(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaTimeZoneDetails obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaTimeZoneDetails obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaTimeZoneDetails(swigCPtr);
      }
      swigCPtr = 0;
    }
}

   MegaTimeZoneDetails copy() {
    long cPtr = megaJNI.MegaTimeZoneDetails_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaTimeZoneDetails(cPtr, true);
  }

  public int getNumTimeZones() {
    return megaJNI.MegaTimeZoneDetails_getNumTimeZones(swigCPtr, this);
  }

  public String getTimeZone(int index) {
    return megaJNI.MegaTimeZoneDetails_getTimeZone(swigCPtr, this, index);
  }

  public int getTimeOffset(int index) {
    return megaJNI.MegaTimeZoneDetails_getTimeOffset(swigCPtr, this, index);
  }

  public int getDefault() {
    return megaJNI.MegaTimeZoneDetails_getDefault(swigCPtr, this);
  }

  public MegaTimeZoneDetails() {
    this(megaJNI.new_MegaTimeZoneDetails(), true);
  }

}
